### ISSUE TITLE
`autocomplete=device-eid` and `=device-imei`

### ISSUE THREAD

**Issue by saschanaz** [mozilla/standards-positions#1002]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Autocomplete tokens for EID and IMEI
* Specification or proposal URL (if available): https://github.com/whatwg/html/issues/9884
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): @annevk
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @smaug---- @zcorpan @tantek

**Comment by annevk** [comment]
The autofilling aspects need a fair amount of guardrails given the sensitivity of the data, but in principle the mechanism can work in general purpose user agents and it's definitely expected to be implemented by websites you can reach via a URL.

**Comment by zcorpan** [comment]
We think this proposal would set a precedent of adding a privacy-sensitive feature to HTML that don't apply to general-purpose UAs. Your comment above says it _could_ be implemented in a general-purpose UAs, but based on the text 
[@jgraham](https://mozilla.slack.com/team/U6CBQGM46) quoted it seems there's no such plan.

If such a plan materializes, we can reevaluate.
