### ISSUE TITLE
getHTML() and the serializable concept

### ISSUE THREAD

**Issue by zcorpan** [mozilla/standards-positions#1006]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: getHTML() and the serializable concept
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/10139
* Explainer URL (if available): https://github.com/whatwg/html/issues/8867
* Proposal author(s) (`@`-mention GitHub accounts): @mfreed7
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1886630
* Mozillians who can provide input (optional): @zcorpan @hsivonen

### Other information

From https://issues.chromium.org/issues/41492947

> This work falls under these two chromestatus entries:
>  https://chromestatus.com/feature/5081733588582400
>  https://chromestatus.com/feature/5102952270528512
> and these two blink-dev threads:
>  https://groups.google.com/a/chromium.org/g/blink-dev/c/PE4VwMjLVTo
>  https://groups.google.com/a/chromium.org/g/blink-dev/c/it0X7BOimKw

**Comment by smaug----** [comment]
This is being implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1890428
