### ISSUE TITLE
Constructors for RTC Encoded Frames with metadata

### ISSUE THREAD

**Issue by guidou** [mozilla/standards-positions#1009]
* Specification title: Part of [WebRTC encoded transform](https://w3c.github.io/webrtc-encoded-transform/)
* Specification or proposal URL (if available): https://github.com/w3c/webrtc-encoded-transform/pull/223
* Explainer URL (if available): https://github.com/guidou/webrtc-extensions/blob/main/constructor-explainer.md
* Proposal author(s) (`@`-mention GitHub accounts): @guidou @palak8669
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jan-ivar

**Comment by smaug----** [comment]
@jan-ivar does this need just a spec pr review?
