### ISSUE TITLE
CSS Nesting: @nest

### ISSUE THREAD

**Issue by andruud** [mozilla/standards-positions#1013]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: CSS Nesting
* Specification or proposal URL (if available): https://drafts.csswg.org/css-nesting-1/#nest-rule
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): @tabatkins
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @emilio
* WebKit position: https://github.com/WebKit/standards-positions/issues/337

### Other information

Basically [this proposal](https://github.com/w3c/csswg-drafts/issues/8738#issuecomment-2057868087) from Tab.

I am a bit reluctant to ship this since we have a major open issue about how it should appear in CSSOM (https://github.com/w3c/csswg-drafts/issues/10234), but apparently the CSSWG wants to ship `@nest` as currently specified _now_, then consider any additional changes later (https://github.com/w3c/csswg-drafts/issues/10234#issuecomment-2067746133, https://github.com/w3c/csswg-drafts/issues/10234#issuecomment-2069212736).

So I am specifically asking for a position on shipping the (possibly intermediate) state of `@nest` as it's currently specified, despite https://github.com/w3c/csswg-drafts/issues/10234 not being resolved.

**Comment by emilio** [comment]
I'm ok with the current `@nest` definition, I think it's the most straight-forward thing to do, and the best over-all.

One particularity that I mentioned on the call (or the issue?) that might have gotten overlooked is that I _think_ there's no reason it needs to be a `CSSGroupingRule` tho.

If you don't write it, it will never contain anything else than declarations, correct? It seems then that @nest could be "leaf" rules?

I think `CSSGroupingRule` probably makes sense, to make it similar to a `CSSStyleRule`, but only if we're sure that's the final design (which, IMO, it should be, but @LeaVerou and @mdubet at least disagreed). If we're open to changing stuff, making it a grouping rule introduces unnecessary risks / API surface.

Wdyt @tabatkins @andruud? All in all, I think I'm supportive of this, though I think we should not try to change this later, _specially_ if we ship it with the grouping behavior.

**Comment by tabatkins** [comment]
Yeah, it's currently a CSSGroupingRule just to be similar to CSSStyleRule, but I think it would be just fine to make it a leaf node and only contain a .style attribute.

**Comment by andruud** [comment]
I didn't realize it was specified as a `CSSGroupingRule`. IMO it should be:

```
<@nest> = @nest { <declaration-list> }
```

and

```
interface CSSNestRule : CSSRule { ... }
```

I don't see the point in giving it any more capabilities than that.

**Comment by LeaVerou** [comment]
@andruud @tabatkins can you please move the design discussion back into the CSS WG? Thanks.
