### ISSUE TITLE
AudioContext.onerror

### ISSUE THREAD

**Issue by gsinafirooz** [mozilla/standards-positions#1016]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: AudioContext.onerror
* Specification or proposal URL (if available): https://github.com/WebAudio/web-audio-api/pull/2580
* Explainer URL (if available): N/A
* Proposal author(s) (`@`-mention GitHub accounts): hoch@
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): padenot@mozilla.com

**Comment by martinthomson** [comment]
I'll give @padenot a chance to comment, but on the face of it, this seems too small to bother with here.

**Comment by marcoscaceres** [comment]
We closed it also on the WebKit side... best to just comment in the PR directly. I see @padenot already left some feedback.

**Comment by padenot** [comment]
Sorry I was off. I've been revieweing the PR, all good there, we'll implement.
