### ISSUE TITLE
Allow converting VideoFrame to RGB pixel formats by calling VideoFrame.copyTo()

### ISSUE THREAD

**Issue by Djuffin** [mozilla/standards-positions#1017]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: [WebCodecs](https://www.w3.org/TR/webcodecs/) (a tiny codec specific subfeature)
* Specification or proposal URL (if available): https://www.w3.org/TR/webcodecs/#dom-videoframe-copyto
* Explainer URL (if available): https://gist.github.com/Djuffin/9e2f98025ead49998524510cfeed8d33
* Proposal author(s) (`@`-mention GitHub accounts): @Djuffin
* Mozillians who can provide input (optional): @padenot 

### Other information
Spec change discussion: https://github.com/w3c/webcodecs/issues/92

**Comment by padenot** [comment]
Sorry I was off. `positive` on this one.
