### ISSUE TITLE
Still on SerialPort API

### ISSUE THREAD

**Issue by WebReflection** [mozilla/standards-positions#1018]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Reconsidering the SerialPort API position
* Specification or proposal URL (if available): https://developer.mozilla.org/en-US/docs/Web/API/SerialPort
* Explainer URL (if available): interacting with the plethora of IoT and educational devices out there https://pyscript.com/@agiammarchi/micro-repl/latest
* Proposal author(s) (`@`-mention GitHub accounts): 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://github.com/mozilla/standards-positions/issues/336
* Mozillians who can provide input (optional): 

### Other information

I am working on a project that needs to show kids to grown up users: *works in Chrome/ium* and as long standing Web supporter this is one of those cases it's not me being sloppy on cross-browser testing, it's rather other vendors making it impossible for the project I am working on to work on "*the Web Platform*".

I have read almost the entirety of this thread https://github.com/mozilla/standards-positions/issues/336 and had no chance to chime in but, for what I've understood, the security concern is not different from a basic `<input type="file">` any malicious Web page could present, any malicious Web page could influence the user about what to upload, so that any malicious Web page could also read both sensible data or configuration files from any user surfing that malicious Web page.

While asking users to download an `.exe` file or anything like that instead which, once granted Admin privileges would harm them even more, seems like "*the solution*" to that thread, I am dealing with thousand of kids willing to just use their browsers to interact with "*this or that SBC*" so that when kids, or even adults, are using projects that are basing their default OS to Firefox, are incapable of learning, having fun, or create amazing projects out of the Web, which used to be a technology to enable everyone, not a technology to patronize and overload their ideas, or possibilities, instead.

Accordingly, as much as I'd love to remove the "*need for Chrome/ium*" mandatory alert on whatever I am building, these are days nobody can even blame the Web developer behind anymore, as constraints are all over the major vendors responsibility.

This is true for all *MicroPython* boards as well as *Espruino* or others, the need for a particular Web extension to do something otherwise impossible out of extensions (which are just yet another extra user explict intent) makes literally no sense, when an extension just lands over an extra explicit user consent.

I am hoping that anyone reading this *might* have a second thought, but I am unfortunately sure this will get blocked and closed at speed light instead, keeping the idea that Firefox is not what people think it is anymore, just another gatekeeping in the Web industry / reality 😥

**Comment by bholley** [comment]
We've revised our position in #959. Basically, we'd take a patch if it meets our standards.

**Comment by WebReflection** [comment]
@bholley that's a better resolution than expected so thatnks for the update and thank you all for re-thinking that position. About "positions" though, I won't be able (due work/life/kid balance) to file that PR but I hope some *FF* enthusiast will find the time to do so 🤞

**Comment by bholley** [comment]
> @bholley that's a better resolution than expected so thatnks for the update and thank you all for re-thinking that position. About "positions" though, I won't be able (due work/life/kid balance) to file that PR but I hope some _FF_ enthusiast will find the time to do so 🤞

No worries, the position is already updated (that's the PR I linked to above).
