### ISSUE TITLE
The ChapterInformation interface

### ISSUE THREAD

**Issue by jiajiabingcheng** [mozilla/standards-positions#1019]
* Specification title: 
The ChapterInformation interface

* Specification or proposal URL (if available): 
spec:
https://www.w3.org/TR/mediasession/#the-chapterinformation-interface
proposal:
https://github.com/w3c/mediasession/issues/273

* Explainer URL (if available):
  https://github.com/w3c/mediasession/blob/main/explainer.md

* Proposal author(s) (`@`-mention GitHub accounts): 
@jiajiabingcheng

* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by padenot** [comment]
@alastor0325 Can you comment on this one?

**Comment by alastor0325** [comment]
LGTM, this can provide more detailed information for metadata. `positive`.

**Comment by zcorpan** [comment]
https://mozilla.github.io/standards-positions/#media-session exists already, treating this as an additional small feature (so no new entry needed).
