### ISSUE TITLE
improved styling of <details> and <summary> elements

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#1027]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: improved styling of `<details>` and `<summary>` elements
* Specification or proposal URL: Not a single spec, but a set of changes initially discussed in https://github.com/openui/open-ui/issues/744 and now moved to https://github.com/w3c/csswg-drafts/issues/9879 and https://github.com/whatwg/html/pull/10265 for the parts that belong in CSS and HTML respectively.
* Explainer URL (if available): https://github.com/dbaron/details-styling
* Proposal author(s) (`@`-mention GitHub accounts): @dbaron
* Caniuse.com URL (optional): none
* Bugzilla URL (optional): One piece of it is covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1856374 but other bugs are needed for other parts.
* Mozillians who can provide input (optional): @emilio
* WebKit standards-position: 

### Other information

I realize this is perhaps a little fuzzy, but I think most specifically it's useful to have a position on:
* the set of changes in https://github.com/whatwg/html/pull/10265
* the addition of the `::details-content` pseudo-element.

**Comment by martinthomson** [comment]
@emilio, I see that you [approved](https://github.com/whatwg/html/pull/10265#pullrequestreview-2133005217) the HTML pull request.  Does that mean that you think that this is OK?  (FWIW, the TAG looked at this as well and I think it's a useful change.)

So, positive?

**Comment by emilio** [comment]
Yes, positive sgtm
