### ISSUE TITLE
Local Peer-to-Peer API

### ISSUE THREAD

**Issue by MrBrain295** [mozilla/standards-positions#1029]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Local Peer-to-Peer API
* Specification or proposal URL (if available): https://wicg.github.io/local-peer-to-peer/
* Explainer URL (if available): https://github.com/WICG/local-peer-to-peer/blob/main/EXPLAINER.md
* Proposal author(s) (`@`-mention GitHub accounts): @ibelem @backkem @anssiko @wangw-1991
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/352

### Other information
[Local Peer-to-Peer](https://wicg.github.io/local-peer-to-peer/) is a Web platform API proposal for local communication between browsers without the aid of a server.

**Comment by backkem** [comment]
I'm one of the proposal authors. Thanks @MrBrain295 for filing this. Happy to answer any questions and gather feedback or concerns.

**Comment by MrBrain295** [comment]
There has now been a TAG design review https://github.com/w3ctag/meetings/blob/gh-pages/2024/telcons/06-10-minutes.md#breakout-e
