### ISSUE TITLE
Prioritized Task Scheduling: scheduler.yield()

### ISSUE THREAD

**Issue by shaseley** [mozilla/standards-positions#1039]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Prioritized Task Scheduling: scheduler.yield()
* Specification or proposal URL (if available): https://wicg.github.io/scheduling-apis/#dom-scheduler-yield
* Explainer URL (if available): https://github.com/WICG/scheduling-apis/blob/main/explainers/prioritized-task-scheduling.md#scheduleryield
* Proposal author(s) (`@`-mention GitHub accounts): @shaseley
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @smaug---- @sefeng211 
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/361

### Other information

This builds on `scheduler.postTask()`, which I know has been prototyped but not shipped in Gecko. We recently landed https://github.com/WICG/scheduling-apis/pull/92 to try to address concerns captured in https://github.com/WICG/scheduling-apis/issues/67. That same concern will apply to this API, which builds on the existing prioritization in the spec.

**Comment by sefeng211** [comment]
I think the task ordering can still be discussed, but generally we are positive for this.

**Comment by zcorpan** [comment]
https://mozilla.github.io/standards-positions/#scheduling-api entry exists, this is an addition. No new entry needed.

**Comment by sefeng211** [comment]
Implementation tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1920115
