### ISSUE TITLE
Partitioned :visited links history

### ISSUE THREAD

**Issue by kyraseevers** [mozilla/standards-positions#1040]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Partitioning :visited links history
* Specification or proposal URL (if available):  https://github.com/WICG/proposals/issues/100
* Explainer URL (if available): https://github.com/kyraseevers/Partitioning-visited-links-history
* Proposal author(s) (`@`-mention GitHub accounts):  @kyraseevers
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1398414
* Mozillians who can provide input (optional):
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/363

### Other information
We would want to add this change to the CSS spec and will be working with @tabatkins as a spec mentor.

**Comment by emilio** [comment]
Generally positive as a concept and from the CSS side, though skeptic about the loss of functionality being acceptable.

**Comment by martinthomson** [comment]
I agree with Emilio, this is generally worthwhile.

One piece of feedback here: please try to find a better venue for this work than WICG.  Privacy CG might be willing to take this on, as that is where a lot of related work has been incubated.
