### ISSUE TITLE
Backdrop filter mirror edgeMode

### ISSUE THREAD

**Issue by flackr** [mozilla/standards-positions#1051]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Filter Effects
* Specification or proposal URL (if available): https://drafts.fxtf.org/filter-effects-2/#backdrop-filter-operation
* Explainer URL (if available): https://github.com/w3c/fxtf-drafts/issues/374
* Proposal author(s) (`@`-mention GitHub accounts): @flackr
* Caniuse.com URL (optional): N/A (this is a change to the way backdrop-filter renders)
* Bugzilla URL (optional):
* Mozillians who can provide input (optional):
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/372

### Other information

This is specifically about the switch from the duplicate edgeMode to the mirror edgeMode for backdrop-filter sampling beyond the backdrop edges. The duplicate edgeMode leads to significant flickering in common scenarios and significantly overweights pixels at the edge into the blur, whereas mirroring back into the backdrop allows the smooth introduction of new content into the backdrop while still avoiding sampling outside of it (the motivation for using duplicate originally).

**Comment by jrmuizel** [comment]
Yes, I believe we want to do this.
