### ISSUE TITLE
DOM State-preserving move (`Node.prototype.moveBefore`)

### ISSUE THREAD

**Issue by noamr** [mozilla/standards-positions#1053]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: DOM state preserving move (a new addition to the DOM spec)
* Specification or proposal URL (if available): whatwg/dom#1255
* Explainer URL (if available): https://github.com/noamr/dom/blob/spm-explainer/moveBefore-explainer.md
* Proposal author(s) (`@`-mention GitHub accounts): @domfarolino @noamr 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/375

**Comment by smaug----** [comment]
I think we're positive on this. There are some technical issues to solve, but the concept is fine. The feature is something what web developers have asked for for decades, at least since https://bugzilla.mozilla.org/show_bug.cgi?id=254144 .
