### ISSUE TITLE
FedCM as a trust signal for the Storage Access API

### ISSUE THREAD

**Issue by cfredric** [mozilla/standards-positions#1065]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: FedCM as a trust signal for the Storage Access API
* Specification or proposal URL (if available): 
* Explainer URL (if available): https://github.com/explainers-by-googlers/storage-access-for-fedcm, https://github.com/privacycg/storage-access/pull/204
* Proposal author(s) (`@`-mention GitHub accounts): @johannhof, @cfredric, @yi-gu
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @bvandersloot-mozilla 
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/390

**Comment by bvandersloot-mozilla** [comment]
Given that this improves the ergonomics of storage access while enabling the FedCM API to potentially get out of the way of the third-party faster via my Lightweight FedCM proposal. I think it is fair to call this positive.
