### ISSUE TITLE
FYI Private State Token API Permissions Policy Default Allowlist Wildcard

### ISSUE THREAD

**Issue by arichiv** [mozilla/standards-positions#1066]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title:  Private State Token API Permissions Policy Default Allowlist Wildcard
* Specification or proposal URL (if available): https://github.com/WICG/trust-token-api/pull/306
* Explainer URL (if available): https://github.com/WICG/trust-token-api/blob/main/README.md
* Proposal author(s) (`@`-mention GitHub accounts): @arichiv, @aykutbulut, @dvorak42, @krgovind
* Issue URL (optional): https://chromestatus.com/feature/5205548434456576
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/391
* TAG Review: https://github.com/w3ctag/design-reviews/issues/990
* Past Evaluation: https://github.com/mozilla/standards-positions/issues/262

### Other information

Access to the Private State Token API is gated by Permissions Policy features. We proposed to update the default allowlist for both `private-state-token-issuance` and `private-state-token-redemption` features from self to * (wildcard).

**Comment by martinthomson** [comment]
There's not a lot new here, so we should retain our previous position on the overall feature.

(If anything, this makes things worse in the sense that the top-level site no longer needs to aid and abet the tracking that might be occurring, but it's a pretty minor thing.)
