### ISSUE TITLE
Transferable RTCDataChannel

### ISSUE THREAD

**Issue by jan-ivar** [mozilla/standards-positions#1077]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: WebRTC — § 6.2.6 Transfering data channel
* Specification or proposal URL (if available): https://w3c.github.io/webrtc-pc/#transfering-a-data-channel
* Explainer URL (if available): 
* Proposal author(s) (`@`-mention GitHub accounts): @youennf — https://github.com/w3c/webrtc-extensions/pull/78
* Caniuse.com URL (optional): https://caniuse.com/mdn-api_rtcdatachannel_transferable
* Bugzilla URL (optional): [bug 1749543](https://bugzilla.mozilla.org/show_bug.cgi?id=1592988).
* Mozillians who can provide input (optional): @jan-ivar
* WebKit standards-position: shipped in Safari 15

### Other information

Helps optimize data transmission; avoids blocking rendering when transmitting real time audio, video or game data. Partner interest.

**Comment by jan-ivar** [comment]
@martinthomson WDYT?

**Comment by jesup** [comment]
Original bug https://bugzilla.mozilla.org/show_bug.cgi?id=1209163 filed in 2015
As you'd expect, I'm in favor

**Comment by jesup** [comment]
Note that the Bugzilla URL in the initial comment goes to the wrong bug, and if it went to the bug # in the initial comment, that's "Make MediaStreamTrack transferable to DedicatedWorker", not DataChannels.   @jan-ivar can you update the initial comment?

**Comment by martinthomson** [comment]
Yep, this is worth doing.

**Comment by jan-ivar** [comment]
I've updated the OP. Thanks!
