### ISSUE TITLE
Badging API

### ISSUE THREAD

**Issue by mgiuca** [mozilla/standards-positions#108]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Badging API
* Specification or proposal URL: https://wicg.github.io/badging/
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): @marcoscaceres

### Other information

Discussed at TPAC 2018 in WebPlat: https://www.w3.org/2018/10/26-webplat-minutes.html#item07 (proposed by @mgiuca from Google).

**Comment by marcoscaceres** [comment]
This request is to help decide if we (Mozilla) want to support formally standardizing the Badging API as part of the W3C's WebApp WG in 2019. We can opt for further incubating this API at the WICG, though I personally think this is a pretty obvious thing that the Web is missing. 

My personal position: there is a long history of (ab)using favicons, page title (e.g., gmail), etc. to convey this information... having some means to integrate with platform and/or browser provided UI facilities would be a nice addition, specially for long-lived web apps (e.g., twitter, GitHub, etc.). The fact that it's write-only makes it nice from a privacy perspective. 

I'd encourage people to have a look, as the spec is very short and the API is very simple: literally `Badge.set(20)` and `Badge.clear()` ... could even just `Badge.set(null)` to clear :). 

I'm not huge fan on setting a `DOMString` (e.g., `Badge.set("⏸")`), for the badge, as it conflicts with things browsers already provide and could lead to confusion and things getting out of sync.

**Comment by annevk** [comment]
I think it makes sense to have this, though it should probably just be put on `navigator`.

**Comment by andreasbovens** [comment]
This seems like a good idea and something that's been missing from the web platform. I can see how it will work with favicons, top site icons, etc.
However, how will this work with web apps installed on the Android home screen? Only some Android OS variants (notably Samsung's) support badging on app icons. Stock Android only has notification dots (with nothing in them), so it seems unclear how this will be implemented — it would be very useful there, of course.

**Comment by marcoscaceres** [comment]
My understanding is that it’s platform agnostic/independent ... so current version of stock Android might show just the dot (but maybe the assistive technology in Android would say “5 actions” or something). And then, say, next version of Android may actually display numbers - so it “just works” tm. 

The API itself doesn’t care :)

**Comment by mgiuca** [comment]
@andreasbovens There are two pieces to the Android story.

1. For an OS like Android that only supports a notification dot (not a number): this is explicitly called out in the spec. The user agent can just ignore the data associated with the badge and set a coloured dot as a badge. Setting and clearing the badge still makes sense. This is how we plan to treat this API on Chrome OS (which currently doesn't support badging but we're implementing it as part of this API).
2. However, for Android itself: Android doesn't actually have an API for setting an app's badge. It automatically sets a badge when an app triggers a notification, and clears the badge when the user clears the notification. So even though this looks the same, it's actually not something we can support on Android. This was discussed at TPAC and called out as being "desktop only". Not really true --- this API can be implemented on iOS. It's just an Android-specific deficiency.

**Comment by dbaron** [comment]
Is `worth prototyping` an appropriate label given the discussion above?

**Comment by marcoscaceres** [comment]
Agree it is.
