### ISSUE TITLE
Writable Files

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#110]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Writable Files
* Specification or proposal URL: https://github.com/WICG/writable-files
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

The Writable Files specification seems to be getting some attention lately, so it seems like it may be useful to have a position on it.  See [the repository](https://github.com/WICG/writable-files), the [WICG Discourse discussion](https://discourse.wicg.io/t/writable-file-api/1433), and the [Google Developers blog post](https://developers.google.com/web/updates/2018/11/writable-files).

Also see the relationship to the old [File System API proposal](https://www.w3.org/TR/file-system-api/) ([caniuse](https://caniuse.com/#feat=filesystem)).

**Comment by martinthomson** [comment]
Given the drafty nature of this, I think that the only sensible response is "defer".  Once things mature a little, we can reconsider that position.  It seems like some of the thinking here is headed in the right direction, some not.  The details matter, but they are still very much in flux.

**Comment by martinthomson** [comment]
I think that it would be appropriate to reopen, or open a new issue, when someone believes that there is sufficient new information such that reassessment is warranted.
