### ISSUE TITLE
Dialog BeforeToggle/Toggle events

### ISSUE THREAD

**Issue by keithamus** [mozilla/standards-positions#1101]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: dispatch toggleevents for dialog open/close
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/10091
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): @keithamus 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1876762
* Mozillians who can provide input (optional): @smaug---- 
* WebKit standards-position: https://github.com/WebKit/standards-positions/issues/418

### Other information

This is kind of retroactively ensuring we catalogue the standards position for this for the due diligence on spec, but it's already shipping in Firefox nightly.

**Comment by smaug----** [comment]
This was discussed already at 2023 TPAC. Seems a fine small addition.
