### ISSUE TITLE
Vertical alignment of details

### ISSUE THREAD

**Issue by martinthomson** [mozilla/standards-positions#1121]
![image](https://github.com/user-attachments/assets/cc8b9744-51a3-4cce-88ab-a50aa022f371)

"Raw sockets" is presently the only item with concerns AND details.  It renders somewhat poorly.  `vertical-align: top` seems like a reasonable tweak for that.

**Comment by zcorpan** [comment]
It would need to be `bottom` instead (the current value is `top`), which looks reasonable I think.

<img width="1164" alt="Screenshot with bottom alignment" src="https://github.com/user-attachments/assets/d2897c93-8e6e-407c-b6fd-07ec907dd78d">

**Comment by martinthomson** [comment]
Ah, moving the title down makes sense.
