### ISSUE TITLE
Intrinsicsize attribute for HTML image and video elements

### ISSUE THREAD

**Issue by loonybear** [mozilla/standards-positions#129]
* Specification Title: Supporting `intrinsicsize` attribute to HTMLImageElement and HTMLVideoElement
* Demo: https://googlechrome.github.io/samples/intrinsic-size/
* Specification or proposal URL: https://github.com/ojanvafai/intrinsicsize-attribute/
* Mozillians who can provide input (optional): @overholt 

### Other information
We would like to introduce this attribute to allow maintaining an image's aspect ratio while one dimension is specified proportionally. Please see the link above for more details.

**Comment by emilio** [comment]
I recall somebody talking at TPAC to the CSSWG about adding aspect-ratio-based units, but I don't recall the specifics, maybe @dbaron or @jensimmons do? How would this play with that other proposal?

Also, how does this play and interact with the `sizes` attribute which can already change the intrinsic size of the image? Is there any way to make it work with `srcset` / `<source>` and related responsive images stuff?

**Comment by emilio** [comment]
Ah, I see my question was answered already in the document:

> How does this work with responsive images? The 'intrinsicsize' attribute sets the image's intrinsic aspect ratio. For an image element with a srcset, if: 
> * a source is chosen using the 'w' descriptor, then the result of evaluating the 'sizes' attribute sets the image's intrinsic width, and its intrinsic height will be calculated by the intrinsic aspect ratio defined by 'intrinsicsize' attribute;
> * otherwise, the 'intrinsicsize' attribute sets the intrinsic width and the intrinsic height.

**Comment by emilio** [comment]
So looks like `intrinsicsize` overrides the image intrinsic size even though we know the actual source intrinsic size, is that right? Seems a bit footgunny... That means that until all browsers support the attribute it's trivial to cause behavior differences accidentally. For example let's say that I have a `cat.jpeg` feature that is 200x200, but I do `<img intrinsicsize="100x100" src="cat.jpeg">`.

That means that if the browser supports intrinsicsize the image would lay out as 100px wide all the time right? While once it loads a browser that doesn't support the attribute will lay it out as 200px and the layout would be broken. That sounds slightly unfortunate if the use-case this wants to solve is just avoiding the reflow when the image is loaded...

**Comment by annevk** [comment]
This also conflicts a bit with the HTML standard which says width/height attributes are supposed to match the intrinsic dimensions (use CSS for presentation aspects). Now currently width/height attributes map directly to CSS without forwarding some kind of aspect ratio. Perhaps that's the thing that should be added.

You'd still have a rendering difference between supporting and not-supporting browsers, however.

**Comment by loonybear** [comment]
Yes, aspect-ratio would still be a future project. But I don't see why this will stop intrinsicSize.

1. intrinsicSize is only supported on media elements (image / video). asepect-ratio on the other hand is way more complicated than this.
2. intrinsicSize overrides the intrinsic size of element, it will be in pixel unit, aspect-ratio provides just a ratio. However, intrinsic size should only be used if height/width is unspecified (including the case that aspect-ratio is missing), so there is no real conflicts.

To answer the other question, if you do <img intrinsicsize="100x100" src="cat.jpeg">, it will be always rendered as 100px by 100px, this prevents layout instability, it prevents contents from jumping around, which was one of the intention that intrinsicSize is being proposed.

**Comment by emilio** [comment]
So one difference between how intrinsicsize works (as implemented in Chromium today) and how `width=` and `height=` works is that intrinsicsize works in image pixels, while width and height work in CSS pixels. This seems reasonable to me, but does not match what the explainer claims not my initial expectations. The explainer claims:

> The sizes are in CSS Pixels.

But if I go to https://googlechrome.github.io/samples/intrinsic-size/ on Chromium on a HiDPI display, , the samples with `intrinsicsize="250x200"` are really `125x100` CSS pixels. Of course if I set `width="250" height="200"` instead the image is twice as big.

Is that a bug in Chrome's implementation? Or an error in the explainer? Seems pretty counter-intuitive to me.

**Comment by simevidas** [comment]
In @loonybear’s latest comment, the broken image appears to be `<img src="cat.jpeg" style="max-width:100%;">` (in case anyone’s wondering).

**Comment by loonybear** [comment]
Sorry about the broken image, I updated the comment above.

Sorry I will correct the explainer, thanks for pointing that out @emilio. 

In addition, we are in the process of moving the github repo to WICG, so maybe we could move some discussion there too. https://discourse.wicg.io/t/moving-intrinsicsize-attribute-to-wicg/3356

**Comment by dbaron** [comment]
I think I'm largely supportive of this.  A few thoughts:
* Structuring this in a way that content management systems (CMSes) can add this automatically to images whose size they know, with a strong guarantee that they don't break things, is a big plus.  It means that people can fix this at a system level in a number of cases and improve the performance of page loading.
* I think the values given should be in image pixels, which CSS generally treats as the default size to render in CSS pixels.  It should behave the way an image with that underlying intrinsic size behaves.
* The document largely discusses the important use case of improving page performance by specifying the "correct" intrinsic size of the image.  But I think it's at least worth thinking about whether there are use cases for using "incorrect" intrinsic sizes (i.e., overriding the image intrinsic size to be something other than what it is in the image), particularly in combination with [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit).
* the current document is appropriate for a discussion about prototyping, but it's not yet precise enough to lead to interoperable implementations.  So I think a more formal specification should exist before any browsers ship this.

For those reasons, I'd be inclined to mark this as `worth prototyping`.

However, there was some discussion of this at the [CSS Working Group meeting last week](https://wiki.csswg.org/planning/sf-2019), I think on two separate days.  I think @jensimmons and @fantasai disagree with my position a bit on this a bit, so I'd like to give them a chance to chime in.

**Comment by fantasai** [comment]
I think adding the ability to override the intrinsic size of an image with a separate pair of attributes is a little too much power for solving the problem at hand. It also adds extra overhead to authors who then have to learn new attributes and the interaction between them and the old ones and CSS.

Imho it makes more sense to map the ratio between the existing width/height attributes, which as @annevk notes are already defined as a way for authors to provide intrinsic sizes, into an intrinsic aspect ratio to solve the preloading problem. This a) doesn't add any new markup to HTML, b) leverages authors' existing knowledge and practices, and c) improves performance on a large corpus of existing pages without the author needing to make any changes. Many CMSes already add these attributes to image markup by default.

There's a cost to adding new features to the platform, and it's not just the cost of implementing it in browsers: it's the cost of increasing the amount of knowledge an author must acquire to be effective. That's a heavy cost to pay, and when we add fundamentally new and useful features to the platform it's very clearly worth it, so much that we don't really think about that cost too hard. But we're not doing that here, we have an existing mechanism that is perfectly adequate; and I therefore don't think that cost is worth paying for intrinsicsize.

**Comment by yoavweiss** [comment]
> Imho it makes more sense to map the ratio between the existing width/height attributes, which as @annevk notes are already defined as a way for authors to provide intrinsic sizes, into an intrinsic aspect ratio to solve the preloading problem.

Wouldn't that break backwards compatibility? How would the browser tell apart legacy `width`/`height` values, which should be taken literally and new ones which should be considered as a ratio?

**Comment by fantasai** [comment]
@yoavweiss You'd continue to map width/height attributes into the width/height properties as before. The aspect ratio mapping would be an *additional* mapping, not a replacement for width/height. If there are concerns about existing content using width/height values that map to an aspect ratio which is not the actual aspect ratio of the image *and* those width/height attribute values are being overridden by CSS 'auto' values higher in the cascade, then we can take the explicit aspect ratio mapping as a lower priority than the image's actual aspect ratio.

**Comment by jensimmons** [comment]
Mozilla has solved much of the use case for `intrinsicsize` with a different solution, https://bugzilla.mozilla.org/show_bug.cgi?id=1547231;
proposed and discussed here: https://github.com/WICG/intrinsicsize-attribute/issues/16#issuecomment-515035191 

And the original proposal is no longer being pursued:
https://twitter.com/tomayac/status/1165902659083280384
WICG/intrinsicsize-attribute#18
WICG/intrinsicsize-attribute#16 (comment)

**Comment by annevk** [comment]
Thanks for the update @jensimmons, I'll close this then. (Please do comment if this needs to be reconsidered somehow.)
