### ISSUE TITLE
imagesrcset and imagesizes attributes on <link>

### ISSUE THREAD

**Issue by irori** [mozilla/standards-positions#130]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: imagesrcset and imagesizes attributes on `<link>`
* Specification or proposal URL: [Explainer](https://docs.google.com/document/d/1wob4u9AER1kmUodqIEp78BuziSJChBl54A5ZRXPRCUI/edit?usp=sharing), [whatwg/html](https://github.com/whatwg/html/pull/4048), [w3c/preload](https://github.com/w3c/preload/pull/134)
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1515760

### Other information
This adds `imagesrcset` and `imagesizes` attributes to `<link rel=preload as=image>`, that correspond to the `srcset` and `sizes` attributes of HTMLImageElement, so that responsive images can still appreciate the power of preloading.

- [blink-dev Intent to Ship thread](https://groups.google.com/a/chromium.org/d/msg/blink-dev/07CbItWfA4M/CG1qF8IoEAAJ)

**Comment by ddragana** [comment]
<link rel=preload ... > is not implemented yet. We may need to implement it in the near future (this year), but I am not sure at the moment.

**Comment by annevk** [comment]
I think we're implementing `rel=reload` so this is probably fine. (I'm a bit surprised the HTML PR got merged as there was only stated interest from Google.)

**Comment by domenic** [comment]
There is a hidden comment at https://github.com/whatwg/html/pull/4048#issuecomment-455806466 citing https://bugzilla.mozilla.org/show_bug.cgi?id=1515760#c4 as implementer interest from Mozilla. I think that was not a correct reading of @ddragana's Bugzilla comment, and apologize for not checking it more closely before merging. /cc @domfarolino to avoid future mistakes. I suspect the new HTML pull request template will make also help avoid such problems in the future.
