### ISSUE TITLE
PFP: Cache Digest

### ISSUE THREAD

**Issue by Jxck** [mozilla/standards-positions#131]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Cache Digest for HTTP/2
* Specification or proposal URL: https://tools.ietf.org/html/draft-ietf-httpbis-cache-digest
 
### Other information

in httpwg at IETF, chair mnot asking implementation signal for cache digest now.

https://lists.w3.org/Archives/Public/ietf-http-wg/2019JanMar/0033.html

if mozilla says interested in or not, thats big material to consider this spec is dead or alive.

personally, I'm looking forward to use Cache Digest for Optimize http2 push.
if cache digest will dead, that means cache aware server push for browser dead too.
so I wanna hear good voice from firefox.

**Comment by annevk** [comment]
I strongly suspect mnot already talked to someone at Mozilla given that email...

cc @ddragana @martinthomson

**Comment by martinthomson** [comment]
This is an experimental RFC, which is sometimes not an indication that it's out there.  This one is truly out there.  More effort is being spent on 103 I think.  Which reminds me...

It's not actively harmful, so `non-harmful` is probably a reasonable position, but given the complexity of implementation, it's probably not something we'll end up doing.  The recent addition of cuckoo filters means that it is less difficult to do without complete walks of the cache, but it still is far from trivial.

**Comment by dbaron** [comment]
I'd note that #133 has a few comments that are discussing the substance of the position and thus probably should have been here instead.
