### ISSUE TITLE
HTTP 103 Status

### ISSUE THREAD

**Issue by martinthomson** [mozilla/standards-positions#134]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: An HTTP Status Code for Indicating Hints
* Specification or proposal URL: https://tools.ietf.org/html/rfc8297
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @ddragana

### Other information

This 1xx status code provides servers (and CDNs) the ability to provide hints about a resource before delivering a final response.  The primary purpose of this is to send link relations, like prefetch and preload, much more quickly so that the browser can start to request those resources.  This is seen as a less ambitious alternative to server push.  It requires fewer bytes to send just a URL rather than a synthesized GET, and it avoids cases where pushes are sent for resources that are already cached.

**Comment by ddragana** [comment]
I would say it is `worth prototyping`,  but the main purpose of the 103 status code is to be used with link rel=preload which is not implemented.

**Comment by annevk** [comment]
I raised these issues at some point:
* https://github.com/httpwg/http-extensions/issues/687 Slight concern that server operators need to be in the loop if folks start serving 103s as they can be used to bypass CSP policies of final responses. (Having Origin Policy would mitigate this somewhat.)
* https://github.com/httpwg/http-extensions/issues/736 There's no integration with Fetch defined yet. This means a number of things are somewhat unclear. E.g., can you specify a CSP policy on an early response? HSTS, etc.

**Comment by adamroach** [comment]
@annevk -- The concerns you cite seem relatively mild. Is it your intention to advocate for a less forward-leaning position than `worth prototyping`? Or should we go with that position while noting your two concerns in the details?

**Comment by annevk** [comment]
I think the second issue in particular is worth noting as it means a number of design decisions still have to be taken. I don't think it precludes `worth prototyping` though.

**Comment by adamroach** [comment]
Okay, so I propose `worth prototyping` with:

> We believe that experimentation with the 103 response code is worthwhile, while at the same time noting that its primary benefit comes from using it with `rel=preload`, which Firefox does not yet implement. We do have some concerns about the lack of clear interaction with Fetch, which we hope will be specified before the mechanism is put into widespread use.
