### ISSUE TITLE
Ability to link to a single Position

### ISSUE THREAD

**Issue by jyasskin** [mozilla/standards-positions#136]
It'd be nice to be able to link to one position on https://mozilla.github.io/standards-positions/. Right now, clicking an entry opens a more detailed description for that entry, but it doesn't add a fragment to the URL that would let me link to just that entry.

Compare https://www.chromestatus.com/features/5685444318593024 and https://www.chromestatus.com/feature/5685444318593024.

**Comment by dbaron** [comment]
This was fixed in #246 (for #245, which was really a duplicate of this but I missed it).
