### ISSUE TITLE
Encrypted SNI

### ISSUE THREAD

**Issue by chris-wood** [mozilla/standards-positions#139]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Encrypted SNI For TLS 1.3
* Specification or proposal URL: https://datatracker.ietf.org/doc/draft-ietf-tls-esni/ & https://tools.ietf.org/html/draft-ietf-tls-esni
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1494901
* Mozillians who can provide input (optional):

**Comment by dbaron** [comment]
cc @ekr

**Comment by martinthomson** [comment]
Well, we were behind pushing this, so I'm going to say `important`.
