### ISSUE TITLE
Mozilla or Firefox?

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#14]
The title says these are Mozilla positions, but the `<h1>` says Firefox. Should we instead use the Mozilla logo and change `<img alt>` accordingly?

**Comment by ekr** [comment]
I concur with Anne that we should say "Mozilla". However, in cases where the distinction is relevant, we might need to just use freeform comments. I'm inclined to think that we should lean in the direction of Firefox on those. So, say for instance that there was some browser feature which Firefox was skeptical of but Servo decided to experiment with. I think we could mark this as "defer" and then have comments like ("experiments going in in other browser, including Servo may inform this position in future"). Would that work for people?

**Comment by annevk** [comment]
I think that's fine.

**Comment by dbaron** [comment]
Image changed in #120.
