### ISSUE TITLE
Fetch/HTTP: Stale While Revalidate

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#144]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTTP Cache-Control Extensions for Stale Content
* Specification or proposal URL: https://tools.ietf.org/html/rfc5861
* Mozillians who can provide input (optional): @mayhemer

### Other information

Chrome seems have implemented this and is close to shipping. Fetch integration is happening at https://github.com/whatwg/fetch/pull/853 primarily to ensure that the fetch from the HTTP cache obeys general Fetch policies. Might be worth looking at too (though primarily the end state, not the whole comment thread).

**Comment by martinthomson** [comment]
My understand is that this is a decent performance improvement, but I'd like to understand what @mayhemer thinks.

**Comment by ddragana** [comment]
(I will only talk about Stale While Revalidate Handling, rfc 5861 adds multiple headers)

This will save 1-rtt if the resource is only revalidated. If revalidation cause a new version to be fetched, it will save multiple rtt-s, because the old version will be display while new version is being fetched. This header will make possible changing content of a page without the time penalty.

**Comment by mayhemer** [comment]
There are two parts: 
1. HTTP c-c: s-w-r response handling (https://bugzilla.mozilla.org/show_bug.cgi?id=1536511)
2. allowing fetch() to optionally use this feature (https://bugzilla.mozilla.org/show_bug.cgi?id=1534698)

I will, as Dragana did, comment only on the HTTP cache part (rfc 5861).  I filed a bug to support this as it's relatively easy to implement and can well save round trips as P1 bug for this cycle (subject to change, tho)

It's not clear from https://github.com/whatwg/fetch/pull/853 how will fetch() work with this feature, hard to find an overview status in that long discussion.

**Comment by annevk** [comment]
@mayhemer it doesn't affect `fetch()`. I think an earlier iteration did that, but that got dropped. The integration with Fetch is mainly about ensuring these fetches from the HTTP cache obey the same rules as other fetches (e.g., those from `<img>`).

**Comment by mayhemer** [comment]
> 
> 
> @mayhemer it doesn't affect `fetch()`. I think an earlier iteration did that, but that got dropped. The integration with Fetch is mainly about ensuring these fetches from the HTTP cache obey the same rules as other fetches (e.g., those from `<img>`).

I'm really not sure what you mean - is that that a fetch("//.../stall_while_reval") will behave the same way as <img src="//.../stall_while_reval" />?  If so, then it's simple: it will.  They will both go through the same HTTP cache checking logic.

Did that answer you objection?

**Comment by annevk** [comment]
I'm confused. What objection?

I was trying to clarify that nothing is added to the `fetch()` API in particular. The reason there's integration with fetch is about the other things fetch defines and ensuring the fetch from the HTTP cache uses those rules.

**Comment by mayhemer** [comment]
> 
> 
> I'm confused. What objection?

ah.. none, just ignore me today.

> 
> I was trying to clarify that nothing is added to the `fetch()` API in particular. The reason there's integration with fetch is about the other things fetch defines and ensuring the fetch from the HTTP cache uses those rules.

now it's clear.  so, the answer is the same: fetch will use these rules, yes.

thanks!

**Comment by annevk** [comment]
I forgot to close the loop here. This is effectively `worth prototyping`, but not worth its own entry I suspect.

**Comment by adamroach** [comment]
Yep, I read this a `worth prototyping` also. Proposed detail:

> The `stale-while-revalidate` cache control extension appears to provide improved user experience with no obvious drawbacks. We take no position on the other mechanisms in RFC 5861 at this time.

I'll also add https://bugzilla.mozilla.org/show_bug.cgi?id=1536511 to the entry.

Any objections?

**Comment by annevk** [comment]
Thanks, sounds good to me.
