### ISSUE TITLE
KV Storage

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#145]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: KV Storage
* Specification or proposal URL: https://wicg.github.io/kv-storage/
* Mozillians who can provide input (optional): @asutherland @janvarga

### Other information

This is the first feature to build on top of new JavaScript built-in module infrastructure and is therefore somewhat controversial.

**Comment by domenic** [comment]
One thing to note is https://github.com/WICG/kv-storage/issues/46, which I hope to work on over the next month or so in collaboration with Igalia.

**Comment by annevk** [comment]
Mozilla storage engineers have helped shape this API and are happy with the outcome. Folks from the ECMAScript/Wasm side of the organization are also happy with this, thus let's mark this `worth prototyping`.

**Comment by dbaron** [comment]
also cc: @bholley

**Comment by annevk** [comment]
Closing as this proposal has been abandoned.
