### ISSUE TITLE
Form Participation API

### ISSUE THREAD

**Issue by tkent-google** [mozilla/standards-positions#150]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Form Participation API
* Specification or proposal URL: https://docs.google.com/document/d/1JO8puctCSpW-ZYGU8lF-h4FWRIDQNDVexzHoOQ2iQmY/edit?usp=sharing
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
https://bugzilla.mozilla.org/show_bug.cgi?id=1518442 for Event-based one
https://bugzilla.mozilla.org/show_bug.cgi?id=1552327 for "Form-associated custom elements"
* Mozillians who can provide input (optional): 

### Other information
The proposal was discussed on https://github.com/w3c/webcomponents/issues/187 by multiple vendors.
Event-based participation was already merged to the WHATWG HTML specification.

**Comment by annevk** [comment]
cc @johndai1984 @smaug----

**Comment by domenic** [comment]
The spec PR is at https://github.com/whatwg/html/pull/4383 which has links to some rendered spec text. Some highlights include:

- https://whatpr.org/html/4383/custom-elements.html#custom-elements-face-example for an example
- https://whatpr.org/html/4383/custom-elements.html#custom-element-reactions for brief explanations of the new callbacks
- https://whatpr.org/html/4383/custom-elements.html#the-elementinternals-interface has the new ElementInternals methods that allow communicating state to the browser

**Comment by annevk** [comment]
We've evaluated the various extensions to the `form` element in the DOM team (and I've also reviewed the new specification text) and decided to prototype and likely ship these (I've updated OP with a pointer for the form-associated custom elements bug). So this is `worth prototyping`. As these are in effect minor additions to the XMLHttpRequest (that's where `FormData` is defined) and HTML Standard it's probably not worth adding a line to the dashboard. Closing therefore, but happy to consider alternatives.

**Comment by mercmobily** [comment]
Sorry for the noise but... This [this spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example] being considered for FF?

**Comment by annevk** [comment]
Yes, see Bugzilla links in OP.

**Comment by mercmobily** [comment]
@annevk Sorry I was confused by the closing and reopening of the ticket, and by that "Closing therefore, but happy to consider alternatives."

**Comment by devinbirtciel-mck** [comment]
Does this issue being closed mean that form-associated custom elements are implemented? My team have been unable to get the API to work on anything but Chromium based browsers. I tried commenting on the bugzilla report a couple of weeks ago, but there doesn't seem to be much activity on it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1552327

**Comment by dbaron** [comment]
> Does this issue being closed mean that form-associated custom elements are implemented?

No.  It means we've taken a position on what we think about the proposed specification; see [this repository's README](https://github.com/mozilla/standards-positions).

**Comment by smaug----** [comment]
And form-associated custom elements are being implemented. In that linked bug (which is a kind of meta bug) you can see activity on the bugs it depends on.
