### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/standards-positions#151]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Lazyloading of images/iframes below the fold
* Specification or proposal URL: https://github.com/whatwg/html/pull/3752
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by smaug----** [comment]
Personally I do like the proposal, but it is still nowhere near ready. Especially it is unclear to me how 'auto' is handled and when 'auto' lazyloaded resources may or may not block top level page's load event to fire. (unless I'm missing something...)

**Comment by dbaron** [comment]
It seems reasonable to me as well assuming it's specified sufficiently.  Does `worth prototyping` seem like a reasonable summary?

**Comment by smaug----** [comment]
The affect to load event firing is very critical piece. Without that being defined, it isn't clear to me how the lazyload is supposed to work.

**Comment by smaug----** [comment]
Given that 'auto' is the default behavior in the latest PR, and 'auto' behavior is left to UA to decide, I consider that part rather harmful. I'd feel more comfortable if 'auto' was dropped altogether for now and the whole feature was always an opt-in.

**Comment by marcoscaceres** [comment]
That’s indeed an odd/harmful choice. Has that been raised as an issue? If whomever is proposing it not willing to change?

**Comment by digitarald** [comment]
Shipping in Chrome 67: https://web.dev/native-lazy-loading

Related, this is the caniuse URL: https://caniuse.com/#feat=loading-lazy-attr

**Comment by smaug----** [comment]
They will be shipping only parts of the lazyload proposal. Or that is what has been said on blink-dev at least. The default state for lazyload won't ship yet.

But note, there is no proper spec yet. There is a pr only.

**Comment by domenic** [comment]
The spec is as proper as it will get. Without a second implementer interested, per the WHATWG working mode, it will not be merged in to the HTML Living Standard. But the spec still exists, and is available for others to implement (or express interest in) at their leisure.

**Comment by smaug----** [comment]
The PR has unaddressed review comments.

**Comment by annevk** [comment]
Given the recent changes by @domfarolino and reduced scope (`img` only, no `auto`) I think this is `worth prototyping`.

**Comment by smaug----** [comment]
I agree, the recent spec pr is starting to have quite clearly defined behavior.
