### ISSUE TITLE
Private Click Measurement

### ISSUE THREAD

**Issue by ehsan** [mozilla/standards-positions#161]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Privacy Preserving Ad Click Attribution
* Specification or proposal URL: https://wicg.github.io/ad-click-attribution/index.html
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @ehsan, @englehardt, @tanvihacks, @bakulf

### Other information
We're interested in this specification in order to support a way for a click source to measure conversions as a result of the user clicking on an ad without sharing user-identifying information with the click source in the third-party context.

**Comment by marcoscaceres** [comment]
This serves as a fairly good explainer:
https://webkit.org/blog/8943/privacy-preserving-ad-click-attribution-for-the-web/

**Comment by dbaron** [comment]
Do you think this is `worth prototyping`, `important`, or something else?

**Comment by marcoscaceres** [comment]
This seems "worth prototyping", specially if Apple is doing it in parallel. The privacy preserving aspects make it pretty aligned with Mozilla's mission, but it will be highly disruptive to adtech so it might be worth seeing what the large-scale impacts will be on the web and sites ability to monetize through ads.

**Comment by hober** [comment]
A couple of notes:

1. We've renamed it Private Click Measurement (due to acronym collision: PP-ACA is the Affordable Care Act)
2. We'd like to move it from @WICG to the @privacycg, but need multi-implementer interest to do so. If Mozilla is interested, please say so in privacycg/proposals#1

**Comment by hober** [comment]
On the fraud question, one possible route would be to use something like Privacy Pass #261 / the Trust Token API #262 to prevent / mitigate fraud.

**Comment by annevk** [comment]
It's not entirely clear to me we should endorse this quite yet as it fundamentally depends on some kind of fraud prevention protocol that isn't specified. And the ultimate nature of that fraud prevention technique has itself privacy and security properties that we need to consider.

I believe from the latest Privacy CG meeting that steps are being taken to get more concrete on that and I would suggest we wait on that.

**Comment by dbaron** [comment]
Does that seem likely to happen relatively soon (i.e., we should just wait for it), or do you think it might take a while and we should mark this as `defer` in the meantime?

**Comment by ekr** [comment]
I tend to think defer

**Comment by TanviHacks** [comment]
We are trying to get some more specification on the proposed fraud preventions, and hence need some more time to sort this out.
