### ISSUE TITLE
WebAuthn

### ISSUE THREAD

**Issue by mhalano** [mozilla/standards-positions#163]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Web Authentication: An API for accessing Public Key Credentials
* Specification or proposal URL: https://www.w3.org/TR/webauthn/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
This is the famous WebAuthn standard. Mozilla already have a working prototype on Firefox. This issue is just to formally register the support for standard.

**Comment by dbaron** [comment]
Probably `important`.  cc @jcjones.
