### ISSUE TITLE
HTML toast element 🍞

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#169]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: std-toast
* Specification or proposal URL:  https://github.com/jackbsteinberg/std-toast
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
Discourse discussion https://discourse.wicg.io/t/proposal-toast-ui-element/3634

**Comment by marcoscaceres** [comment]
This is what I said over on the WICG Discourse

> Personally, I appreciate the proposal, but don’t find it particularly compelling: it doesn’t seem to provide any system level integration (already achieved with notifications API) nor does the “saves bytes” argument strike me as particularly compelling, as the body of the toast is where the weight is. It seems to replicate CSS functionality, via the duration member, and so on. The accessibility aspect of this is compelling, but feels to me that’s best delegated to something like AOM?

> I’ll see what other Mozilla folks think (will file a formal standards position), and I’m open to being convinced otherwise, but my initial reaction would be for Firefox to not support this - and that going down this route of might actually be harmful: it’s standardizing things at the wrong level.

**Comment by dbaron** [comment]
It's not clear to me if it's still useful to state a position here or we should just close this.  I'm inclined to think we should just close.

I'd note that in addition to the relatively substantial number of library-related questions around this proposal, there was also a set of accessibility-related ones.  In particular, toasts are a relatively inaccessible model.  While the standardized component might be the most accessible toast that can be built, there's a tradeoff around providing that.  People who would use toasts anyway might get something more accessible, but people who would have used something else (likely something more accessible) might be encouraged to use toasts instead.
