### ISSUE TITLE
Restricting Notifications API to secure contexts

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#17]
Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Notifications API
* Specification or proposal URL: https://github.com/whatwg/notifications/issues/93

**Comment by dbaron** [comment]
I don't see any reason not to be supportive of this change, given that it sounds like Chromium is going to make (or has made?) the change first.  (If the weren't, we'd be at risk of web-compatibility problems until they did.)

That said, I wonder if it's worth a separate entry in [the positions table](https://mozilla.github.io/standards-positions/) given the positions we've already stated on secure contexts?

**Comment by johannhof** [comment]
FWIW, a few weeks ago I added telemetry on request origin schemes for all permissions: https://mzl.la/2BHl0qF

It's still only on Nightly, but there 7.16% of requests came from HTTP (at the time of writing).

**Comment by martinthomson** [comment]
Yes, we should do that, but I think that @dbaron is right in saying that we should just do it and not record a position.  This is at the level of discussion that belongs on a bug more than here, but I appreciate that it was raised, because it might not have been.

**Comment by dbaron** [comment]
OK, given that martin agrees, I'm going to close this as "wontfix", essentially because we've already stated a position on the overall topic that we believe to be sufficient.

@annevk feel free to reopen if you disagree with this approach.
