### ISSUE TITLE
WICG Media APIs

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#182]
The following media-related APIs are in the final stages of being migrated to the newly rechartered [W3C Media Working Group](https://www.w3.org/media-wg/) - the proposals have been incubating for a few years, and  Media WG (co-chaired by Apple and Google), intend to formally standardize... I'm assuming that Apple's involvement means there is a moderate chance some of these APIs will be implemented in WebKit (maybe some have already?). They are all shipping in Chrome I believe. Apart from our loosely formed opinion on Picture-in-Picture (#72), I'm unsure about our plans for others:  

- [Media Capabilities](https://github.com/wicg/media-capabilities) - [intent to migrate](https://github.com/WICG/media-capabilities/issues/117). 

- [Picture-in-Picture](https://wicg.github.io/picture-in-picture/) - [intent to migrate](https://github.com/WICG/picture-in-picture/issues/150). See also: https://github.com/mozilla/standards-positions/issues/72.

- [Media Session](https://wicg.github.io/mediasession/) - [intent to migrate](https://github.com/WICG/mediasession/issues/220) See also: https://github.com/mozilla/standards-positions/issues/28.

- [Media Playback Quality](https://wicg.github.io/media-playback-quality/) - [intent to migrate](https://github.com/WICG/media-playback-quality/issues/11).

- [Autoplay Policy Detection](https://github.com/wicg/autoplay/) - [intent to migrate](https://github.com/WICG/autoplay/issues/9) 

CC @padenot and @jyavenard, as members of the working group, and @mikeconley re: PiP.

If there are any concerns about them migrating or we believe some need further incubation, it would be a good time to speak up. Similarly, it would be good to express some [position](https://github.com/mozilla/standards-positions/#possible-specification-positions) for these specs. 

The WICG Chairs will be reviewing the intents to migrate, linked to above, over this week with the aim of migrating them by next week.

**Comment by padenot** [comment]
**Picture in Picture**: we're following the spec but don't plan to currently implement the API.
**Media Capabilities**: we implement and ship the spec, and we're currently implementing and intend to ship additions to the spec.
**Media Session**: we don't implement, but we are considering implementing and shipping in in the short to medium term. In particular, we're currently doing experiments to support this effort at the platform level.
**Media Playback Quality**: we implement and ship this spec, and intend to continue doing so, were it to change.
**Autoplay Policy Detection**: we are actively participating to the spec discussion, and plan to implement and ship the outcome of this discussion.

I'll write something to formally express our position.

**Comment by marcoscaceres** [comment]
@padenot, @annevk, in the [intent to migrate for media playback quality](https://github.com/WICG/media-playback-quality/issues/11),  @domenic raised a concern about where standardization should happen: Media WG or WHATWG? Might be good to chime in there too.

**Comment by marcoscaceres** [comment]
Closing, as we now have separate issues for each.
