### ISSUE TITLE
Autoplay Policy Detection

### ISSUE THREAD

**Issue by padenot** [mozilla/standards-positions#186]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Autoplay Policy Detection
* Specification or proposal URL: https://github.com/wicg/autoplay/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1506289
* Mozillians who can provide input (optional): @padenot @alastor0325 @jyavenard

### Other information

This needs more discussion before implementing. We're following the spec (not written yet) and discussions. This will happen in the new Media WG.

**Comment by alastor0325** [comment]
We should close this because it's duplicated to https://github.com/mozilla/standards-positions/issues/675.
