### ISSUE TITLE
Element Timing API

### ISSUE THREAD

**Issue by digitarald** [mozilla/standards-positions#192]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Element Timing API
* Specification or proposal URL: https://w3c.github.io/element-timing/
* Mozillians who can provide input (optional): @ecsmyth, @vickychin

### Other information

A similar metric approach has been used in Firefox's performance automation https://bugzilla.mozilla.org/show_bug.cgi?id=1418368 .

**Comment by dbaron** [comment]
There may be some useful info in w3ctag/design-reviews#326 and w3ctag/design-reviews#395.

**Comment by martinthomson** [comment]
We just learned from Microsoft that this is shipping unprefixed in Edge and Chrome.  We'd like to have a position soon.

**Comment by zcorpan** [comment]
Is there an issue for moving this spec into the Web Performance WG (or somewhere else)?

**Comment by sefeng211** [comment]
This is being discussed and incubated within WebPerf WG. Is this what you are asking Simon? Are you looking for an issue for adoption?

**Comment by keithamus** [comment]
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1940239
