### ISSUE TITLE
HTML: autofocus="" overhaul

### ISSUE THREAD

**Issue by domenic** [mozilla/standards-positions#195]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Update to autofocus="" processing algorithm
* Specification or proposal URL: https://github.com/whatwg/html/pull/4763
* Mozillians who can provide input (optional): @bzbarsky has commented on autofocus work in the past; @annevk has asked that we improve the foundations of autofocus before working on custom element focus features.

### Other information

@tkent-google has been working on overhauling the autofocus processing model to better match browser behavior, while also making sense with the specification ecosystem, and avoiding surprising results for users. See some motivating issues in https://github.com/whatwg/html/issues/3551 (raised by @bzbarsky) and https://github.com/whatwg/html/issues/4563#issuecomment-486224619 (by @annevk).

Kent has a pull request at the above URL. However, we've had trouble getting other browsers to vet the proposal. As such it is hard for us to judge whether merging the spec PR, and implementing it in Chrome, would move us closer toward interop, or just create a new divergent behavior.

I am hoping that raising an issue on this repository will be a good way to get Mozilla input as to the proposed changes.

**Comment by bzbarsky** [comment]
The proposal looks generally reasonable to me, fwiw.  There are some parts of it that are not trivial to implement in Gecko, largely due to differences between the spec's model for some things nd Gecko's internal model, but I don't think will be too much of a problem in practice.  @smaug----

**Comment by dbaron** [comment]
I think a bunch of the feedback actually happened in whatwg/html#4763, but we should have remembered to come back after that happened and make a conclusion here; I think this should probably be marked as `worth prototyping`.
