### ISSUE TITLE
Limiting Same Origin Document Access

### ISSUE THREAD

**Issue by dtapuska** [mozilla/standards-positions#197]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Document Access Feature Policy
* Specification or proposal URL:  https://github.com/whatwg/html/pull/4606, https://github.com/dtapuska/documentaccess
* Mozillians who can provide input (optional): @bzbarsky @annevk 

### Other information
[Blink Intent to Implement](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Cibo-GNPs7Y/RznlX7WKDAAJ)
[TAG Review](https://github.com/w3ctag/design-reviews/issues/397)

**Comment by bzbarsky** [comment]
I'm generally pretty wary of adding new security primitives.  I raised https://github.com/dtapuska/documentaccess/issues/2 asking whether forcing nonce origins would achieve the goals of this proposal without the new-security-primitive angle.

**Comment by annevk** [comment]
Given the use cases provided and the statement that this is a security primitive, I don't think this is a good idea as while it allows some isolation between same-origin content, it leaves plenty of channels around. I recommend harmful as a position therefore. (I filed https://github.com/dtapuska/documentaccess/issues/4 on this.)

**Comment by dbaron** [comment]
@annevk do you still hold that position following the discussion in that issue?  If so, do you want to make a PR to add this to the table?

**Comment by dtapuska** [comment]
@annevk Just wanted to check in now that W3C has closed their review indicating that they do recognize the problem and the approach Chromium outlined was reasonable. I anticipate proceeding with it in Chromium but wanted to just have a final statement from Mozilla after the TAG review was completed.

**Comment by annevk** [comment]
I don't really see what's changed and it doesn't seem like the TAG considered the point about influencing the way code in third parties runs.
