### ISSUE TITLE
Web NFC API

### ISSUE THREAD

**Issue by wbob** [mozilla/standards-positions#198]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Web NFC API
* Specification or proposal URL: https://w3c.github.io/web-nfc/
* Caniuse.com URL (optional): see Fyrd/caniuse#2085
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1308614
* Mozillians who can provide input (optional): @marcoscaceres 

### Other information

The web-nfc draft is currently being updated. Its permission model is linked to the since [implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1105827) Permissions API (see #19). NFC offers use-cases linking the physical world to the web.

**Comment by beaufortfrancois** [comment]
I didn't realize this issue was filed before I created https://github.com/mozilla/standards-positions/issues/238. Sorry for this.

**Comment by annevk** [comment]
Duping this against the newer issue as that has more discussion.
