### ISSUE TITLE
Please add a LICENSE to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/standards-positions#2]
#1 indicates that content from this repository will be published on GitHub Pages, and the README is written as if for the general public. It would drastically simplify licensing concerns for this soon-to-be-published content if this repository applied a LICENSE prior.

https://www.mozilla.org/en-US/foundation/licensing/ encourages CC-SA for pure-content websites, and otherwise we use MPL2 for all repositories not otherwise compelled to use a specific license.

**Comment by annevk** [comment]
cc @dbaron

**Comment by dbaron** [comment]
So given that the repo has Python code in it, I think "pure-content" doesn't apply here.  [The relevant policy](https://www.mozilla.org/en-US/MPL/license-policy/) seems to allow MPL 2 or Apache 2.  I don't see any particular reason to pick Apache, so MPL seems like the right thing.

**Comment by dbaron** [comment]
I'd also note that some of the subdirectories have their own licenses; I guess that's normal.  I guess the convention is that a `LICENSE.txt` in a subdirectory overrides one in an ancestor directory.
