### ISSUE TITLE
Default Accessibility Semantics for Custom Elements

### ISSUE THREAD

**Issue by alice** [mozilla/standards-positions#201]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Default Accessibility Semantics for Custom Elements
* Specification or proposal URL: 
   - https://github.com/whatwg/html/pull/4658
   - https://github.com/alice/aom/blob/gh-pages/explainer.md#per-instance-dynamic-semantics-via-the-elementinternals-object
* Mozillians who can provide input (optional): Jamie Teh

### Other information

This will allow Custom Elements to have "default" accessibility semantics, analogous to how built-in elements have "implicit" or "native" semantics.

e.g.

```js
this._internals.role = "checkbox";
this._internals.ariaChecked = "false";
```

These can be overridden using regular ARIA attributes as normal.

This is [currently being implemented in Blink](https://groups.google.com/a/chromium.org/d/msgid/blink-dev/CACPC1r7EOVjJvsviO56AE9yZzUgR5EyiJFr9fcjvtq9ATGvALw%40mail.gmail.com?utm_medium=email&utm_source=footer), and we intend to ship this alongside [Reflecting IDREF/IDREF list ARIA attributes to element references](https://github.com/mozilla/standards-positions/issues/200).

**Comment by dbaron** [comment]
cc @jcsteh

**Comment by annevk** [comment]
Improving the accessibility story of custom elements is important and this is something we'd like to see happen.

cc @hsinyi

**Comment by nschonni** [comment]
Just making the comment here instead of the PR, but I think this should be `important` given discussions like https://twitter.com/sarahmei/status/1198069119897047041 which have people avoiding aspects of web components given accessibility gotchas

**Comment by annevk** [comment]
To be clear, this is important, but in the end this is a small part of a much larger whole and we tend to use `important` for bigger things I think.

**Comment by nschonni** [comment]
OK, thanks for clarifying @annevk
