### ISSUE TITLE
HTTPSSVC DNS Record

### ISSUE THREAD

**Issue by martinthomson** [mozilla/standards-positions#208]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Service binding and parameter specification via the DNS (DNS SVCB and HTTPSSVC)
* Specification or proposal URL: https://datatracker.ietf.org/doc/html/draft-nygren-dnsop-svcb-httpssvc/
* Mozillians who can provide input (optional): @ddragana, @agrover, @ekr 

### Other information

This specification aims to consolidate a number of fixes for problem with DNS resolution for HTTP: the "CNAME at the apex" aliasing issue, ESNI, alternative services, and better support for extensions.  It aims to be a one-stop shop for all DNS information necessary to access HTTPS resources.

This is currently under consideration by the IETF DNSOP Working Group for adoption.

**Comment by ekr** [comment]
I would suggest "worth prototyping" as the resolution for this. I don't necessarily love the way this spells everything, but we need it for ESNI and it should serve for that.

**Comment by ddragana** [comment]
This will also help discovering Http3 sooner, without making a TCP connection.
I think "worth prototyping" is fine.

**Comment by agrover** [comment]
I concur, worth prototyping.
