### ISSUE TITLE
RFP: API for Accelerated Shape Detection in Images

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#21]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Accelerated Shape Detection in Images
* Specification or proposal URL: https://wicg.github.io/shape-detection-api

### Other information
Photos and images constitute the largest chunk of the Web, and many include recognisable features, such as human faces, QR codes or text. Detecting these features is computationally expensive, but would lead to interesting use cases e.g. face tagging, or web URL redirection. While hardware manufacturers have been supporting these features for a long time, Web Apps do not yet have access to these hardware capabilities, which makes the use of computationally demanding libraries necessary.

**Comment by dbaron** [comment]
Some initial questions:
* how widespread are these APIs (across platforms/versions), and is the spec's behavior reasonable for when they're not available?
* does use of these APIs give privacy-sensitive information to the OS manufacturer?
* how much do we expect these APIs to be in demand?

@marcoscaceres , would you be able to drive this issue?

**Comment by marcoscaceres** [comment]
This is not an area I have much expertise in. However, we may have folks within Mozilla who have a background in computer vision. Nevertheless, some of the questions are answered in the project's [README](https://github.com/WICG/shape-detection-api/blob/master/README.md):

 * how widespread are these APIs (across platforms/versions)?

Detailed here: https://github.com/WICG/shape-detection-api#overview

Notable is that only some Android devices have hardware support (including top 10 selling Android devices). It appears most apps rely on third-party libraries. Android does provide an OS-level software-based shape detector. 

There is also some support in MacOS/iOS also through Apple provided frameworks - and in hardware on the iPhone since 2011. 

Windows also supports face and ORC. 

 * and is the spec's behavior reasonable for when they're not available?

It appears to be, as presumedly software implementations would be consistent results given the same input data. 

* does use of these APIs give privacy-sensitive information to the OS manufacturer?

Given the APIs described in the README, yes.    

 * how much do we expect these APIs to be in demand?

Use case are detailed here:
https://github.com/WICG/shape-detection-api#use-cases-camera

I personally find them compelling, mostly because they cater for extremely popular and commonly used application such as Snapchat, and, when the API works well, it can provide significant user convenience converting physical data to a digital form.  For example, automatically reading the credit card's details by just holding it up to the camera (Uber supports this, as well as iTunes). 

However, it's hard to really put a number on how much demand there actually is for this. OCR might also be useful in various contexts/apps (e.g., this kind of tech was used for [voter registration in the previous US election through a native application](https://twitter.com/RegistertoVote/status/733123511128981508))... but again, demand is hard to gauge. 

The concerns/challenges that have been raised thus far include: 

 * Is there significant advantage (i.e., orders or magnitude in speed and/or power consumption) saving over compiling and existing c/c++ library to do this in WASM? 
 * Would we only expose this API on platforms that support hardware acceleration? What would we do on platform like Linux? Would we need to create and maintain a library (could be a lot of work)?   
 * Would hardware QoS become a concern for interoperability? Different hardware might detect different things in different ways. 

I think we should "defer" on this API, but keep an eye on what comes back from Chrome's [origin trial](https://bugs.chromium.org/p/chromium/issues/detail?id=646035).

**Comment by reillyeon** [comment]
It was pointed out to me that @marcoscaceres's [comments](https://discourse.wicg.io/t/rfc-proposal-for-face-detection-api/1642/3) on the WICG Discourse have been superseded by this issue.

To provide an update based on Chrome's Origin Trial for this API we saw particularly strong interest in the barcode detection subset of this functionality. Based on that feedback we added feature detection support and [intend to ship](https://groups.google.com/a/chromium.org/d/msg/blink-dev/j-PLtssE5fo/budv_U6fCwAJ) this subset of the API first, with face detection coming soon afterwards once it receives similar improvements. Text detection has been dropped from the main specification as it does not have sufficient support yet across platforms.

I am requesting an update on Mozilla's position on this proposed standard.

**Comment by bzbarsky** [comment]
Just looking at the barcode detection API, it seems to add fingerprinting surface: the set of barcode formats supported by the API, which can be explicitly queried.  See https://wicg.github.io/shape-detection-api/#dom-barcodedetector-getsupportedformats

It's possible that it would be conforming for a UA to just return a list of all possible formats from this query even if in practice it never detects some of them, and thus avoid exposing extra fingerprinting surface.  The current spec language certainly supports that behavior, though authors would probably find it surprising...  Of course in a UA that does that this part of the API becomes completely useless.

**Comment by dbaron** [comment]
So I think one of the tradeoffs here is the amount of additional code that would be needed in browsers to support this.  (I suppose, though, that we could download that code lazily when the API is first used rather than increasing the browser download size for it, if we think it's likely to be used rarely.)

I'm not super-concerned about the fingerprinting concerns -- it seems like mostly data that duplicates information that we're not going to obscure (OS and version, categories of hardware that are likely pretty detectable through performance characteristics or other similar things).

Does a rating of `non-harmful` make sense here?  Does somebody want to argue for a different one?

**Comment by marcoscaceres** [comment]
I'd feel better with "defer" and take a wait-and-see approach to see how apps end up using this in Chrome.
