### ISSUE TITLE
ARIA IDL interface/reflection (non-IDREF)

### ISSUE THREAD

**Issue by alice** [mozilla/standards-positions#211]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: ARIA IDL interface and attribute reflection
* Specification or proposal URL: https://w3c.github.io/aria/#idl-interface
* Caniuse.com URL (optional): n/a
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1628418
* Mozillians who can provide input (optional): @jcsteh @annevk 

### Other information

Note that this request **excludes** attributes which have a type of "IDREF" or "IDREF list", which are discussed in #200. This is exclusively about IDL attributes for ARIA attributes which do not refer to other DOM elements, i.e. those with the type `DOMString` in the IDL interfaces in the spec linked above.

Safari has shipped this already; Chrome has implemented it behind a flag.

**Comment by annevk** [comment]
Do you know how Chrome and Safari deal with https://github.com/w3c/aria/issues/1058?

Jamie also brought up the point that using strings for all of these is perhaps not the most ideal API. Do you know why there is no usage of booleans, numbers, enumerations, et al?

**Comment by annevk** [comment]
With those caveats, this is considered `worth prototyping` by Mozilla.

**Comment by annevk** [comment]
@alice do you know when those issues will be addressed? I'm a little wary of resolving this issue as no progress has been made there.

**Comment by alice** [comment]
Sorry for being slow on this. I just had a chat with @cookiecrook about this and he's going to follow up on the other bug. We think we did consider this previously and came back to deciding they should all be strings, but we can't remember the logic, so he's going to try and dig that up.

**Comment by cookiecrook** [comment]
> he's going to follow up on the other bug. 

The "other bug" being ARIA issue 1110: https://github.com/w3c/aria/issues/1110

**Comment by asurkov** [comment]
> Safari has shipped this already; Chrome has implemented it behind a flag.

for the record, which version of Safari/Chrome it was implemented?

**Comment by cookiecrook** [comment]
Landed in WebKit in Fall 2018, so it probably shipped in one of the Spring 2019 releases of Safari.
https://trac.webkit.org/changeset/234482/webkit

**Comment by jcsteh** [comment]
Overall, we believe this is a useful convenience feature which will make life slightly easier for web developers. It is already being used by multiple websites in the wild, so it is important that we ship this for web compatibility. It also enables support for default Accessibility Semantics for Custom Elements (#201), which is important for accessibility of web components.

It's unfortunate that https://github.com/w3c/aria/issues/1110 wasn't resolved before this shipped in other browsers, as that might have made things a little nicer for authors. That said, we acknowledge that there are some challenges in mapping cleanly to ARIA attributes as they have been defined.

**Comment by martinthomson** [comment]
Based on discussions with @jcsteh and that comment, we're going with "positive" on this one.
