### ISSUE TITLE
new CSSStyleSheet - TypeError

### ISSUE THREAD

**Issue by Nashorn** [mozilla/standards-positions#215]
new CSSStyleSheet fails in Firefox dev edition with exception:
>> TypeError: Illegal constructor.

**Comment by annevk** [comment]
This is not the appropriate repository for bug reports or feature requests. You might be looking for https://bugzilla.mozilla.org/.

**Comment by bzbarsky** [comment]
In particular, see https://bugzilla.mozilla.org/show_bug.cgi?id=1520690

Also relevant is https://mozilla.github.io/standards-positions/ which is where issues on this repository would matter; this API is already listed as "worth prototyping" there.
