### ISSUE TITLE
WebVR Device API

### ISSUE THREAD

**Issue by kearwood** [mozilla/standards-positions#216]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebVR
* Specification or proposal URL: https://immersive-web.github.io/webvr/spec/1.1/
* Caniuse.com URL (optional): https://caniuse.com/#feat=webvr
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @kearwood

### Other information

Firefox has shipped this for some time (Firefox 55).  It is in use by many websites, such as sketchfab.com and aframe.io, and integrated into popular libraries, such as threejs.

This API is now deprecated, but expected to remain enabled in Firefox until shortly after its successor, WebXR, has shipped.

**Comment by Manishearth** [comment]
cc @larsbergstrom Would you be able to write down our current position about WebVR?

My _impression_ is that we wish to deprecate and eventually remove this API if possible, in favor of WebXR.

**Comment by larsbergstrom** [comment]
We are tracking the ongoing usage of WebVR and continuing to work with sites to try to get them to move to WebXR. Currently, over 25% of VR browser sessions engage WebVR, so there's still significant work to go, but we are working with these partners and expect them to migrate over the coming quarters.

We don't currently have a firm metric in place (e.g., Google's "must be < 0.03% of page loads"), but will continue to monitor over time.

**Comment by martinthomson** [comment]
As WebVR is now effectively defunct, we don't need to continue to track this.  We have filed a position on the WebXR Device API, which should address the preferred direction of the community.
