### ISSUE TITLE
scrollend and overscroll events

### ISSUE THREAD

**Issue by NavidZ** [mozilla/standards-positions#240]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSSOM View
* Specification or proposal URL: https://github.com/w3c/csswg-drafts/pull/4537
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @smaug----

### Other information

The original issue filed against CSS spec [here](https://github.com/w3c/csswg-drafts/issues/3801). Basically due to the scroll chaining rules there are some functionalities that page has no way of detecting as outlined in the issue. This proposal addresses that issue.

**Comment by dbaron** [comment]
also cc @heycam

**Comment by dbaron** [comment]
We've discussed the need for something like this a number of times in the past, and I think it addresses a need that's worth addressing.  (Jonas Sicking often bugged me about it.)  I think somebody needs to take a look at this particular proposal in a little more detail, though.

**Comment by smaug----** [comment]
I think these are something worth to implement.

**Comment by staktrace** [comment]
I also think these are useful to have. We've had requests for `scrollend` in particular in the past, and we have a half-baked implementation already: https://searchfox.org/mozilla-central/rev/c2bc259414706ef4be5d13df1344eebb7507a51b/layout/generic/nsGfxScrollFrame.cpp#4748-4750

**Comment by theres-waldo** [comment]
No objection from me. cc @mstange as well
