### ISSUE TITLE
Make the dashboard linkable?

### ISSUE THREAD

**Issue by domenic** [mozilla/standards-positions#245]
It would be nice if I could link to the Mozilla position on origin policy. Currently I can link to https://github.com/w3ctag/design-reviews/issues/127. But I cannot link to the part of https://mozilla.github.io/standards-positions/ which states the final position.

**Comment by dbaron** [comment]
Other than deciding whether to (a) add an id to every entry in `activities.json` or (b) write an algorithm to convert either the spec `title` or `url` to an ID (since those are the only unique and always-present fields), this should be pretty easy.

I think I'm currently leaning towards "algorithm to convert the title to an ID".

(Then I should add a `:target` style... and probably also (a tad harder) add some sort of UI for making a link to that target visible.)

**Comment by dbaron** [comment]
And, fwiw, the magic for DataTables is like this:

```diff
diff --git a/index.html b/index.html
index e9d170d..7686a03 100644
--- a/index.html
+++ b/index.html
@@ -120,6 +120,7 @@
               dataSrc: ''
           },
           dom: 'ilfrtip',
+          rowId: 'mozPositionIssue',
           "order": [[2, "asc"]],
           "columns": [
               {
```

(although that's bad since `mozPositionIssue` isn't unique).

**Comment by adamroach** [comment]
>I think I'm currently leaning towards "algorithm to convert the title to an ID"

FWIW, I think it would be both more ergonomic and more compact to use the final (or second-from-last if the final component is empty) component from the URL field.

**Comment by mconca** [comment]
This would be a tremendous enhancement. I often find I'd like to link to the standards position site from a Trello card, doc or bugzilla and being able to have a direct link to a particular proposal/feature would make that even more useful.

**Comment by dbaron** [comment]
I thought about using parts of the URL, but my concern is that a bunch of these URLs (particularly IETF ones) are going to change over time.  For example, I would expect that `draft-yasskin-http-origin-signed-responses` would get a new URL (which we'd probably want to link to) if it's adopted by an IETF working group.

**Comment by dbaron** [comment]
(On the other hand, if I get a URL part from an IETF spec beginning with "draft-", I suppose the algorithm could remove the first two dash-delimited pieces.)

**Comment by adamroach** [comment]
My concern is that document titles change on the order of as frequently as filenames for IETF documents, and I can find several examples of document that changed more than their second component when they were adopted by a working group.

The more I think about this, the more I think that we perhaps need a dedicated anchor field for each entry. We can have it initially populated by the algorithm in your pull request; but after that, it would remain static even if the other data in the entry changes.
