### ISSUE TITLE
ARIA Annotations

### ISSUE THREAD

**Issue by jcsteh** [mozilla/standards-positions#253]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Simplified ARIA Annotations
* Specification or proposal URL: https://github.com/aleventhal/aria-annotations (links to W3C ARIA issues and pull requests)
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1608975
* Mozillians who can provide input (optional): @annevk

### Other information
This adds two new ARIA roles, a new aria-description attribute and expands aria-details. These changes are needed to support screen reader accessibility of comments, suggestions and other annotations in published documents and online word processing scenarios such as Google Docs, iCloud Pages, and MS Office Online. This is not currently possible without resorting to live region hacks, which are not as reliable as semantics and do not work well with Braille displays. As a result, screen reader users have non-optimal support for collaboration features of online word processors.

It is implemented in Chrome behind a flag. Bug URL: https://bugs.chromium.org/p/chromium/issues/detail?id=1006767

**Comment by jcsteh** [comment]
I think this is important. I was involved in early discussions and reviews for this work and the concerns I raised have already been addressed in this draft.

**Comment by bzbarsky** [comment]
Looking at the explainer:

* aria-description is pretty clearly a good "reduce the complexity of using this" idea.
* role="suggestion" -- are "insertion" and "deletion" pre-existing roles?
* role="mark" -- it's not clear to me what the note at the end of its description means in practice.  Is it that not all annotated content should have this role, or something else?
* role="comment" is presumably a generic "comment that might not be an editing suggestion"?  Would it make sense to change "suggestion" to "edit-suggestion" if that's its intended purpose?  (Not trying to drive-by bikeshed; it's just not clear to me at first glance when "comment" vs "suggestion" would be appropriate.... can "suggestion" be a general "reword this" without specific changes proposed?

In general, this all seems quite sane to me; with my _very_ limited knowledge of ARIA.  I'm glad this is explicitly not trying to import Web Annotations wholesale!  @tantek 

@dbaron any concerns you see with adding this as "important"?

**Comment by jcsteh** [comment]
>     * role="suggestion" -- are "insertion" and "deletion" pre-existing roles?

Yes. We [already support them](https://bugzilla.mozilla.org/show_bug.cgi?id=1540813#c4).

>     * role="mark" -- it's not clear to me what the note at the end of its description means in practice.  Is it that not all annotated content should have this role, or something else?

It might be appropriate to use role="mark", but that doesn't necessarily mean the content is "visually highlighted". For example, it might be a breakpoint in a code editor, in which case the visual presentation might be something different than a highlight. I think the note is just to clarify that even though HTML `<mark>` highlights by default, we don't want to suggest that "mark" always means "visual highlight".

>     * role="comment" is presumably a generic "comment that might not be an editing suggestion"?

Reading it again, the earlier part of the explainer is a bit unclear here. role="comment" is the comment itself, not the reference to the comment. You would refer to the comment from the text using role="mark":

```
<p>The <span role="mark" aria-details="thread-1">cat is smart</span>.</p>
<div role="comment" id="thread-1">
  As far as you can tell! Does she talk?
</div>
```

In contrast, suggestion occurs within the content itself and covers an insertion, a deletion or both.

**Comment by aleventhal** [comment]
Hi @dbaron, WDYT? Would love to get public support for Mozilla on this. 
Here's the Chrome status entry: https://www.chromestatus.com/feature/4666935918723072
And here's the blink thread: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/2uume_z0n8M

**Comment by aleventhal** [comment]
Additional status: all of the new markup PRs were merged and are now the ARIA draft master.

**Comment by aleventhal** [comment]
Hi all, ARIA Annotations has left the experimental stage in Chrome. Starting Monday, no flag will be needed to use ARIA Annotations in Canary (82).

Our API review team decided that there was enough public support to move forward, so hopefully this works for Mozilla as well.

**Comment by dbaron** [comment]
This seems reasonable to me, but it would be good to see this moved into an official repository of the appropriate working group (ARIA WG?) given that (or, really, prior to!) implementations are moving forward.  I'll make a PR to mark it as `important`.

**Comment by aleventhal** [comment]
Hi @dbaron, thanks for taking a look. The markup has all made it into the official ARIA repo. The explainer has links to all the merged PRs.
