### ISSUE TITLE
Structured Headers

### ISSUE THREAD

**Issue by mnot** [mozilla/standards-positions#256]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Structured Headers for HTTP
* Specification or proposal URL: https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by annevk** [comment]
With the caveat that I helped a bit with this, I recommend `worth prototyping`. Moving away from custom parsers for new (and some old) HTTP headers will be terrific and long term it might also serve as a building block for a better exchange format and a typed API for headers in JS/Wasm.

**Comment by martinthomson** [comment]
I can second that.  This is a structural thing, so it's unlikely we'll see the effects of this directly, but it should go a long way to improving consistency (and interoperability).

I'm also somewhat enthusiastic about how this could open the way to some fairly significant improvements in performance through the use of new encodings.

**Comment by ddragana** [comment]
I agree here as well that this should be `worth prototyping`

**Comment by tantek** [comment]
I read the Structured Headers for HTTP proposal and browsed the test suite. Looks reasonable.

As someone who has written a few custom parsers for HTTP headers, I welcome this.

Agreed with at least "worth prototyping".

With the potential to reduce duplication of code, and especially reduce infrequently-run code paths for rare(r) headers, I think there are likely security benefits as this is adopted for new (and possibly old headers).

For that reason I think Mozilla should consider this as "important" or at least state that we can see this being/becoming "important".

(Originally published at: https://tantek.com/2020/034/t1/)
