### ISSUE TITLE
WebXR Hit Test

### ISSUE THREAD

**Issue by mounirlamouri** [mozilla/standards-positions#259]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebXR Hit Test Module
* Specification or proposal URL: https://immersive-web.github.io/hit-test/
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): @kearwood, @larsbergstrom, @philip-lamb, @daoshengmu, @thomasmo (copying the list from #218)

### Other information

This API allows websites to perform hit tests with the XR environment.

GitHub: https://github.com/immersive-web/hit-test
Explainer: https://github.com/immersive-web/hit-test/blob/master/hit-testing-explainer.md

**Comment by hober** [comment]
See also https://github.com/w3ctag/design-reviews/issues/463

**Comment by larsbergstrom** [comment]
We believe that it is premature to establish a Mozilla standards position or get TAG review of the WebXR Hit Test module. There are a significant number of security, privacy, naming, and functionality issues with the current proposal (https://github.com/immersive-web/hit-test/issues ), and it has not been prototyped by any other party yet - and most importantly, never on a headworn AR device.

This is an important capability for WebXR, and while Mozilla is deferring any conclusion at this point, we encourage its adoption into the updated WebXR WG charter and further iteration. At this time it would be a mistake to ship this API publicly as we expect significant changes to this API in the coming months.

**Comment by dbaron** [comment]
I'm closing this based on #267 (forgot to put "fixes" in my commit message!), but we should reopen this when it's time to reconsider.
