### ISSUE TITLE
RFP: Activation Delegation

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#26]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Activation Delegation
* Specification or proposal URL: https://github.com/WICG/gesture-delegation/blob/master/explainer.md

### Other information
Some features on the platform require a user activation in order to be triggered. Among these features, some of them require a user activation to have happened on the document. Gating features to user activations is meant to reduce user annoyance but can hurt the ecosystem when the features are triggered from an iframe. Indeed, iframes may be used as components of a website and can be used to sandbox third party code. Allowing these iframes to be able to use the user activation information from the embedder would still allow the embedder to limit the behaviour of an iframe without entirely breaking the intended experience.

**Comment by annevk** [comment]
This is prolly superseded by other user activation proposals, right?

**Comment by annevk** [comment]
@mounirlamouri do you know the status here?

**Comment by mounirlamouri** [comment]
This specific feature is dead and we ended up using Feature Policy. We may end up still adding something either to Feature Policy or something else because Feature Policy requires the permissions to be set at creation which in the case of autoplay (and others) is a non-needed requirement.
