### ISSUE TITLE
Schemeful Same-Site

### ISSUE THREAD

**Issue by sbingler** [mozilla/standards-positions#260]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Schemeful Same-Site
* Specification or proposal URL: https://mikewest.github.io/cookie-incrementalism/draft-west-cookie-incrementalism.html#rfc.section.3.3. 
~~https://html.spec.whatwg.org/multipage/origin.html#same-site~~
* Chrome Intent to Prototype: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/qB7DKqxkiaA

### Other information
Schemeful same-site has been my name for it to make it easier to talk about. In reality the term same-site will mean schemefully and schemeless same-site will be a new concept.

**Comment by tomayac** [comment]
(There's a typo `s/Sam-eSite/Same-Site/` in the issue title, you might want to fix that in order for search to pick it up.)

**Comment by annevk** [comment]
The specification link is somewhat confusing, as this is really a change to cookies from the intent email. Is there a proposed change to the cookie specification that we could study?

**Comment by sbingler** [comment]
Thomas: Whoops, sorry about that. Thank you to Boris for fixing that up!

Anne: If you're referring to rfc6265bis then yes there is a proposed change in the works but it's not not ready for review yet. I'll ping this issue when it is.

**Comment by annevk** [comment]
In https://github.com/w3ctag/design-reviews/issues/497 I asked how this relates to the Scheme-Bound Cookies proposal (which Mozilla considers important).

**Comment by annevk** [comment]
FWIW, given the explanation there this seems `worth prototyping` to me.

cc @bakulf

**Comment by sbingler** [comment]
Hi all, 

Thank you for the update Anne.

For posterity I'm still pinging this thread with the spec: https://mikewest.github.io/cookie-incrementalism/draft-west-cookie-incrementalism.html#rfc.section.3.3.

**Comment by bakulf** [comment]
I agree it's `worth prototyping`. I can work on it.

**Comment by adamroach** [comment]
@martinthomson -- I know you have put some cycles into thinking about how to improve handling here. What's your take on Mike's proposal?

**Comment by martinthomson** [comment]
@bakulf's assessment is good.  In short, anything that allows us to reduce the span over which cookies are reused is good, but comes with a risk to compatibility with sites that depend on the wider spread.  Same-site cookies are relatively new and from Mike's research I infer that they are used predominantly with https:// origins.  Let's go with `worth prototyping`.

**Comment by adamroach** [comment]
Based on the analysis above, I propose `worth prototyping` with detail of:

> Any approach that reduces the scope of cookie use is a privacy win. Because some such changes can break websites that rely on the broader scope, we would like to proceed with caution, but believe that the feature is worth experimenting with and collecting data about.

**Comment by annevk** [comment]
Sounds good. I'd probably also say it's a security win.
