### ISSUE TITLE
Specification maturity

### ISSUE THREAD

**Issue by martinthomson** [mozilla/standards-positions#263]
One of the problems that we routinely have with making assessments of proposals seems rooted in problems in the specification.  We often get asked to express a view on specifications that are very much in a draft state, or that have gaps.  Sometimes the nature of those gaps is significant in our assessment.

In our positions, should we say anything about our view of the maturity of the specification?  This might allow us to separately express the degree to which we think that the specification needs work.  Positive or negative indications associated with less mature specifications are therefore less certain.

The risk here is that we increase our exposure to a need to revise positions, so I'm not certain that this is definitely a good idea.

**Comment by annevk** [comment]
I think the approach of waiting with a definitive position until certain critical issues are resolved is working rather well. E.g., Reporting API is harmful if it creates a per-origin cache, but if it does not, it's worth prototyping.

And we can use the "proposal appears unstable" label to indicate a final assessment has to wait.

**Comment by martinthomson** [comment]
Just to close the loop here.  Based on discussions with @tantek I came to the same conclussion as @annevk.  I think that we have to recognize that specification maturity is part of our assessment process, but that might just lead to more cases of "defer".  There are a bunch of other refinements to the process that came out of that discussion and I plan to follow up on those once I have some time.
