### ISSUE TITLE
Media Session API

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#28]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Media Session Standard
* Specification or proposal URL: https://w3c.github.io/mediasession/
* Bugzilla URL (optional):  https://bugzilla.mozilla.org/show_bug.cgi?id=1112032

### Other information
Add support for media keys and audio focus to the Web. Media keys, like play, pause, fast forward and rewind, are found on keyboards, headsets, remote controls, and on lock screens of mobile devices.

I think Chrome is shipping this in Chrome for Android.

**Comment by nils-ohlmeier** [comment]
@padenot @jyavenard do you have any thoughts on this?

**Comment by marcoscaceres** [comment]
Given that we've moved this to the W3C, and we (Mozilla) are part of the Media Working Group, and that WebKit folks are also supportive of this API, I think it's definitely "worth prototyping". 

The use cases for this API remain quite compelling, specially on mobile.

**Comment by padenot** [comment]
We're in support and following this spec.

Also note that the audio focus bits are now in https://github.com/WICG/audio-focus. We've started writing code for Media Session, and have the back-end code for audio focus already.

**Comment by marcoscaceres** [comment]
@padenot, as this work is underway, any chance you could put together a PR to close this off?

**Comment by codehag** [comment]
I will create a pull request for this as "worth prototyping", for posterity. This is coming a little late.
