### ISSUE TITLE
Position on Storage Access API

### ISSUE THREAD

**Issue by mconca** [mozilla/standards-positions#280]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Storage Access API
* Specification or proposal URL: https://github.com/privacycg/storage-access
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @ehsan

### Other information
Microsoft recently indicated they will be landing an implementation of the Storage Access API in Edge (and thus Chromium).  Firefox and Safari have shipped their own implementations (which are slightly different).

It seems like it would be useful to publically capture Mozilla's position on this API, perhaps in anticipation of the spec being finalized once all three major browser engines have support for it.

**Comment by ehsan** [comment]
A bit about the status of this API in Firefox.  We shipped an implementation of this API as the second implementer after WebKit in [Firefox 66](https://bugzilla.mozilla.org/show_bug.cgi?id=1513021) on desktop (the [mobile](https://bugzilla.mozilla.org/show_bug.cgi?id=1543720) implementation is being worked on).  I should have filed this issue at the time we were working on the implementation, my apologies for not having done so.

I think this feature is `worth prototyping` for two reasons:

- In our current efforts to limit the impact of cross-site tracking there are cases where we may unintentionally break parts of web pages that users depend on.  The storage access API provides a programmatic way for affected embedded content to fix these types of broken experiences for the user.
- In our upcoming efforts to limit the potential capabilities for unknown third-parties to track the user, we would like to continue to restrict the storage capabilities of the third-party context.  The storage access API similarly provides a programmatic path for the embedded widgets which cannot work correctly without access to their data.

It isn't an ideal solution, for example our implementation falls back to prompting the user if it cannot automatically determine whether access should be granted or not, but it is a step in the right direction in the game of reversing the current defaults of the web, that is granting permissive storage access rights to all third-party contexts unconditionally.

**Comment by johannhof** [comment]
Considering our past work on this aren't we realistically considering this to be `important` instead?

**Comment by dbaron** [comment]
Also cc:ing @TanviHacks.

**Comment by dbaron** [comment]
So I've been trying to use `important` for standards we we want to put substantial effort into.  I'm not sure whether this fits that bar, but I agree that at least `worth prototyping` makes sense here.
