### ISSUE TITLE
Crash Reporting

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#288]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Crash Reporting
* Specification or proposal URL: https://wicg.github.io/crash-reporting/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1607364 (code landed behind a flag)
* Mozillians who can provide input (optional): @bakulf @lukewagner 

### Other information

This feature builds on https://w3c.github.io/reporting/ (see #104). It would report the URL where the crash happened and a reason ("oom" (out-of-memory) or "unresponsive" (e.g., `while (true)`).

There's an ongoing discussion as to whether the user ought to be involved in sending crash reports: https://github.com/WICG/crash-reporting/issues/1. I'm inclined to think they should, primarily for consistency with other crash reports, even if much less information is exposed. The behind-a-flag implementation in Firefox does not have such UI as far as I'm aware.

**Comment by mconca** [comment]
I'm also inclined to think the user should be involved.  Adding an element to the existing crash report dialog along the lines of "Let the website know that your browser crashed" seems logical.

**Comment by lukewagner** [comment]
We got frequent requests for this functionality back during the games program, so I definitely believe that it's a real dev problem.  But I can also see the theoretical risk of not having an opt in as described in [Anne's comment](https://github.com/WICG/crash-reporting/issues/1#issuecomment-595757317).

**Comment by dbaron** [comment]
So what do you think of this functionality more generally?  Do you think it seems useful enough to be worth prototyping?  (It also doesn't seem like there's any *barrier* to the browser asking the user's permission, although maybe I'm missing something.)

**Comment by lukewagner** [comment]
Good point.  I think it's worth prototyping.

Also, thinking about it again on a fresh day; the last time I talked to gamedevs diagnosing load-time crashes/OOMs, for lack of crash reporting, they ended up sending regular heartbeat messages back to the server between every significant step of loading the game so the last received heartbeat is effectively a crash report.  So maybe crash reporting is no worse, only less resource/effort intensive.  At least I think it's worth further discussion of whether the UX prompt is truly necessary.
