### ISSUE TITLE
RFP: IndexedDB Observers

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#32]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: IndexedDB Observers
* Specification or proposal URL: https://github.com/WICG/indexed-db-observers/blob/gh-pages/EXPLAINER.md

### Other information
Name is fairly self explanatory. Right now, it's just a rough outline being proposed by Google folks, I believe.

**Comment by annevk** [comment]
cc @asutherland

**Comment by codehag** [comment]
This still appears stale, and will be closed.
