### ISSUE TITLE
Fragment links should expand the details

### ISSUE THREAD

**Issue by jyasskin** [mozilla/standards-positions#323]
As a followup to #245, when I link to https://mozilla.github.io/standards-positions/#webusb, it would be nice if it would auto-expand the Description and Mozilla's Position `<tr>` instead of making the person who gets the link figure out which piece of the row to click to get more details.

**Comment by dbaron** [comment]
I thought about various combinations here (some of which involved dropping the ability to have multiple items expanded at the same time), and couldn't convince myself strongly enough that one of them was better than the other (or the status quo) to get myself to implement one of them.  That said, I did definitely think about wanting auto-expanding when something is the target.  (Target-on-load, or target at any time?)

Maybe just auto-expand if something is *ever* the target is simple enough that it's a straightforward improvement, although I'm a little worried there are already enough mixed metaphors in this UI design...

**Comment by annevk** [comment]
I'd suggest we use `window.onhashchange` (i.e., expand whenever the fragment changes, I wouldn't automatically collapse again though). And maybe we should also offer "expand all" somewhere.
