### ISSUE TITLE
RFP: Async cookies API

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#33]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Async cookies
* Specification or proposal URL: https://github.com/WICG/async-cookies-api/blob/gh-pages/explainer.md

### Other information
Asynchronous cookie API to scripts running in HTML documents and service workers.

Seems Blink team is [sending tests](https://github.com/w3c/web-platform-tests/pull/7484) for this API to WPT - but marked as "don't merge" rn.

**Comment by hsivonen** [comment]
See also [Cookie Change Events](https://github.com/mozilla/standards-positions/issues/50).

**Comment by annevk** [comment]
This is now #94.
