### ISSUE TITLE
CSS Properties & Values API: @property

### ISSUE THREAD

**Issue by andruud** [mozilla/standards-positions#331]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Properties & Values API (`@property` subfeature)
* Specification or proposal URL: https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule
* Caniuse.com URL (optional): https://caniuse.com/#search=%40property

### Other information

- Blink [Intent to Ship](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/3ygpsew53a0/T7acB6sRBQAJ)

There's an existing [position](https://mozilla.github.io/standards-positions/#css-properties-and-values-api) on CSS Properties & Values API, and I'm looking for a clarification on whether or not this position extends to `@property`.

**Comment by andruud** [comment]
@emilio was involved with `@property` on the spec level before, and can probably comment.

**Comment by annevk** [comment]
https://github.com/w3c/css-houdini-drafts/issues/940 is relevant.

**Comment by emilio** [comment]
Yeah, I like `@property` better than the JS counter-part, fwiw. I think that given we gave properties-and-values the "worth-prototyping" status this should be at least the same.

**Comment by dbaron** [comment]
Also see #93, where we added the original position.
