### ISSUE TITLE
Scroll-driven Animations

### ISSUE THREAD

**Issue by andruud** [mozilla/standards-positions#347]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Scroll-driven Animations
* Specification or proposal URL: https://drafts.csswg.org/scroll-animations-1
* Caniuse.com URL (optional): N\A
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1324602
* Mozillians who can provide input (optional): @botond-ballo

### Other information

There appears to be some support for this feature already (given the prior work done on it), but it would good to add an entry for it. Also the spec now contains a declarative API (@scroll-timline etc), which needs evaluation.

(cc @majido, so he knows this exists).

**Comment by majido** [comment]
Thanks for filing this. Also cc'ing @heycam and @birtles who perhaps have more recent context on changes to the specification since it was initially produced in collaboration with Mozilla.

**Comment by majido** [comment]
Also here is the explainer for this feature which goes in more details on usecases and API choices: https://github.com/w3c/csswg-drafts/blob/master/scroll-animations-1/EXPLAINER.md

**Comment by birtles** [comment]
I'm not a Mozilla employee so these are just my thoughts as the current 'DOM: Animation' module owner and one of the editors of this spec (where my current involvement is focused on reviewing those parts that interact with Web Animations).

I think this should be "worth prototyping" for the following reasons:

* Mozilla wrote the initial spec (incorporating ideas from a related proposal from Apple－see references below).
* Mozilla realized the need for this feature based on our experience with Firefox OS (I believe the request for this came from Jonas' team at the time).
* As a fairly high-level/declarative spec it is expected to provide more avenues for user control (e.g. disabling scroll effects), be accessible to more developers, be more amenable to future optimizations, and impose less restrictions on developments in browser architecture than more low-level/imperative alternatives.
* We already have [some patches](https://bugzilla.mozilla.org/show_bug.cgi?id=1321428) for a partial implementation based on an old version of the spec.
* It integrates with both CSS and Web Animations.
* It appears to have support from other browser vendors (Google, Microsoft, and Apple are involved).

References for posterity:
* [Initial proposal for extending timelines from May 2014](https://wiki.mozilla.org/Platform/Layout/Extended_Timelines)
* [Related proposal from Apple in Sep 2014](https://lists.w3.org/Archives/Public/www-style/2014Sep/0135.html)
* [Request to pick up Apple's proposal from March 2016](https://lists.w3.org/Archives/Public/www-style/2016Mar/0357.html)
* [Initial spec commit from August 2016](https://github.com/WICG/scroll-animations/commit/04cd8c45b8d8293cf4cfbe7bb6a558fdf6e95f92)

**Comment by flackr** [comment]
The spec has undergone a [fairly radical change with greatly improved css ergonomics](https://github.com/w3c/csswg-drafts/issues/6674) with working group resolutions for all of the major decision points. We are down to a very small set of issues remaining being tracked by https://github.com/w3c/csswg-drafts/projects/33. It also looks like there is also an implementation started in https://bugzilla.mozilla.org/show_bug.cgi?id=1676780. Could we get a position?

**Comment by BorisChiou** [comment]
I'm fine with positive position, per Brian's comment, and we have been working on this already.

**Comment by SebastianZ** [comment]
FWIW, the spec. got renamed to "Scroll-driven Animations". So, when adding it to the dashboard, the entry should use the same terminology.

And, I guess since there's already work for this happening, this can be labelled with "position: positive" and "ready to add".

Sebastian

**Comment by zcorpan** [comment]
Adjusting labels based on the comments above.

**Comment by stratboy** [comment]
Scroll-driven Animations should be already implemented.

**Comment by Antoineview** [comment]
Update on this ?

**Comment by BorisChiou** [comment]
We are implementing this now (the meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=scroll-animations-1)
