### ISSUE TITLE
RFP: Generic Sensors

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#35]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Generic Sensor API - and friends...
* Specification or proposal URL: https://www.w3.org/TR/generic-sensor/

### Other information
This has also spawned other sensors that inherit the generic interface - which refactor sensors we already have exposed (and in many cases had to remove) in the browser.

**Comment by jonathanKingston** [comment]
> Perhaps the best way to manage this is to consider the merits of each sensor as a feature in isolation

Agreed, I think we could assess the sensor doc in it's generic sense and from a privacy/security stand point it's probably fine.

Just an update here we are in the process of unshipping ambient light and proximity sensors and deprecating orientation and motion all of which have better counter parts in generic sensors. However as @annevk points out there isn't a decent story for adding privacy to any of these sensors yet.

**Comment by foolip** [comment]
I came here from the [Intent to Ship: Generic Sensors-based Motion Sensors](https://groups.google.com/a/chromium.org/d/msg/blink-dev/r8iKkTXftm4/8iBn0c2UAAAJ) on blink-dev.

On the issue of different privacy/security policies for different types of sensors or between UAs, it looks to me like the solution for this is [the SensorErrorEvent interface](https://w3c.github.io/sensors/#the-sensor-error-event-interface) and there's a [good example for Accelerometer](https://w3c.github.io/sensors/#feature-detection) covering the exception thrown in the constructor and error events fired later. Does that address the concerns in this thread?

**Comment by annevk** [comment]
The way I understand it the answer to https://github.com/w3ctag/design-reviews/issues/207#issuecomment-350125076 (can you ask the user about this?) is to not ask the user and just lower the resolution. However, at least Mozilla's XR folks have said that low resolution is not adequate at which point it doesn't really seem worth exposing these.

**Comment by foolip** [comment]
For the sensors that correspond to https://w3c.github.io/deviceorientation/spec-source-orientation.html which are enabled already by default, the answer indeed to not ask the user, and to use the same resolution as for the existing APIs. Just to be sure I tried http://googlesamples.github.io/web-fundamentals/fundamentals/native-hardware/device-orientation/dev-orientation.html on Firefox Nightly for Android and it works.

If at some point in the future one or more vendors wanted to gate access to those sensors on asking the user, then it looks to me like the Generic Sensors API is well equipped to allow that, but the risks of trying to ship that are similar to trying to limit the deviceorientation and devicemotion events, namely that web developers just assume they work and the result will be a non-functional page.

**Comment by martinthomson** [comment]
There is bad UI and there is bad UI.  I think that the principle should be that we don't ship features for which we believe that require consent unless we have a very clear story about how that consent is obtained.  That means that we need great UX if the feature depends on UX.

The other part was that **generic** was generally not considered as a valuable property when it comes to deciding whether a feature is worth shipping.  Each capability needs to be assessed on its own merits.

That's a slightly different emphasis, but not fundamentally different.

**Comment by rniwa** [comment]
FWIW, Apple's WebKit team doesn't support generic sensors API either for similar reasons as Mozilla's.
