### ISSUE TITLE
make expand/collapse nature of entries more obvious

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#354]
One thing I worry about with the [positions table](https://mozilla.github.io/standards-positions/) is that it's not obvious to readers that the entries expand.  Yet the parts that are visible when you expand them are an important part of the message we're trying to convey.

To remedy this, I'd like to make roughly the following changes:
* add expand/collapse triangles at the left edge, replacing (I think) the "Details" column and icon
  * probably this requires moving the link icon to the right edge, but not entirely sure
* add [Expand All] and [Collapse All] buttons at the top

Thoughts?

**Comment by adamroach** [comment]
These sound like an improvement. Thanks.

/a

**Comment by mconca** [comment]
This would be a great UX improvement.

**Comment by annevk** [comment]
That sounds good. Related thoughts while here:

* I wonder if we can indicate somehow that there's a Mozilla's Position entry as some expand to only show Description, which is not as interesting unless you're using this page to learn about new things.
* It seems the expansion bit is abusing tables quite badly. I think semantically Description and Mozilla's Position ought to be their own columns. I haven't played enough with CSS in the last decade to know if that's feasible however.
* Similarly, it's a bit bad this page only works when you have scripting enabled.

**Comment by dbaron** [comment]
All of those related thoughts seem valid, though I think worth separate issues if you think it's worth tracking them.  The second and third would require switching to something other than [DataTables](https://datatables.net/), and the third would require even larger restructuring.  The first is a pretty tractable separate issue.

For what it's worth, my PR did the things in my initial comment other than moving the link bit to the right; I think it's *probably* OK as-is, though if others feel strongly I'd like to know.

**Comment by dbaron** [comment]
(And the "turn things that are semantically columns into their own row" isn't really something that CSS tables can do in any straightforward way.)
