### ISSUE TITLE
RFP: Geolocation using Generic Sensor API

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#36]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Geolocation Sensor
* Specification or proposal URL: https://w3c.github.io/geolocation-sensor/

### Other information
Geolocation API refactored to use Generic Sensor spec.

**Comment by hsivonen** [comment]
The intro says this enhances privacy and security. How exactly? What problem does this solve beyond making geolocation looks like other sensors API-wise?

**Comment by annevk** [comment]
It does not appear to solve a problem in that space as far as I can tell. And as discussed in #35 it's not clear sensors need a generic API. I've suggested we close this as harmful in #399 with this rationale:

> Given that the web already has a geolocation API, any additional API for the same purpose would have to meet a high bar as both will need to be maintained forever. While the document claims to improve security and privacy, there is no evidence that is the case. And as it can be largely polyfilled on top of the existing API, it seems better to invest in web platform geolocation additions there, if any.
