### ISSUE TITLE
Use labels to identify context

### ISSUE THREAD

**Issue by martinthomson** [mozilla/standards-positions#37]
Based on the intro and the structure of the process, I think that we probably want the following labels: w3c, ietf, ecma.  @marcoscaceres has been modifying titles, which doesn't really scale well.  We probably want the coordinators to be responsible for applying labels.

**Comment by dbaron** [comment]
I made labels for the various standards orgs, as well as a `policy` label for issues about how we run/operate this repository, and started using the `bug` label for bugs in the python code.  Probably more to do here, though.

**Comment by annevk** [comment]
If folks need more labels, I'd be happy to add them, just let me know.
