### ISSUE TITLE
A Well-Known URL for Changing Passwords

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#372]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: A Well-Known URL for Changing Passwords
* Specification or proposal URL: https://wicg.github.io/change-password-url/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @mnoorenberghe @mozfreddyb @dveditz

### Other information
Supported in Safari with implementer interest from Chrome. Supported by Twitter and Facebook. 
See: https://github.com/WICG/change-password-url/issues/16

**Comment by hober** [comment]
I don't know MattN's GitHub username, but perhaps he or other lockwise folk have thoughts on this?

**Comment by mnoorenberghe** [comment]
This would be useful for various features within Firefox/Lockwise and Firefox Monitor, specifically related to website breaches. A year ago we even analyzed support for this proposed standard in https://github.com/mozilla/blurts-server/issues/1112#issuecomment-510578444. An alternative to having this standardized is manually building up a database of change-password URLs without the help of the website author but implementing this standard would be preferable from a maintainability standpoint. In the medium term we wouldn't rely exclusively on this .well-known URL, using a curated list of change password URLs for sites which don't support it but which we want to provide a link to change the password e.g. for a site added to monitor.firefox.com.

I would recommend `worth prototyping` as it's beneficial to Mozilla products, low cost to implement and maintain, and straightforward for authors to adopt.

**Comment by annevk** [comment]
There's a MIT licensed data set at https://github.com/apple/password-manager-resources that can be used with this Well-Known scheme as fallback/eventual replacement.

(I'm sure we all keep hoping for a better way to do identity, but until that's there and adopted this seems like a pretty decent improvement to the status quo.)

**Comment by FaRrules** [comment]
Dos i say Moz bug url?

**Comment by FaRrules** [comment]
If so old Hells Angels biker WHO my lovelig Girl fuckt before me im glad if so he just Got Trowht out hahahaha
