### ISSUE TITLE
Testing in standards: from idea to full interop

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#38]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Testing in standards: from idea to full interop
* Specification or proposal URL: https://github.com/foolip/testing-in-standards/blob/master/lifecycle.md

### Other information
Proposes to enhance the w3c work mode to more closely align with the [WHATWG Work Mode](https://whatwg.org/working-mode). It would be a grass roots effort.

In particular, encourages more use of  ".tentative" as a filename post-fix to identify things in Web Platform Tests on which implementers don't have agreement on.    

This is part of a larger discussion we've been having with Google about what ends up in WPT (and https://wpt.fyi). For example, should "Web Share" tests be part of the WTP without having the ".tentative" post-fix? (please don't fixate on Web Share, on which we have not yet taken a position #27, I'm just using it as an example).

**Comment by annevk** [comment]
I think we're largely supportive of this and there's not much negative side effects. It in fact has helped when we did decide to experiment with something. I'm going to close this though as there's not much to record here I think. Please reopen if you disagree.
