### ISSUE TITLE
HTML: dialog element

### ISSUE THREAD

**Issue by tantek** [mozilla/standards-positions#388]
## Request for Mozilla Position on an Emerging Web Specification

  * Specification Title: HTML: The dialog element
  * Specification or proposal URL: https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element
  * Caniuse.com URL (optional): https://caniuse.com/dialog
  * Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=840640
  * Mozillians who can provide input (optional): [@annevk](https://github.com/annevk), [@dbaron](https://github.com/dbaron)
  * W3C Tag Design Review issue: none

### Other information

We have implemented the HTML dialog element in Nightly ([announced Monday](https://wiki.mozilla.org/Firefox/Roadmap/Updates#2020-07-06)), with a few caveats as described in [Bugzilla 1645046](https://bugzilla.mozilla.org/show_bug.cgi?id=1645046).

Along with inert ([#174](https://github.com/mozilla/standards-positions/issues/174)), this seems worthy of recording as "worth prototyping".

Label: whatwg.

(Originally published at: https://tantek.com/2020/191/b1/)

**Comment by annevk** [comment]
Agreed. See also https://github.com/whatwg/html/issues/4937#issuecomment-536000145 by @mconca.
