### ISSUE TITLE
WHATWG Working Mode and test policy

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#39]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WHATWG Working Mode
* Specification or proposal URL: https://whatwg.org/working-mode

### Other information
We need to have a discussion about the [WHATWG Work Mode](https://whatwg.org/working-mode) and to [WHATWG testing policy](https://blog.whatwg.org/improving-interoperability). This includes taking an organizational position on Living Standards. 

Personally, I'd like to see us all get behind: 

 * Incubation process.
 * Living standards. 
 * Spec changes must be accompanied by tests.

And that groups we WGs participate in make a best effort to follow the above.

**Comment by annevk** [comment]
I think this is very much worth keeping in mind when reviewing policies, but I don't think tracking this here will help us with that, so closing.
