### ISSUE TITLE
Atomics.waitAsync

### ISSUE THREAD

**Issue by marjakh** [mozilla/standards-positions#433]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Atomics.waitAsync
* Specification or proposal URL: https://tc39.es/proposal-atomics-wait-async/
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1467846

**Comment by annevk** [comment]
cc @lars-t-hansen

**Comment by lars-t-hansen** [comment]
@codehag handles all of that.

**Comment by codehag** [comment]
This is worth prototyping. It introduces a meaningful way for the main thread to interact with blocking concurrent patterns. I will create a PR to reflect this.
