### ISSUE TITLE
@font-face descriptors ascent-override, descent-override and line-gap-override to override font metrics

### ISSUE THREAD

**Issue by xiaochengh** [mozilla/standards-positions#439]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: @font-face descriptors `ascent-override`, `descent-override` and `line-gap-override` to override font metrics
* Specification or proposal URL: https://drafts.csswg.org/css-fonts-4/#font-metrics-override-desc
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

The descriptors are [newly added](https://github.com/w3c/csswg-drafts/pull/5521) into CSS Fonts Level 4. Chromium has already implemented them behind a flag.

**Comment by emilio** [comment]
cc @jfkthame

**Comment by myfonj** [comment]
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1681691

**Comment by xiaochengh** [comment]
Another request for a similar feature `advance-override` was just made (#489). Please merge if needed.

**Comment by jfkthame** [comment]
Mozilla has implemented these, as of Firefox 89 (currently Beta).

@annevk Is there a "correct" way to close this (recording our position as supporting the feature)?

**Comment by annevk** [comment]
We need to determine a position as per https://github.com/mozilla/standards-positions#possible-specification-positions. And then if it's major enough update the Dashboard as per https://github.com/mozilla/standards-positions/blob/main/CONTRIBUTING.md#for-mozillas-subject-matter-experts. I suspect the latter is not applicable and the former is `worth prototyping`? If that matches your thinking we could close this.

**Comment by jfkthame** [comment]
SGTM, thanks.
