### ISSUE TITLE
Top-level await in JS

### ISSUE THREAD

**Issue by syg** [mozilla/standards-positions#444]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Top-level await
* Specification or proposal URL: https://github.com/tc39/proposal-top-level-await
* HTML integration PR: https://github.com/whatwg/html/pull/4352
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1519100
* Mozillians who can provide input (optional): @codehag @jorendorff

### Other information

The TC39 proposal advanced to Stage 3 at the meeting in June, 2019. Chrome is planning to ship it soon, likely in 88.

Interestingly, Node has flipped on the feature flag in V8 for top-level await by default, so it is already shipping for the Node ecosystem: https://github.com/nodejs/node/pull/34558

**Comment by codehag** [comment]
Proposed position: Worth Prototyping.

As per stage 3, we are implementing this. Top level await allows an ergonomic way to write modules with asynchronous behaviour at the top level. On our end, this feature is almost finished. I will make a patch to this effect.
