### ISSUE TITLE
Change click, auxclick, contextmenu to PointerEvent

### ISSUE THREAD

**Issue by liviutinta** [mozilla/standards-positions#455]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: PointerEvents, UIEvents, Html
* Specification or proposal URL:  
  - [PointerEvents pending PR](https://github.com/w3c/pointerevents/pull/317) 
  - [UIEvents merged PR](https://github.com/w3c/uievents/pull/259)
  - [Html pending PR1](https://github.com/whatwg/html/pull/5324)
  - [Html pending PR2](https://github.com/whatwg/html/pull/6126) 
* Mozillians who can provide input (optional): @smaug----  

### Other information
Make “click”, “contextmenu” and “auxlick” instances of PointerEvents (instead of MouseEvents), to allow web apps to identify the source of such events in a multi-pointer environment (with mouse, pen and multitouch capabilities), and utilize fractional coordinates.  No other aspect of these events or their dispatch mechanism would be changed.

(The “dblclick” event remains unchanged because it is [considered](https://github.com/w3c/pointerevents/issues/100#issuecomment-684074963) a legacy event.)

#### Compat study
To better understand compat implications, Chrome [committed](https://lists.w3.org/Archives/Public/public-pointer-events/2019AprJun/0071.html) to experimenting in the wild. Chrome made the change available as an experimental web-platform feature in Sep 2019, started an experiment in Canary in Aug 2020, and gradually expanded the scope of the experiment to Canary, Dev and Beta by Nov 3rd 2020. So far there were no related bug reports.

**Comment by annevk** [comment]
Mozilla is okay with this change, but note that if you did not know this, the HTML PR should not have stated Firefox support and should probably not have been merged.

I suggest we close this as the standard is already changed and this is a very small change anyway.

cc @domenic
