### ISSUE TITLE
Standards Position Request: Readable Byte Streams

### ISSUE THREAD

**Issue by nidhijaju** [mozilla/standards-positions#457]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Readable Byte Streams
* Specification or proposal URL: https://streams.spec.whatwg.org/
Specific Sections:
  - https://streams.spec.whatwg.org/#readable-byte-stream
  - https://streams.spec.whatwg.org/#byob-reader-class
  - https://streams.spec.whatwg.org/#rbs-controller-class
  - https://streams.spec.whatwg.org/#rs-byob-request-class
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
TAG Review: https://github.com/w3ctag/design-reviews/issues/567
Chrome Status Entry: https://chromestatus.com/feature/4535319661641728

**Comment by annevk** [comment]
This seems worth prototyping to me. Especially for I/O you want streams that are have good integration with Typed Arrays. (I also think this has been part of the standard for a long time, it's just that implementations didn't tackle it from the get-go.)
