### ISSUE TITLE
Cross-Origin Opener Policy Reporting API

### ISSUE THREAD

**Issue by camillelamy** [mozilla/standards-positions#460]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Cross-Origin Opener Policy Reporting API
* Specification or proposal URL: https://html.spec.whatwg.org/multipage/origin.html#reporting
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1648450
* Mozillians who can provide input (optional):

**Comment by mozfreddyb** [comment]
I can't recall our implementation status for the Reporting API, but as a drive-by comment, I'd argue this is **worth prototyping**.

We want websites to opt into COOP and similar new isolation features. Giving them useful tools to measure feasibility for their websites seems very reasonable to me.

I'm sure @annevk has an opinion too :)

**Comment by annevk** [comment]
Agreed. A thought I had is that if Chrome makes rapid progress on applying COOP "`same-origin-allow-popups`" by default as was suggested at various points this might obsolete itself.

**Comment by annevk** [comment]
No need for a dashboard entry here so closing this as worth prototyping.
