### ISSUE TITLE
Encrypted Media Extensions - Encryption Scheme support

### ISSUE THREAD

**Issue by SingingTree** [mozilla/standards-positions#467]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Encrypted Media Extensions - Encryption Scheme support
* Specification or proposal URL: https://w3c.github.io/encrypted-media/ (the changes discussed have been merged into draft with https://github.com/w3c/encrypted-media/pull/457)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1610671
* Mozillians who can provide input (optional): bryce (me)

### Other information
This adds a further field to the capabilities passed to the EME API so that implementations can explicitly filter on the encryption scheme used. Specifically, this makes it easier for sites to determine explicit support for the `cbcs` scheme which has been introduced since the initial EME specification. However, being able to query more information means the possibility of higher resolution fingerprinting.

**Comment by martinthomson** [comment]
@SingingTree maybe you can clarify something for me.  It seems to me like enabling cryptographic agility for this is a reasonable thing to do.  In assessing fingerprinting risk what I'm interested in is whether you expect this new capability to be distinguishing in the long run.

If you expect everyone who has EME enabled to eventually gain this new capability - ideally by replacing existing CDMs with ones that support `cbcs` - then the amount of additional, usable fingerprinting entropy is minimal long term.  If this is down to availability of the capability in HDCP, then whether the capability is present exposes information about the devices that are present, which would be more identifying.  Either way, if this is no more identifying than enumerating the CDMs that are present, then the fingerprinting risk is probably not significant.

https://pr-preview.s3.amazonaws.com/w3c/encrypted-media/457/79d5a58...joeyparrish:bca19ac.html#privacy-fingerprinting shows that the change didn't update the fingerprinting section of the document.  I can't tell if that was deliberate.

**Comment by SingingTree** [comment]
@martinthomson, thanks for the quick follow up. At this point in time I would expect the amount of entropy exposed to be low and would not expect new values to be added very often. More concretely, if we expose this, all supported Fx versions will already have support for `cenc` and `cbcs` so the fingerprinting available will boil down to detection the version when we flipped the pref. The spec also suggests a separate key for cbcs-1-9, which we do not yet implement in Gecko ([tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1683737)). This is an example of where if we add such a key later it could expose a more information, but again this would boil down to exposing something similar to version.

This should not expose anything related to devices present. There is no hardware requirement or gating on these encryption schemes, simply if the software in the CDM has implemented the scheme and if it's been plumped in Gecko. I think at most it will expose a Gecko version and a CDM version.

**Comment by martinthomson** [comment]
Thanks @SingingTree.  That confirms my initial intuition.  On that basis, I think we can say that this is OK.  As this is a very small change - it's just implementing good API hygiene - I wonder if we really need to get this on the dashboard at all.  We could mark it has "worth prototyping" on the basis that cryptographic agility is good, but I'm inclined to just close this.

**Comment by nils-ohlmeier** [comment]
I agree with @martinthomson that also don't see this small extension worth putting onto the dashboard.

For future extensions of existing APIs the question is where to get expertise from different Mozilla folks before shipping it?

**Comment by hsivonen** [comment]
On the basis that the discoverable values will correlate with CDM versions and, therefore, only be identifying when the whole installed base hasn't yet updated the CDM, I think it's OK to expose this.

**Comment by SingingTree** [comment]
Thanks all for the feedback, I'll get a patch ready for gecko. Please let me know if there's any other steps I should take prior to landing.

**Comment by annevk** [comment]
@nils-ohlmeier I think this is a fine place, including for smaller questions. We just won't update the dashboard. (We've also started doing this for smaller questions from non-Mozillians.)
