### ISSUE TITLE
allow sftp in safelisted schema for registerProtocolHandler()

### ISSUE THREAD

**Issue by vapier** [mozilla/standards-positions#468]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTML
* Specification or proposal URL:
  * whatwg/html#6254
  * https://tools.ietf.org/html/draft-ietf-secsh-scp-sftp-ssh-uri-04#page-5
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by annevk** [comment]
While it's in https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml it doesn't appear to be standardized. That makes me think it's not worth the effort.

**Comment by martinthomson** [comment]
It would be easier to assess these if there was a set of principles that we might employ to determine what is OK and what is not.  A reference to an unpublished draft from 2006 isn't exactly a strong signal that this is good.  I see nothing in HTML that would guide us in determining if this is OK.  That `ssh` is listed is good, but that's cargo-culting, not an application of principles.

**Comment by annevk** [comment]
HTML defers that question to implementer consensus at the moment as it's largely a UI question.

**Comment by annevk** [comment]
Let's merge this into #513.
