### ISSUE TITLE
Storage Buckets API

### ISSUE THREAD

**Issue by ayuishii** [mozilla/standards-positions#475]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Storage Buckets API
* Specification or proposal URL: https://github.com/WICG/storage-buckets/blob/gh-pages/explainer.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @annevk @asutherland 

### Other information
This feature is in early stages of prototyping in Google Chrome and currently going through an early [TAG design review](https://github.com/w3ctag/design-reviews/issues/562). This has been presented in TPAC 2019 ([discussion notes](https://docs.google.com/document/d/1eBWhY91nUfdT2mys3GaNKX4fKPei79Wk-KlWHYffbAA/)) and TPAC 2020 ([minutes](https://www.w3.org/2020/10/29-storage-buckets-minutes.html)). 

Related:
Multiple buckets issue: https://github.com/whatwg/storage/issues/2

**Comment by asutherland** [comment]
I think it makes sense to mark this as `worth prototyping`.

**Comment by annevk** [comment]
@asutherland do you want to create a PR for this?

**Comment by asutherland** [comment]
I'd like to see where the discussion in https://github.com/WICG/storage-buckets/pull/36 and any follow-ups ends up first.
