### ISSUE TITLE
Storage Foundation API

### ISSUE THREAD

**Issue by fivedots** [mozilla/standards-positions#481]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Storage Foundation API
* Specification or proposal URL: https://github.com/fivedots/storage-foundation-api-explainer
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

This feature is being prototype in Google Chrome and had gone through an early [TAG design review](https://github.com/w3ctag/design-reviews/issues/566). It has been presented TPAC 2020 ([WebApps WG minutes](https://www.w3.org/2020/10/19-webapps-minutes.html), [breakout](https://www.w3.org/2020/10/TPAC/breakout-schedule.html#nativeio)).

**Comment by annevk** [comment]
While in principle it seems reasonable to have a low-level storage API, https://github.com/fivedots/storage-foundation-api-explainer/issues/4 and https://github.com/fivedots/storage-foundation-api-explainer/issues/8 are problematic and I don't think it's an acceptable outcome for the web platform to have that many ways to work with files. (I know there is some hope for removal of File and Directory Entries API, but that does not seem sufficient, if it even works out.) I think this really needs a more holistic approach to what a filesystem API might look like that is both nice to work with, performant, and appreciative of the status quo across browsers.

**Comment by svoisen** [comment]
Hi @annevk @asutherland  — I just wanted to make you aware of a position of support for Storage Foundation that we (at Adobe) posted: https://github.com/WICG/proposals/issues/10#issuecomment-804145429

We understand that there is some concern about the splintering of APIs and multiple ways of working with files. At the same time, we also need the performance properties it provides, which are presently lacking in existing solutions or File System Access. I'm hoping that we might be able to nudge some more discussion on a solution that would be acceptable to all.

**Comment by birtles** [comment]
Former Mozilla engineer @jlongster just released [`absurd-sql`](https://jlongster.com/future-sql-web) and suggests this API (or presumably something of its ilk) is a necessary piece for achieving database performance that is more competitive with native.
