### ISSUE TITLE
mapping a <source>'s width/height attributes to width/height/aspect-ratio CSS properties on the <img> in a <picture>

### ISSUE THREAD

**Issue by cbiesinger** [mozilla/standards-positions#485]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: mapping a `<source>`'s width/height attributes to width/height/aspect-ratio CSS properties on the `<img>` in a `<picture>`
* Specification or proposal URL: https://github.com/whatwg/html/pull/5894
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): Boris Chiou

### Other information
This extends a similar proposal on <img> (https://github.com/whatwg/html/pull/6032) to `<picture>`

**Comment by emilio** [comment]
I think this is a weird precedent, but probably worth it, see my comments in the PR. cc @annevk @smaug---- in case they have any objections, otherwise I think we should at least flag it as worth prototyping.

**Comment by annevk** [comment]
Did OP mean to mention https://github.com/whatwg/html/pull/5894? I cannot find comments from @emilio in 6032. If the only weirdness is that the data is on another element and that's new for the default style sheet I don't think I have a problem with it. There's plenty of precedent for that pattern elsewhere. (It's a little worrying that the rendering section isn't very explicit about attribute mutations, but hopefully there's tests for that...)

**Comment by cbiesinger** [comment]
Yes sorry, that's the one I meant.

**Comment by dougwl** [comment]
Just linking the Bugzilla thread here, for more information:

https://bugzilla.mozilla.org/show_bug.cgi?id=1694741

**Comment by annevk** [comment]
Let's close this as worth prototyping without dashboard entry.
