### ISSUE TITLE
URL: protocol setter needs to be more restrictive around file

### ISSUE THREAD

**Issue by ricea** [mozilla/standards-positions#486]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: URL: protocol setter needs to be more restrictive around file
* Specification or proposal URL: https://url.spec.whatwg.org/#scheme-state step 2.1.3 and 2.1.4 (originally added in https://github.com/whatwg/url/pull/269)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1347459
* Mozillians who can provide input (optional): annevk

### Other information

The standard change was made in 2017, but Blink and Firefox haven't implemented it. I am planning to implement it in Blink, see https://crbug.com/701685. The Blink process requires me to get a position from Mozilla. Sorry for bothering you with such a small change.

**Comment by annevk** [comment]
That sounds great, thanks.

Not entirely sure whether we want to put small changes like this on the dashboard though. @martinthomson thoughts?

**Comment by martinthomson** [comment]
Yeah, let's just tell Adam that this is "worth prototyping", but we don't need to put this on the dashboard.

**Comment by annevk** [comment]
Adam, let us know if that's not enough, thanks again for tackling this!
