### ISSUE TITLE
@font-face descriptor advance-override

### ISSUE THREAD

**Issue by xiaochengh** [mozilla/standards-positions#489]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: @font-face descriptor `advance-override`
* Specification or proposal URL: https://drafts.csswg.org/css-fonts-5/#descdef-font-face-advance-override
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

The descriptor is [newly added](https://github.com/w3c/csswg-drafts/pull/5991) into CSS Fonts Level 5. Chromium has already implemented it behind a flag.

This feature was proposed together with `ascent-override`, `descent-override` and `line-gap-override` descriptors. So please merge this request into #439 if appropriate.

**Comment by annevk** [comment]
cc @jfkthame

**Comment by jfkthame** [comment]
Considered in isolation, I cannot support this for the time being. I agree with what fantasai has said in recent CSSWG discussions (e.g. [in the github issue here](https://github.com/w3c/csswg-drafts/issues/5983#issuecomment-789898142)) that it would be harmful to ship this without *also* shipping (at the same time, or even earlier) a [glyph scaling feature](https://github.com/w3c/csswg-drafts/issues/6075), which will provide a typographically superior solution to many of the potential use cases for this descriptor.

**Comment by drott** [comment]
@jfkthame is this resolved? We would like to ship `size-adjust` which I believe is the glyph scaling feature you have in mind. advance-override is no longer a priority.

**Comment by jfkthame** [comment]
I think we can just close this (as "abandoned" or something like that) for now -- noting that `advance-override` has been removed from the draft spec. If at some point it gets revived, we'll need to consider our position in the light of whatever new use-cases and proposed spec may come up.

(Regarding `size-adjust`, we're intending to support this, and have it implemented behind a pref -- enabled in Nightly -- at this point. I'm not sure if there's a clear consensus yet on whether it's ready to ship?)

**Comment by drott** [comment]
We take it that [sending out the intent to prototype for `glyph-scale-factor`](https://groups.google.com/g/mozilla.dev.platform/c/joBc4SoTOPc/m/Mwjr06tcAgAJ), now called `size-adjust` descriptor means that you consider this functionality worth prototyping. We thought it may be okay to reuse this request, please let us know if you would rather open a new position request for that.

**Comment by annevk** [comment]
I can reopen this to let @jfkthame assess that, but generally a new issue would be better if it's a separate feature.

**Comment by jfkthame** [comment]
For `size-adjust`, yes, our position would be `worth prototyping`.
