### ISSUE TITLE
WebAssembly SIMD

### ISSUE THREAD

**Issue by ngzhian** [mozilla/standards-positions#491]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebAssembly SIMD
* Specification or proposal URL: https://github.com/WebAssembly/simd
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): Lars T Hansen

### Other information
Blink Intent to Ship  https://groups.google.com/a/chromium.org/g/blink-dev/c/Ks2iWmi32MM

**Comment by annevk** [comment]
cc @lars-t-hansen

**Comment by lars-t-hansen** [comment]
We support this and will be shipping it, initially for Intel CPUs, almost certainly in FF89; ARM64 support to follow, likely FF90.  Intent-to-ship will be sent out soonish.

**Comment by ngzhian** [comment]
Thanks Lars! I've updated the Blink Intent to Ship thread with your comment.

**Comment by martinthomson** [comment]
@lars-t-hansen, is it too much to ask for you to create a pull request with a positive statement?  We don't usually record shipping plans, but something more general, like "this is good for the web because <it goes faster with SIMD>" or something along those lines.

**Comment by lars-t-hansen** [comment]
I can do that.  By EOW is plausible.
