### ISSUE TITLE
Honor media HTML attribute for link icon

### ISSUE THREAD

**Issue by beaufortfrancois** [mozilla/standards-positions#495]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTML spec
* Specification or proposal URL: https://html.spec.whatwg.org/multipage/semantics.html#processing-the-media-attribute
* Discussion: https://github.com/whatwg/html/issues/6408

### Other information

Browsers don’t currently honor the media attribute for link[rel="icon"] even though [the HTML specification says](https://github.com/whatwg/html/issues/6408#issuecomment-783507998) they should.

> Icons could be auditory icons, visual icons, or other kinds of icons. If multiple icons are provided, the user agent must select the most appropriate icon according to the type, media, and sizes attributes.

Members of the Google Chrome team are thinking of honoring the link element’s "media" attribute for link[rel="icon"] so that web developers can define multiple equally appropriate icons based on a media query (dark and light modes for instance). The last one that matches will be picked.

**Comment by annevk** [comment]
@beaufortfrancois if you take the definition literally, it's not just a decision you make when fetching. So resizing the window would have to change the icon. Is that what you are planning on doing? If not, some changes might be needed here. Either way it seems somewhat reasonable to support this.

cc @emilio

**Comment by beaufortfrancois** [comment]
I'm not sure the spec should define which media features should affect the favicon displayed in the browser tab.

As noted in the HTML spec as well,
> User agents are not required to update icons when the list of icons changes, but are encouraged to do so.

**Comment by domenic** [comment]
Wait, what is this issue about then, if not the favicon displayed in the browser tab? What do you think the spec is taking about, if not that?

**Comment by annevk** [comment]
I don't think "matches the environment" has wiggle room to ignore certain media features.

I also don't think the list of icons actually changes in this case, but the processing model is not as clear as it could be.

**Comment by beaufortfrancois** [comment]
> @beaufortfrancois if you take the definition literally, it's not just a decision you make when fetching. So resizing the window would have to change the icon. Is that what you are planning on doing? If not, some changes might be needed here. Either way it seems somewhat reasonable to support this.

Indeed, Chrome will update icons when media features change (e.g. dark/light mode change, viewport resize).

**Comment by annevk** [comment]
Thanks for clarifying. I think this is worth prototyping, but I'm not entirely sure it's worth adding it to the dashboard...

**Comment by beaufortfrancois** [comment]
Which dashboard sorry?

**Comment by annevk** [comment]
https://mozilla.github.io/standards-positions/. More of a thing we need to sort out with requests for positions on relatively minor features.

**Comment by beaufortfrancois** [comment]
FYI I've just sent an intent to ship at https://groups.google.com/a/chromium.org/g/blink-dev/c/OwUSsHWokpA

**Comment by annevk** [comment]
I'll close this next week. If anyone doesn't think this is worth prototyping, now would be a good time to weigh in.
