### ISSUE TITLE
CSP's `prefetch-src` directive.

### ISSUE THREAD

**Issue by mikewest** [mozilla/standards-positions#496]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSP's `prefetch-src` directive.
* Specification or proposal URL: https://w3c.github.io/webappsec-csp/#directive-prefetch-src
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1457204
* Mozillians who can provide input (optional): @annevk, @dveditz

### Other information

Hello, friendly Mozillians! Several years ago, we hammered out a `prefetch-src` directive in https://github.com/w3c/webappsec-csp/issues/107 which aimed to give developers control over prefetched/prerendered resources. After that discussion, we [landed the directive](https://github.com/w3c/webappsec-csp/pull/283) in both the spec and behind a flag in Chrome. And then life happened and I never brought it out from behind the flag.

This is low-priority, but I'd like to get it out the door if y'all are still on board. WDYT?

**Comment by annevk** [comment]
This still seems worth prototyping. I don't see us supporting `prerender` in its current form, but `prefetch` is still useful for same-origin navigation and subresources of subsequent same-origin documents.

**Comment by mikewest** [comment]
Great, thanks!

I'm not sure this is an interesting-enough feature to put on y'all's dashboard, but I want to make sure to dot-i's and cross-t's before shipping it. If "worth prototyping" is where you end up, I'm happy for y'all to close this out.

**Comment by annevk** [comment]
Right, we don't have an exact process for this, but I'm inclined to wait a couple days to ensure enough people have had a chance to see it and then close it.

**Comment by annevk** [comment]
Yeah, it's probably worth stating that in the bug.

I'll close this per my earlier comment.
