### ISSUE TITLE
TC39 Proposal Temporal

### ISSUE THREAD

**Issue by Jxck** [mozilla/standards-positions#498]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: TC39 Proposal Temporal
* Specification or proposal URL: https://github.com/tc39/proposal-temporal
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1519167
* Mozillians who can provide input (optional): N/A

### Other information

[Currently Stage 3](https://github.com/tc39/proposals/commit/253a4ae237a30549849c49b4062972c4ee75e5b4)

**Comment by annevk** [comment]
Any particular reason you are wondering about Mozilla's position here?

As a general rule, we'd object to entering Stage 1/2/3 if we would not be okay with a TC39 proposal. There might well be an exception to that rule if we missed a meeting or some such or overlooked an important issue, but I would expect that to be rather exceptional.

**Comment by Jxck** [comment]
IIUC, mozilla has a choice not to implement even if its on Stage 4.
And explicit position on MSP will help developer who interested in Key features like Temporal but not familiar with tc39 meeting/standardization process.

**Comment by annevk** [comment]
standards-positions is not about product priorities. So even if we take an explicit position here (and to be clear, this specific thing is worth prototyping), that doesn't mean it will be implemented anytime soon.

**Comment by Jxck** [comment]
I'm not intended to ask that.
Just asking a position from mozilla.
(And now I found its Green one)

**Comment by Jxck** [comment]
FYI for @annevk 

https://groups.google.com/a/chromium.org/g/blink-dev/c/pzy_Z3AwmaY/m/FeXzN3hnAwAJ

> Also, see https://github.com/mozilla/standards-positions/issues/498#issuecomment-796586704 for evidence that Mozilla considers all Stage 3 TC39 proposals to be "positive".

**Comment by annevk** [comment]
Yeah, I think that is fine. Closing this as worth prototyping.

**Comment by captainbrosset** [comment]
There seems to be some movement in the implementation of Temporal in Firefox. Should this be marked as `position:positive` then? @zcorpan?
