### ISSUE TITLE
Set of possible positions seems too narrow

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#51]
At least for PRs against WHATWG standards we need a stronger signal than "participating" gives. We need something that indicates support. That's not a commitment to implement, but it is an endorsement of the feature that allows others to go ahead and implement it, to add tests to web-platform-tests, etc.

My initial hope for this repository was that we could have something where one could raise a standards-related issue with Mozilla stakeholders and determine a position on that issue. The way it's structured now doesn't really lend itself to that.

**Comment by dbaron** [comment]
Some prior history here is in #16 and #41, although a bunch of it was in email threads.  I'd be happy to get rid of `participating`, which I think is a statement of fact rather than a position.  If I were replacing it I'd probably add `important` and `neutral`.

**Comment by tantek** [comment]
I agree with re-emphasizing @annevk's use-case of "determine a [Mozilla] position on that issue". Also agreed that "participating" is more of a statement of fact (whether in WG membership, spec editorship, or spec issues/pull requests).

I've also re-reviewed the #16 and #41 issues and related threads for nuances we may have overlooked.

> I'd probably add important and neutral.

I think "important" is too vague (relative to what?), and "neutral" doesn't say anything (enough?)

Counterproposal: add non-harmful, worth-prototyping

I believe this keeps with having mutually exclusive positions in rough time / positivity order:

We have no position yet:
* under consideration - (but we're looking at it)
* defer - (we have postponed looking at it - not looking at it currently)

We have a position:
* harmful - Mozilla considers this specification to be harmful in its current state.
* non-harmful - (we've looked at it enough to determine that this spec is likely not harmful in its current state, but we're not sure of actual utility vs cost to implement, or whether this is a good enough approach to the problem space etc.)
* worth-prototyping - this indicates conceptual support (more than not harmful, we think the spec is at least good enough to be worthy of implementers prototyping to incubate/iterate, but not saying whether we are or are not. Actual state of whether *we* prototype/implement is separately covered by Intent to Experiment, Intent to Implement, Intent to Ship etc.) we may actually prototype, and then find there are bad enough problems to change state to "harmful" for example. or we may find that the spec is awkward/subpotimal but not actually harmful and change state to "non-harmful".

Feel free to bikeshed the names, but those two conceptual additions (non-harming, worth-prototyping), I believe provide sufficient additional granularity to weakly or strongly positively communicate our positions.

IMO "worth-prototyping" captures @annevk's specific use-case of "indicates support. That's not a commitment to implement, but it is an endorsement of the feature that allows others to go ahead and implement it, to add tests to web-platform-tests"

And "non-harmful" indicates we are ok with (don't object to) e.g. a "PR against WHATWG standards", yet we are not endorsing it, while not blocking others from implementing or testing themselves.

**Comment by stpeter** [comment]
I like what @tantek has proposed. Do we feel the need for one more position to capture what @dbaron called `important` (as in, "we think this is needed to address a critical gap and we will actively contribute to the standardization effort")?

**Comment by ekr** [comment]
I think that's pretty important to capture. I mean, there's a pretty big
gap between TLS 1.3, where we're spending a lot of effort and plan to
deploy shortly, and say, Expect-CT

**Comment by dbaron** [comment]
I'm fine with replacing `participating` with the set of `non-harmful`, `worth-prototyping`, and `important`.

**Comment by annevk** [comment]
Maybe instead of "important" we could use "are-implementing"?

**Comment by ekr** [comment]
On Fri, Feb 16, 2018 at 2:59 AM, Anne van Kesteren <notifications@github.com
> wrote:

> Maybe instead of "important" we could use "are-implementing"?
>

I would prefer not to conflate these. There are things we think are
important we might not have started yet and things we think are not very
important that we are doing anyway

**Comment by annevk** [comment]
I was trying to address @tantek's concern about "important" not being very clear, but I don't care strongly and @dbaron's proposal is a huge improvement over the status quo so maybe we should just go with that and bikeshed "important" in a new issue if someone still feels strongly.

**Comment by ekr** [comment]
WFM. I am fine with "important"

On Fri, Feb 16, 2018 at 6:21 AM, Anne van Kesteren <notifications@github.com

**Comment by tantek** [comment]
I can live with "important" so we can land the rest of this, and defer bikeshedding "important" to a new issue which can collect examples to inform how to clarify it.
Also agreed with @ekr about not conflating implementation. Again I'd like to keep that orthogonal to status, and continue using our existing "Intent to Experiment/Implement/Ship" mechanisms for that.

**Comment by dbaron** [comment]
OK, I'm working on a PR to do this.  The interesting piece of that is the descriptions, which I've currently drafted as:

- `important` - This specification is important to Mozilla.
- `worth prototyping` - Mozilla sees this specification as likely enough to be important that it is worth prototyping and iterating on.
- `non-harmful` - Mozilla does not see this specification as harmful, but is not convinced that it is worth working on.

I'd welcome suggestions or improvements to these descriptions.

**Comment by dbaron** [comment]
OK, revised based on those suggestions to:
- `important` - This specification is conceptually good and is important to Mozilla.
- `worth prototyping` - Mozilla sees this specification as conceptually good, and worth prototyping, getting feedback on its value, and iterating.
- `non-harmful` - Mozilla does not see this specification as harmful, but is not convinced that it is a good approach or worth working on.

**Comment by stpeter** [comment]
Do we need to add a hyphen (i.e., `worth-prototyping`)?

**Comment by dbaron** [comment]
I was trying to just use English; I suppose in that style `non-harmful` could also be `not harmful`, but I don't think it matters.  I'd note the existing `under consideration` is also two words.

**Comment by stpeter** [comment]
Right. As you were, sorry about the noise.
