### ISSUE TITLE
contain-intrinsic-size auto & longhands

### ISSUE THREAD

**Issue by cbiesinger** [mozilla/standards-positions#512]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: contain-intrinsic-size (auto value, and the contain-intrinsic-size-width / height properties)
* Specification or proposal URL:  https://drafts.csswg.org/css-sizing-4/#intrinsic-size-override
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1597529
* Mozillians who can provide input (optional): @dholbert 

### Other information
Chrome would like to implement these additions to the contain-intrinsic-size spec and is seeking Mozilla's position on these.

**Comment by dholbert** [comment]
In general the feature seems reasonable, but I'm a little concerned about the hand-waviness around "last remembered size".  I filed https://github.com/w3c/csswg-drafts/issues/6220 to get spec clarification there.

**Comment by cbiesinger** [comment]
FYI Blink is now shipping the longhands in canary (not the auto handling yet)

**Comment by cbiesinger** [comment]
@dholbert just to check, are you happy with the latest version of the spec?

**Comment by dholbert** [comment]
Yes, the latest version of the spec looks reasonable to me (now that the above-mentioned "last remembered size" issue has been resolved).  Thanks!
