### ISSUE TITLE
Admin: allow read-only access for some collaboration

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#52]
Would be great to if we could create a read-only access group that would allow folks like @annevk and myself to assign issues to people. This can be done via "Settings" -> "Collaborators & teams", and adding us there with "read-only" access. 

Other folks who want to be included in that group should respond here. Hopefully, by assigning issues to people, we might be able to get some things moving a bit more quickly ... fingers crossed!🤞

**Comment by annevk** [comment]
I think we should give write access to Mozillians but restrict the master branch to the owners. That would simplify a bunch of things and not put as much strain on a few people.

**Comment by annevk** [comment]
This should now be the case.
