### ISSUE TITLE
Hide shipped-and-finished standards

### ISSUE THREAD

**Issue by saschanaz** [mozilla/standards-positions#524]
It's a bit confusing to see things like `<template>` and bigint are still in the page when all engines ship them and no significant changes are expected there. Probably good to mark them as shipped and hide them by default.

Maybe dead standards e.g. HTML imports should also be hidden.

**Comment by saschanaz** [comment]
>Interesting, what makes it confusing?

Those make me think 1) those are not finished, or 2) Mozilla still want to say something for them.

> What we ship doesn't necessarily correlate with what we think about it. DRM comes to mind.

Yeah, but we haven't been against the idea for <template> nor for bigint, right?

> Positions on abandoned or even shipped specifications still seem relevant in the development of new specifications as hopefully those new efforts learn from past efforts.

Agreed, so "hide" by default but not "remove", because I think the main interest there still is about emerging standards.

**Comment by zcorpan** [comment]
I think we shouldn't hide them, or spend time discussing which items should be hidden. It seems better to make it easy to find any issue where we have set a position, IMO.
