### ISSUE TITLE
Standards position for TC39 Stage 3 Proposals

### ISSUE THREAD

**Issue by codehag** [mozilla/standards-positions#527]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: JavaScript
* Specification or proposal URL: https://tc39.es/ecma262
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

The way we have been signalling our position on all upcoming TC39 proposals is through my participation on TC39. I publicly state which proposals are worth prototyping by allowing a proposal to move to stage 3, and these decisions are reviewed by the SpiderMonkey team at large, the internationalization team, and with other internal mozilla folks if it touches other parts of the browser. Most of the time we are looking at smaller adjustments to the language, which, if all were posted here, might be a lot, and the engagement on smaller proposals would primarily be me restating our position from TC39. Anything we do allow to stage 3 is something we intend to prototype.

The question I have is, what is the best way to reflect this on mozilla standards positions?  I spoke with @tantek -- and he suggested that we create a meta-position covering all of tc39 stage 3 as "worth prototyping", with a [link to our ongoing work on stage 3 proposals](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1435811&hide_resolved=1). Stage 2 proposals, if they are complex and need further input, can get their own position as necessary (which is what has been happening). 

The main change here is a new standards position on TC39 stage 3 proposals being "worth prototyping". 

Is this a good solution?

**Comment by annevk** [comment]
FWIW, I think that's reasonable. I'd mainly expect to see further discussion on proposals that have privacy/security impact or require host integration. New syntax, standard library features, etc. seem adequately covered by TC39 itself and the SpiderMonkey team.

**Comment by cwilso** [comment]
Thanks.  I expect we will wrap this in to Chromium's process, btw, so we will stop spamming you with requests here for specifications that are already stage 3+.

**Comment by annevk** [comment]
https://mozilla.github.io/standards-positions/#tc39-stage-3
