### ISSUE TITLE
Window Controls Overlay

### ISSUE THREAD

**Issue by diekus** [mozilla/standards-positions#529]
## Request for Mozilla Position on an Window Controls Overlay
* Specification Title: Window Controls Overlay
* Specification or proposal URL: https://github.com/WICG/window-controls-overlay/blob/main/explainer.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

Allows a developer to customize part of the title bar that is not covered by the window controls overlay (web app menu, maximize/restore, minimize, close). It consists of 4 parts:
•	(JS) New object on the window.navigator.windowControlsOverlay. 
•	(CSS) New Environmental variables: (titlebar-area-{x/y/width/height}). 
•	(CSS) standardisation of -webkit-app-region:drag and -webkit-app-region: no-drag.
•	(Manifest) addition of “display-override” member

Looking forward to hearing your ideas.

**Comment by diekus** [comment]
👋🏼 Holaaa! Just pinging since it feels lonely here!

**Comment by martinthomson** [comment]
Hi @diekus, Mozilla is currently not investing in PWAs.  That's the reason for the delay and for why we're going to have to `defer` this request.

**Comment by zDaleZ** [comment]
Just a gentle nudge, now that Firefox supports desktop PWAs on Windows, would you be open to revisiting this?

**Comment by GamerGirlandCo** [comment]
> Just a gentle nudge, now that Firefox supports desktop PWAs on Windows, would you be open to revisiting this?

unfortunately, they're investing more into their slacktivism campaigns than actually making the web better ¯\\\_(ツ)_/¯
