### ISSUE TITLE
UA-CH API updates

### ISSUE THREAD

**Issue by miketaylr** [mozilla/standards-positions#533]
## Request for Mozilla Position on an Emerging Web Specification

Howdy all.

I'm writing to request a position on some recent API updates to the 
User-Agent Client Hints API. There's a blink-dev I2P on the topic at [1], but I'll repeat the updates 
here:

1. Sec-CH-UA-Bitness: adds a new high-entropy hint to expose the OS 
bitness, which may be combined with Sec-CH-UA-Arch to provide optimized 
binaries for download, for example.
Spec PR: https://github.com/WICG/ua-client-hints/pull/210.

2. Make Sec-CH-UA-Platform a low-entropy hint: OS is passively 
observable at the TCP level anyways, so we plan to change this to be 
low-entropy and send as a default header (similar to Sec-CH-UA and 
Sec-CH-UA-Mobile).
Spec PR: https://github.com/WICG/ua-client-hints/pull/221

3. Include low-entropy hints by default in UADataValues (returned by 
getHighEntropyValues()). If a hint moves from high to low-entropy, this 
future proofs any code relying on it.
Spec PR: https://github.com/WICG/ua-client-hints/pull/226

4. Add a toJSON method to NavigatorUAData’s IDL. Technically a bugfix, 
but it is an API change (instead of returning {}, 
`JSON.stringify(navigator.userAgentData))` will now be useful)
Spec PR: https://github.com/WICG/ua-client-hints/pull/228

[1]  <https://groups.google.com/a/chromium.org/g/blink-dev/c/dafizBGwWMw/m/72l-1zm6AAAJ> 

* Specification Title: User-Agent Client Hints
* Specification or proposal URL: https://wicg.github.io/ua-client-hints/
* Mozillians who can provide input (optional): 

### Other information

The API was previous reviewed @ https://github.com/mozilla/standards-positions/issues/202 (https://mozilla.github.io/standards-positions/#ua-client-hints)

**Comment by martinthomson** [comment]
Hi Mike,

Our existing position on UA client hints still applies here.  Asking us on items at this fine level of detail isn't really necessary.  We'd prefer if you continue discussing changes to the proposal on its repository, reaching out to people at Mozilla as appropriate.

**Comment by miketaylr** [comment]
Sounds good, thanks @martinthomson.
