### ISSUE TITLE
EME MediaKeySession Closed Reason

### ISSUE THREAD

**Issue by xhwang-chromium** [mozilla/standards-positions#537]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: EME MediaKeySession Closed Reason
* Specification or proposal URL:
  * https://github.com/w3c/encrypted-media/issues/473
  * https://github.com/w3c/encrypted-media/pull/487
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): Paul Adenot, Bryce Van Dyk

### Other information

The current EME spec says "the CDM may close a session at any point, such as when the session is no longer needed or when system resources are lost". However, there's not way to specify the exact reason for session closure. In some cases, this is part of normal user flow, e.g. user close laptop lid to put the device into sleep mode, where the player should resume playback. In some other cases, this is due to some unrecoverable fatal error.

This proposal updates the `closed` attribute on MediaKeySession to provide a MediaKeySessionClosedReason so that the JavaScript player can handle session closure differently based on the reasons.

**Comment by annevk** [comment]
cc @padenot @SingingTree

**Comment by xhwang-chromium** [comment]
Kindly ping. Thanks!!!

**Comment by SingingTree** [comment]
This looks okay to me from a technical perspective. I assume the list of enumerated value isn't intended to grow and everything there should cover anticipated use cases. I don't do a lot of spec language specific parsing, so will leave concerns around language used to other Mozillians.

**Comment by martinthomson** [comment]
I've reviewed the proposal and some of the discussion.  I'm not an expert here, but everything seems reasonable.  Unless there is something that I can't see that would result in security problems or user disempowerment (...), I see no reason to oppose this.  We can mark this as "non-harmful" on the basis of that (if someone closer to this wants to argue for "worth prototyping", I see no reason not to say that too, but I'm not reading that level of enthusiasm from [this comment](https://github.com/mozilla/standards-positions/issues/537#issuecomment-879190957)).

This doesn't really rise to the level of features we want to track on the dashboard, so if people are OK with our position just being stated here, we can close this issue.

**Comment by xhwang-chromium** [comment]
Thank you Bryce and Martin for the comments! I wonder how we can move forward and close this issue?

**Comment by annevk** [comment]
You can consider it non-harmful per mt's comment and the lack of further comments. I'll close it now.
