### ISSUE TITLE
RFP: Signature-based SRI

### ISSUE THREAD

**Issue by mikewest** [mozilla/standards-positions#54]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Signature-based Resource Loading Restrictions
* Specification or proposal URL: https://github.com/mikewest/signature-based-sri

### Other information

There's a discussion starting at https://lists.w3.org/Archives/Public/public-webappsec/2017Jun/0000.html that's quite relevant. @sleevi's comments at https://lists.w3.org/Archives/Public/public-webappsec/2017Jun/0004.html are particularly intriguing.

You'll also probably find the TAG review discussion at https://github.com/w3ctag/design-reviews/issues/186 interesting, as well as the (sparse) minutes from TPAC last year (with @dveditz, @tanvihacks, and @ckerschb in attendance): https://www.w3.org/2017/11/07-webappsec-minutes.html#item04.

**Comment by mozfreddyb** [comment]
I kicked off a thread w/ the wider seceng team (including @martinthomson and @franziskuskiefer) last August, here's a brief summary of reactions, I've received:

- we're concerned the lack of progressive loading will hurt long term
- it's not clear that this mechanism will materially help the web except very few large content providers

For now, we'll be watching.

**Comment by martinthomson** [comment]
I think that this proposal is dead and we can close this issue.

**Comment by mikewest** [comment]
I still want to pursue this at some point, but it's nowhere on my radar at the moment. Let's close it out, and I'll reopen it if it bubbles back up. :)
