### ISSUE TITLE
CSS Module Scripts

### ISSUE THREAD

**Issue by dandclark** [mozilla/standards-positions#541]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Module Scripts
* Specification or proposal URL:  [Explainer](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md), [HTML PR](https://github.com/whatwg/html/pull/4898/)
* Mozillians who can provide input (optional): @annevk 

### Other information

This proposal has already been in discussion for a while now (long thread [here](https://github.com/WICG/webcomponents/issues/759), see also the [TAG review](https://github.com/w3ctag/design-reviews/issues/405)), but I realized we don't have a mozilla/standards-positions entry on it yet so I think it would be useful to get an official position.

Landing the CSS Module Script HTML Spec PR is currently blocked on resolution of an [open issue](https://github.com/tc39/proposal-import-assertions/pull/111) in the import assertions TC39 proposal. However import assertions is at Stage 3 so that proposal is unlikely to undergo significant changes.

**Comment by annevk** [comment]
I'm not sure I understand your last paragraph. It seems to me those integration concerns need to be sorted, no? Including what kind of host hook to provide.

Do you recall if we ever discussed the identifier name? Do we want to specifically assert it's CSS or is stylesheet or some such sufficient?

**Comment by dandclark** [comment]
@annevk Sorry, that paragraph was too vague. I agree that the integration concerns and the shape of the host hooks need to be settled before landing the HTML spec change. The import assertion proposal champions are joining an SES call this Wednesday to hopefully make some progress in that area.

I meant that most of the basic behavior of the proposal as observed by developers is unlikely to change much. For example, the fact that the `import` gives you a CSSStyleSheet, and the use of the import assertions syntax to convey the expected module type is unlikely to change, in my estimation, even if details about spec integration and behavior of undefined types need to be sorted out.

Regarding the identifier name, my understanding is that there was general agreement on using "css" as the type name, as in:
```js
import styleSheet from "./styles.css" assert { type: "css" };
```
This was what I used in my [slides](https://onedrive.live.com/edit.aspx?resid=3C830C8020C680D9!491311&ithint=file%2cpptx&authkey=!ALofG5li5Ywr-LU) (specifically, slide 7) in last year's TPAC discussion on the topic ([notes here](https://www.w3.org/2020/10/29-components-minutes.html)), and I don't recall disagreement on that point at the time. Happy to discuss alternatives though.

I like "css" because it's short and the use of the acronym would align nicely with "json" for JSON modules and maybe "html" someday:
```js
import styleSheet from "./styles.css" assert { type: "css" };
import myJson from "./data.json" assert { type: "json" };
import doc from "./content.html" assert { type: "html" };
```

**Comment by annevk** [comment]
Thanks, provided the details are settled, I would recommend we mark this as worth prototyping.

**Comment by annevk** [comment]
Closing this as per the previous comment.
