### ISSUE TITLE
Request for Position - Unique ID for PWAs

### ISSUE THREAD

**Issue by philloooo** [mozilla/standards-positions#559]
## Request for Mozilla Position on an Emerging Web Specification

* Base specification title: Web Application Manifest (https://www.w3.org/TR/appmanifest/)
* Proposal https://github.com/w3c/manifest/pull/988
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @marcoscaceres offered to implement this in Gecko

### Other information
This proposal explicitly defines what uniquely identifies a PWA and allow developers to specify the identifier in the manifest.

**Comment by marcoscaceres** [comment]
Patch: https://phabricator.services.mozilla.com/D126331

**Comment by annevk** [comment]
This is a duplicate of #493.
