### ISSUE TITLE
Support for font-family: math

### ISSUE THREAD

**Issue by fred-wang** [mozilla/standards-positions#564]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Fonts Module Level 4
* Specification or proposal URL: https://drafts.csswg.org/css-fonts/#math-def
* Bugzilla URL: math font pref implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=947654
* Mozillians who can provide input: @emilio @jfkthame

### Other information

This request for position is about implementing `font-family: math` in Firefox.

Currently, what we do is forcing a "math" lang on `<math>` elements and then styling them with the corresponding preference...

CSS Fonts Module Level 4 has a new generic family `math` that serves similar purpose. The idea would be to set `font-family: math` by default on `<math>` elements.

**Comment by annevk** [comment]
This seems like a reasonable solution. I suspect this can be closed without dashboard entry as worth prototyping unless either @emilio or @jfkthame have concerns.
