### ISSUE TITLE
Reject non-IPv4 hostnames that end in numbers.

### ISSUE THREAD

**Issue by MattMenke2** [mozilla/standards-positions#568]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Reject non-IPv4 hostnames that end in numbers.
* Specification or proposal URL: https://github.com/whatwg/url/pull/619
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1723456
* Mozillians who can provide input (optional): 
valenting, annevk

**Comment by yoavweiss** [comment]
^^ @annevk @valenting

**Comment by martinthomson** [comment]
I think that we've indicated support already.  Worth prototyping, that is.  We won't update the dashboard for something this small though.

While we can be supportive, I believe that the pull request has a [bug](https://github.com/whatwg/url/issues/632) that you might want to look into.
