### ISSUE TITLE
Content Security Policy for WebAssembly

### ISSUE THREAD

**Issue by fgmccabe** [mozilla/standards-positions#574]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Content Security Policy (update for WebAssembly)
* Specification or proposal URL: https://github.com/w3c/webappsec-csp/pull/293, https://github.com/WebAssembly/content-security-policy/tree/fgm-patch-4
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @annevk

### Other information
This is a proposed amendment to the W3C CSP spec. The idea to extend coverage to WebAssembly. This is in two parts: to use a source directive wasm-unsafe-eval to allow the engine to dynamically compile and execute a wasm module. Currently, if tehre is a non-empty CSP policy, the only way to allow wasm is to use unsafe-eval which is actually intended for JavaScript eval.

The second part is to extend the use of existing CSP script-src policies to cover the streaming APIs: WebAssembly.compileStreaming & WebAssembly.instantiateStreaming.

This is really at the intersection of two sepcs: CSP and Wasm's WebAPI specs. There are links to both of these above.

**Comment by annevk** [comment]
I think this should be worth prototyping. This makes it easier to use WebAssembly in a safe manner on sites already using CSP.

I suggest closing this without dashboard entry as it's a relatively small addition to the platform.

cc @lars-t-hansen @ckerschb
