### ISSUE TITLE
Request for Position: HTMLScriptElement.supports(type) method

### ISSUE THREAD

**Issue by horo-t** [mozilla/standards-positions#576]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTMLScriptElement.supports(type) method
* Specification or proposal URL: https://html.spec.whatwg.org/multipage/scripting.html#dom-script-supports
* Caniuse.com URL (optional): None
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1729239
* Mozillians who can provide input (optional): @annevk 

### Other information

HTMLScriptElement.supports(type) method was introduced by the recent spec change (https://github.com/whatwg/html/pull/7008).
We have started implementing this method in Chromium (https://crbug.com/1245528)

**Comment by annevk** [comment]
This is a small addition to `HTMLScriptElement` to accommodate for the `type` attribute not exclusively reflecting known values. I suggest we close this as `worth prototyping` without dashboard entry.
