### ISSUE TITLE
Request for Mozilla position on intent to ship CSP for WebAssembly

### ISSUE THREAD

**Issue by fgmccabe** [mozilla/standards-positions#580]
## Request for Mozilla Position on intent to ship an Emerging Web Specification

* Specification Title: Content Security Policy (update for WebAssembly)
* Specification or proposal URL: Minimal specification of 'wasm-eval' source directive w3c/webappsec-csp#293
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 
annevk@
### Other information

This is a proposed amendment to the W3C CSP spec. The idea to extend coverage to WebAssembly. This is to use a source directive `wasm-unsafe-eval` to allow the engine to dynamically compile and execute a wasm module. Currently, if there is a non-empty CSP policy, the only way to allow wasm is to use unsafe-eval (on chrome) which is actually intended for JavaScript eval.

This is really at the intersection of two sepcs: CSP and Wasm's WebAPI specs. There are links to both of these above.

I posted a recent 'intent to prototype' issue: https://github.com/mozilla/standards-positions/issues/574. There has been a small change since that issue: the change is now restricted to only adding the wasm-unsafe-eval source directive. The proposal to extend coverage of script-src to include WebAssembly has been dropped.

**Comment by annevk** [comment]
After the discussion in the relevant issue I think change to the proposal is fine. As this is a strict subset and nobody chimed in previously I'll close this as worth prototyping as well.
