### ISSUE TITLE
Disable custom protocols in sandboxed iframe.

### ISSUE THREAD

**Issue by ArthurSonzogni** [mozilla/standards-positions#581]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Disable custom protocols in sandboxed iframe.
* Specification or proposal URL: https://github.com/whatwg/html/pull/7124
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): TBD
* Mozillians who can provide input (optional): @bzbarsky, @annevk, @gijsk, @johannhof (Mozillians who interacted with the [issue](https://github.com/whatwg/html/issues/2191))

### Other information

Developers are surprised that sandboxed iframe can navigate and/or redirect the user toward an external application.

General iframe navigation in sandboxed iframe are not blocked normally, because they stay within the iframe. However they can be seen as a popup or a top-level navigation when it leads to opening an external application. In this case, it makes sense to extend the scope of sandbox flags, and block malvertisers.

This gates iframe navigation toward external protocol behind any of:
- allow-popups
- allow-top-navigation
- allow-top-navigation-with-user-gesture (+ user gesture)

I would be happy to get your feedback.

**Comment by annevk** [comment]
This is something we think is worth prototyping (and I suspect does not warrant a dashboard entry) though note that @johannhof noted a potential compat issue: https://github.com/whatwg/html/issues/2191#issuecomment-922775038.

**Comment by ArthurSonzogni** [comment]
Thanks! I think I will start with metrics only, and try to see what I can do beside @johannhof work for driving those numbers down.

**Comment by annevk** [comment]
Closing this as worth prototyping. Thanks for tackling this @ArthurSonzogni!

**Comment by ArthurSonzogni** [comment]
@annevk I think the additional change to allow impacted website to disable this change: [`allow-custom-protocols-navigation`](https://github.com/whatwg/html/pull/7654) sandbox flags, doesn't worth me filling a second standard position request, and I can reuse this one;

I will assume previous "worth prototyping" still apply, modulo getting your review on the [PR](https://github.com/whatwg/html/pull/7654). Please let me know if this isn't the case.

**Comment by annevk** [comment]
Yeah, that seems fine.

cc @Trikolon
