### ISSUE TITLE
Request for Position: HDR CSS Media Queries

### ISSUE THREAD

**Issue by willcassella** [mozilla/standards-positions#584]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: dynamic-range and video-dynamic range CSS Media Queries
* Specification or proposal URL: https://www.w3.org/TR/mediaqueries-5/#dynamic-range
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1702365

### Other information

Chrome would like to ship the `dynamic-range` and `video-dynamic-range` media queries, currently implemented behind a feature flag (default disabled). See chrome status page: https://chromestatus.com/feature/5680926106320896

To ship, we need Mozilla's official position on this feature. WebKit has already implemented and shipped this.

Thanks!

**Comment by emilio** [comment]
Yeah, makes sense to me.
