### ISSUE TITLE
RFP: CSS Shadow Parts

### ISSUE THREAD

**Issue by emilio** [mozilla/standards-positions#59]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Shadow Parts
* Specification or proposal URL: https://drafts.csswg.org/css-shadow-parts/
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A

### Other information

Over in https://github.com/w3c/csswg-drafts/issues/2368, Mozilla was asked for a position on this spec draft.

Explainer: https://meowni.ca/posts/part-theme-explainer/

**Comment by annevk** [comment]
Once #57 lands I think this should be "worth prototyping".

**Comment by dbaron** [comment]
Also see w3ctag/design-reviews#230, where I had a few comments so far.

**Comment by dbaron** [comment]
And I agree that this fits in `worth prototyping`; I think my biggest concern with the spec is probably the naming of the pseudo-element functions.

**Comment by dbaron** [comment]
(I realize we should probably have separate issues for positions on the main pieces of web components, too.)

**Comment by dbaron** [comment]
Also /cc @heycam @bzbarsky @upsuper in case they have an opinion here.  (The substance of our position should be discussed here; the pull request should just be for the code change.)
