### ISSUE TITLE
Request for position: Cookie Expires/Max-Age attribute upper limit

### ISSUE THREAD

**Issue by arichiv** [mozilla/standards-positions#592]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Cookie Expires/Max-Age attribute upper limit
* Specification or proposal URL: https://github.com/httpwg/http-extensions/pull/1732
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): @annevk @martinthomson 

### Other information

The draft of rfc6265bis[^1] now contains an upper limit for Cookie Expires/Max-Age attributes. As written:
`The user agent MUST limit the maximum value of the [Max-Age/Expiration] attribute. The limit MUST NOT be greater than 400 days (34560000 seconds) in duration. The RECOMMENDED limit is 400 days in duration, but the user agent MAY adjust the limit to be less. [Max-Age/Expiration] attributes that are greater than the limit MUST be reduced to the limit.`[^2]

400 days was chosen as a round number close to 13 months in duration. 13 months was chosen to ensure that sites one visits roughly once a year (e.g., picking health insurance benefits) will continue to work.

Safari already has a compliant upper age limit (7 days), but Firefox and Chrome both support cookies with expiration dates orders of magnitude longer than a millenia in the future.[^3]

What is Mozilla's position on:
1. Having an explicit upper limit for Cookie Expires/Max-Age attributes?
2. Having an explicit upper limit for Cookie Expires/Max-Age attributes that's less than or equal to 400 days?

Thanks!

[^1]: https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html
[^2]: https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-the-expires-attribute
[^3]: https://github.com/httpwg/http-extensions/issues/1600

**Comment by annevk** [comment]
I discussed this with @artines1 and having a limit here seems reasonable to us. We're not entirely sure if we're comfortable with 400 days, but as an upper limit it seems okay.

I suggest we close this as worth prototyping without dashboard entry, assuming there are no further comments.

Thanks @arichiv!

**Comment by Chealer** [comment]
Note that:
1. The proposal originated from [ticket _RFC6265bis: Standardize maximum Max-Age cookie attribute value/handling_](https://github.com/httpwg/http-extensions/issues/1600).
2. The proposal was since integrated in the draft, with important modifications.
3. Firefox apparently implements the recommendation since this year (version 140).
