### ISSUE TITLE
Request for position: minPinLength in WebAuthn

### ISSUE THREAD

**Issue by agl** [mozilla/standards-positions#595]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: minPinLength
* Specification or proposal URL: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-minpinlength-extension
* Explainer (*this is the best place to start*): https://github.com/w3c/webauthn/wiki/Explainer:-minPinLength
* Mozillians who can provide input (optional): Dan Veditz

**Comment by annevk** [comment]
cc @dveditz @martinthomson
