### ISSUE TITLE
Web Components

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#60]
Raising this per suggestion from @dbaron in #59. I'm not really sure how to split this up since as per https://github.com/w3c/webcomponents/blob/gh-pages/README.md the situation is complicated.

* Shadow DOM: we're implementing "v1" and this is now part of the DOM and HTML standards. (Some parts ended up in CSS, UI Events, Touch Events.)
* Custom elements: we're implementing "v1" and this is now part of the DOM and HTML standards.
* HTML Templates: shipped and now part of the HTML standard.
* CSS changes: I'm not sure what the status is here.
* HTML Imports: this is now abandoned I think. We've opposed this in the past: https://hacks.mozilla.org/2014/12/mozilla-and-web-components/.

On top of that there's various new proposals which @smaug---- and I should know more about next week (there's a meeting). My thinking is that we'll open issues for those proposals, but that for the above (apart from the CSS bits) we don't really need anything.

**Comment by smaug----** [comment]
FWIW, we've shipped parts of HTML Templates.
https://bugzilla.mozilla.org/show_bug.cgi?id=1090513 is open

**Comment by annevk** [comment]
Minor update:
* We plan to implement the basics of https://drafts.csswg.org/css-shadow-parts/ for internal usage (see https://bugzilla.mozilla.org/show_bug.cgi?id=1505489)

**Comment by annevk** [comment]
Closing this per above. We'll file new issues as appropriate.

**Comment by smaug----** [comment]
We've shipped Shadow DOM and Custom Elements. Is there any reason to keep this open?

**Comment by dbaron** [comment]
We should document our positions in [the table](https://mozilla.github.io/standards-positions/) before closing issues.

**Comment by dbaron** [comment]
It seems like there are four pieces here:
* Shadow DOM - should we list this as `important` or something else?
* Custom elements - same?
* HTML Templates - same?
* HTML Imports: seems like we should list this as `harmful` based on the info above, but we'd need an explanation of why.  @annevk, would you be able to write that?

It's also possible we need a position like `acceptable` for something that's past the prototyping stage but not `important`?  If we had such a position, would we want to use it here?

**Comment by zcorpan** [comment]
I have split this into separate issues (see #1087):
- #1092
- #1093 
- #1094 
- #1098
