### ISSUE TITLE
Request for position: Canvas2D Layers

### ISSUE THREAD

**Issue by Juanmihd** [mozilla/standards-positions#600]
* Specification Title: Canvas2D Layers
* Specification or proposal URL: https://github.com/whatwg/html/issues/7329
* Explainer (this is the best place to start): https://github.com/fserb/canvas2D/blob/master/spec/layers.md

**Comment by Juanmihd** [comment]
Chromium has an implementation ready and currently hidden behind the flag `canvas-2d-layers`

**Comment by annevk** [comment]
cc @jdashg

**Comment by jdashg** [comment]
I have questions and am engaging in whatwg/html#7329.

**Comment by kdashg** [comment]
The proposal has closed.
