### ISSUE TITLE
Request for Mozilla Position on CBOR

### ISSUE THREAD

**Issue by rmedaer** [mozilla/standards-positions#603]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Concise Binary Object Representation (CBOR)
* Specification or proposal URL: https://datatracker.ietf.org/doc/html/rfc8949
* Caniuse.com URL (optional): No, but [support request here](https://github.com/Fyrd/caniuse/issues/6108)
* Bugzilla URL (optional): ?
* Mozillians who can provide input (optional): ?

### Other information

Similar to JSON library, would it be possible to implement both `CBOR.encode` and `CBOR.decode` ?

---
Edit:
RFC 7049 was deprecated, replacing by RFC 8949.

**Comment by bortzmeyer** [comment]
RFC 7049 was deprecated one year ago. The current standard of CBOR is RFC 8949.

**Comment by rmedaer** [comment]
My bad. I update the issue.

**Comment by annevk** [comment]
I'm not sure I understand the request. CBOR only makes sense for us to support as part of something else. Is there a concrete proposal for JS API somewhere that you want us to evaluate?

**Comment by rmedaer** [comment]
As far as I know, there is currently not any standardized JS API specification for CBOR encoding/decoding. However @cabo says  [on his website](https://cbor.io/impls.html):

> Many implementations use a simple API of the form:
> `encoded = CBOR.encode(data)` ➔ `data = CBOR.decode(encoded)`

**Comment by cabo** [comment]
There is more than one "something else", so it would be useful to have a common way to operate on CBOR encoded data.
The very simple interface described here is fine if the platform can map the CBOR generic data model (including, e.g., tags); it is probably worth to describe how that is done in general.
You probably also want to provide a similar interface for RFC8742 CBOR Sequences.

**Comment by annevk** [comment]
To be clear, this is a place to ask Mozilla for its position on a standard or proposal, not to create a proposal. For that you want https://wicg.io/ or equivalent. I suggest we mark this as `defer`.

**Comment by ekr** [comment]
```defer``` seems fine.

I suppose we could offer an opinion on CBOR per se, but that seems kind of redundant given that it's widely deployed.

**Comment by martinthomson** [comment]
To be clear, we ship it already in Firefox.  It's part of WebAuthn.  So this is somewhat moot.
