### ISSUE TITLE
Request for position: mix-blend-mode: plus-lighter

### ISSUE THREAD

**Issue by vmpstr** [mozilla/standards-positions#607]
## Request for Mozilla Position on CSS mix-blend-mode amendment

The proposal is to add plus-lighter as a value to mix-blend-mode CSS property, which would act as the compositing operator [plus-lighter](https://drafts.fxtf.org/compositing/#porterduffcompositingoperators_plus_lighter)

* Specification Title: mix-blend-mode: plus-lighter
* Specification or proposal URL: https://github.com/w3c/fxtf-drafts/issues/445#issuecomment-995087612

**Comment by birtles** [comment]
Looks like we already implement this: https://bugzilla.mozilla.org/show_bug.cgi?id=1746248

**Comment by zcorpan** [comment]
I guess that means we're positive.

Relatedly, I see there's an issue about removing `plus-darker` from the spec: https://github.com/w3c/fxtf-drafts/issues/447

**Comment by martinthomson** [comment]
I'm going to say that this doesn't need a dashboard entry.
