### ISSUE TITLE
blocking="render" attribute on <link>, <script> and <style>

### ISSUE THREAD

**Issue by xiaochengh** [mozilla/standards-positions#608]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: `blocking="render"` attribute on `<link>`, `<script>` and `<style>`
* Specification or proposal URL:
  * Full proposal: https://gist.github.com/xiaochengh/9404abbecdc3b45c0e9f3d5e99fbc65d
  * WHATWG discussion: https://github.com/whatwg/html/issues/7131
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

This proposal also includes the standardization of a general **render-blocking mechanism**, which will standardize the existing [stylesheet loading behaviors](https://github.com/chrishtr/rendering/blob/master/stylesheet-loading-behavior.md) and support the proposed attribute. The proposed behavior slightly differs from Firefox's current behavior: the proposal does not allow `requestAnimationFrame()` callbacks to fire until all render-blocking stylesheets are loaded, while Firefox currently allows it.

**Comment by smaug----** [comment]
Well, UA can always stop the blocking. Otherwise there would be security/privacy issues.
But yes, we could stop calling fAF. Though, need to test how resize (and other) events behave in other implementation while rendering is blocked.

I think in general the idea is quite reasonable.

**Comment by noamr** [comment]
Intending to amend the current spec for render-blocking scripts to also include inline scripts, see #10034

**Comment by zcorpan** [comment]
I think this is reasonable and useful. My main concern is that it might be a bit too easy to block rendering on a `defer` (or `module` which is defer by default) script, and thus block until the timeout hits or until the full document is parsed. I'll file a spec issue.
