### ISSUE TITLE
hidden=until-found HTML attribute and beforematch event

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#612]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: hidden=until-found HTML attribute and beforematch event
* Specification or proposal URL: https://github.com/whatwg/html/pull/7475
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @emilio 

### Other information

- whatwg/html issue: https://github.com/whatwg/html/issues/6040
- Explainer: https://github.com/WICG/display-locking/blob/main/explainers/hidden-content-explainer.md
- This was originally proposed as the beforematch event and the content-visibility:hidden-matchable CSS property, but was [changed to an HTML attribute](https://github.com/whatwg/html/issues/6040#issuecomment-785991421) due to [feedback from the CSSWG](https://github.com/w3c/csswg-drafts/issues/5595#issuecomment-776914538).
- This is very similar to the auto-expanding details feature, but is a more generic version that can be used outside of details elements: https://github.com/mozilla/standards-positions/issues/578

**Comment by annevk** [comment]
Thanks for raising this @josepharhar!

As mentioned, this is very similar to auto-expanding `details` elements which we're supportive of. It's just now something that all elements can make use of.

I suggest we mark this worth prototyping as well, sans dashboard entry.
