### ISSUE TITLE
Request for Position: Topics API

### ISSUE THREAD

**Issue by jkarlin** [mozilla/standards-positions#622]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Topics API
* Specification or proposal URL: https://github.com/patcg-individual-drafts/topics
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
Chrome status page: https://chromestatus.com/feature/5680923054964736
 
Note that Chrome is implementing (with spec following shortly after) but we're quite open to evolving the API over time and are appreciative of your feedback.

**Comment by jkarlin** [comment]
Yes, that's available at https://github.com/patcg-individual-drafts/topics/blob/main/topics_analysis.pdf

**Comment by estelle** [comment]
can we add the `position: negative` label to this issue?
