### ISSUE TITLE
Request for position: WebDriver-BiDi

### ISSUE THREAD

**Issue by juliandescottes** [mozilla/standards-positions#632]
## Request for Mozilla Position on an Emerging Web Specification

Specification Title: WebDriver-BiDi

Specification or proposal URL: https://w3c.github.io/webdriver-bidi 

Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1690255 

Mozillians who can provide input (optional): James Graham (@jgraham), Henrik Skupin (@whimboo), Julian Descottes (@juliandescottes), Alexandra Borovova (@lutien), Jan Odvarko (@janodvarko)

### Other information

WebDriver-BiDi defines a WebSockets-based, bidirectional, protocol for external tools to interact with and control a web browser. The initial target use case is automated testing of web applications.

The [current WebDriver specification](https://www.w3.org/TR/webdriver/) implemented by major browser engines lacks bidirectional capabilities, making it difficult to test contemporary web applications, which are often highly interactive and event-driven. Consequently modern testing tools (e.g. [Puppeteer](https://github.com/puppeteer/puppeteer), [Playwright](https://github.com/microsoft/playwright), [Cypress](https://github.com/cypress-io/cypress)) have been written on top of browser-specific proprietary protocols which provide a bidirectional communications model. Tools designed around the WebDriver standard (e.g. [Selenium](https://www.selenium.dev/)) have also begun to implement new functionality that depends on browser-specific protocols because of this limitation in the architecture of the existing specification.

The widespread use of browser-specific protocols for remote automation and testing makes it harder for web developers to write tests across multiple browsers. This in turn disadvantages implementations of the web platform that don't enjoy specific support from popular testing tools, and makes it more likely that users will run into content that doesn't work in their choice of user agent.

WebDriver-BiDi aims at providing a standard & cross-browser alternative to those browser-specific protocols, allowing testing tools to work with any compliant implementation.

The specification is currently a working draft that is under active development.

Chrome is currently implementing https://github.com/GoogleChromeLabs/chromium-bidi 
Firefox is currently implementing and plans to ship an initial implementation consisting of a subset of stable features in Firefox 101 https://bugzilla.mozilla.org/show_bug.cgi?id=1753997

**Comment by bgrins** [comment]
Marked as worth-prototyping in https://github.com/mozilla/standards-positions/pull/648
