### ISSUE TITLE
form rel attribute

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#633]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: form rel attribute
* Specification or proposal URL: https://html.spec.whatwg.org/multipage/forms.html#attr-form-rel
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1509346
* Mozillians who can provide input (optional): 

### Other information

This has been shipped by Safari, and is about to be shipped in chrome: https://groups.google.com/a/chromium.org/g/blink-dev/c/Ram6i7ffgkM
Here are the relevant WPTs: https://wpt.fyi/results/html/semantics/forms/form-submission-target

**Comment by annevk** [comment]
Thanks for tackling this! As this is part of the agreed upon goals of https://wpt.fyi/interop-2022 let's close this as worth prototyping. And no dashboard entry as this is a part of the HTML standard.

**Comment by ericlaw1979** [comment]
This (form targeting _blank has noopener) has shipped in Chrome but not Firefox.
