### ISSUE TITLE
Element.checkVisibility method

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#634]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Element.checkVisibility method
* Specification or proposal URL: https://drafts.csswg.org/cssom-view/#dom-element-isvisible
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

Here is the TAG review: https://github.com/w3ctag/design-reviews/issues/734
Here is the csswg issue where this was discussed: https://github.com/w3c/csswg-drafts/issues/6850

**Comment by smaug----** [comment]
Oddly named method when isVisible({checkInert: true}); may return true on a visible element.

And step 6 of the algorithm
"If the [checkVisibilityCSS](https://drafts.csswg.org/cssom-view/#dom-isvisibleoptions-checkvisibilitycss) dictionary member of options is true, and this is invisible," doesn't seem to really define what "invisible" means.

**Comment by smaug----** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/7256

**Comment by josepharhar** [comment]
> Oddly named method when isVisible({checkInert: true}); may return true on a visible element.

Do you mean that it may return false for a visible element...? Or that it may return true for an invisible element? Which definition of visible are you interested in with this example? Are you just interested in the inert attribute being included in this method at all?

**Comment by josepharhar** [comment]
Good point, I filed an issue to consider removing the inert option: https://github.com/w3c/csswg-drafts/issues/7274

**Comment by miketaylr** [comment]
It looks like the CSSWG resolved to remove the `checkInert` option: https://github.com/w3c/csswg-drafts/issues/7274#issuecomment-1130214343. Any further thoughts @smaug----?

**Comment by smaug----** [comment]
The method was renamed, I think. Is it now checkVisibility?

**Comment by karlhorky** [comment]
Should this be closed? Seems like the position is positive if [the "Can I Use..." data](https://caniuse.com/mdn-api_element_checkvisibility) reports this being available in Firefox since version 106 (Oct 2022):

![Screenshot 2023-10-31 at 10 29 40](https://github.com/mozilla/standards-positions/assets/1935696/b6ed1877-d383-49a2-9ab7-cbb65670c4f3)

**Comment by smaug----** [comment]
Yeah, looks like this was implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1777293
