### ISSUE TITLE
DisplayMediaStreamConstraints.systemAudio

### ISSUE THREAD

**Issue by eladalon1983** [mozilla/standards-positions#638]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: DisplayMediaStreamConstraints.systemAudio
* Specification or proposal URL: https://github.com/w3c/mediacapture-screen-share/pull/222/files

### Other information
@jan-ivar has approved merging the PR that introduces this API surface.

**Comment by bgrins** [comment]
Marking as worth prototyping as per https://github.com/mozilla/standards-positions/issues/639#issuecomment-1157197052

**Comment by eladalon1983** [comment]
Thank you.
CC @yoavweiss and @slightlyoff.
