### ISSUE TITLE
DisplayMediaStreamConstraints.selfBrowserSurface

### ISSUE THREAD

**Issue by eladalon1983** [mozilla/standards-positions#639]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: DisplayMediaStreamConstraints.selfBrowserSurface
* Specification or proposal URL: https://github.com/w3c/mediacapture-screen-share/pull/216/files
* Mozillians who can provide input (optional): @jan-ivar 

### Other information
The PR that introduced this new API surface was approved by @jan-ivar.

**Comment by bgrins** [comment]
@jan-ivar based on our conversation I believe that the 4 issues should all be marked as worth-prototyping (without requiring a stated position on the webpage):
- https://github.com/mozilla/standards-positions/issues/638
- https://github.com/mozilla/standards-positions/issues/639
- https://github.com/mozilla/standards-positions/issues/641
- https://github.com/mozilla/standards-positions/issues/642 

I'm going to mark them up that way, but feel free to send over a PR if you think taken as a whole we should have document the position.
