### ISSUE TITLE
Response.json()

### ISSUE THREAD

**Issue by ricea** [mozilla/standards-positions#640]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Response.json() (part of "Fetch")
* Specification or proposal URL: https://fetch.spec.whatwg.org/#ref-for-dom-response-json
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1758943
* Mozillians who can provide input (optional): annevk

**Comment by annevk** [comment]
This seems reasonable to us per prior discussion of which the conclusion was recorded in https://github.com/whatwg/fetch/pull/1392#pullrequestreview-970555855.

(We wouldn't support something in the WHATWG if we didn't thought it was worth prototyping for standards-positions purposes.)
