### ISSUE TITLE
MediaTrackSupportedConstraints.suppressLocalAudioPlayback

### ISSUE THREAD

**Issue by eladalon1983** [mozilla/standards-positions#641]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: MediaTrackSupportedConstraints.suppressLocalAudioPlayback
* Specification or proposal URL: https://github.com/w3c/mediacapture-screen-share/pull/164/files
* Mozillians who can provide input (optional): @jan-ivar 

### Other information
The PR that introduced this new API surface was approved by @jan-ivar.

**Comment by bgrins** [comment]
Marking as worth prototyping as per https://github.com/mozilla/standards-positions/issues/639#issuecomment-1157197052
