### ISSUE TITLE
import.meta.resolve()

### ISSUE THREAD

**Issue by domenic** [mozilla/standards-positions#647]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: import.meta.resolve()
* Specification or proposal URL: https://github.com/whatwg/html/pull/5572 , https://gist.github.com/domenic/f2a0a9cb62d499bcc4d12aebd1c255ab
* Mozillians who can provide input (optional): @annevk, @codehag

### Other information

This has unofficial supportive comments from @annevk and @codehag in the pull request, but I thought it'd be best to get an official position as well.

This will be useful to test import maps, which are "worth prototyping".

**Comment by annevk** [comment]
Asked a clarifying question in https://github.com/whatwg/html/pull/5572#issuecomment-1148616027 as I'd really like for APIs like this to be widely adopted.

**Comment by codehag** [comment]
From my perspective, this is worth prototyping in line with import maps, as it is a requirement for adequately testing that spec. In addition, I think that this provides a useful utility for inspecting the resolution of a specifier or relative URL, especially in the context of import maps.

**Comment by bgrins** [comment]
Thanks Yulia! I'm going to label as worth prototyping and close the issue as opposed to asking you to do a PR, since this looks like a logical addition to import maps (which we alread have a stated position for). But if you think it should be documented more formally please feel free to send one over.
