### ISSUE TITLE
css-easing: `linear()` easing

### ISSUE THREAD

**Issue by dshin-moz** [mozilla/standards-positions#649]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: `linear()` easing 
* Specification or proposal URL: https://github.com/w3c/csswg-drafts/pull/6533
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1764126
* Mozillians who can provide input (optional): @emilio, @dholbert

**Comment by dholbert** [comment]
This is an often-requested animation feature, with relatively low complexity, which helps web developers avoid needing to lean on JS libraries to provide "bounce"/"spring" visual effects (or anything fancier than "ease-in" animation style).

Given the demand, the low-complexity, and the presence of a draft spec with CSSWG activity around it, I think we can easily consider this worth-prototyping.

**Comment by martinthomson** [comment]
Labelled and I think we can close without updates to the dashboard.
