### ISSUE TITLE
Request for position : CSS Overflow for replaced elements

### ISSUE THREAD

**Issue by khushalsagar** [mozilla/standards-positions#659]
## Request for Mozilla Position on CSS Overflow for replaced elements

* Specification Title: css-overflow-3
* Specification or proposal URL: https://drafts.csswg.org/css-overflow/#propdef-overflow. See https://github.com/w3c/csswg-drafts/issues/7144 for specific edits to this spec.
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
This is a follow up to #626 which introduced object-overflow to support the same functionality. Based on feedback in the CSSWG the proposal has been updated to use the existing `overflow` property. This property is already respected for svg elements and the proposal aims to have consistent behaviour for all replaced elements.

**Comment by dholbert** [comment]
This seems reasonable; I think we could call this "worth prototyping", for the same reasons discussed in #626.

(This is essentially the same feature that was discussed there, though with slightly different ergonomics to avoid near-duplicate feature sets.)

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1779332 on implementing this feature (CSS Overflow for replaced elements).

**Comment by martinthomson** [comment]
Thanks @dholbert.  As this is small, let us just resolve the issue with those comments.
