### ISSUE TITLE
Request for position : Render blocking status in Resource Timing

### ISSUE THREAD

**Issue by abinpaul1** [mozilla/standards-positions#662]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Render blocking status in Resource Timing
* Specification or proposal URL: 
   - Explainer: https://github.com/abinpaul1/resource-timing/blob/render-blocking-status-explainer/Explainer/Render_Blocking_Status.md
   - Spec PR : https://github.com/w3c/resource-timing/pull/327
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @bdekoz @sefeng211 
### Other information

Link to entry on the Chrome Platform Status: https://chromestatus.com/feature/5166965277589504

**Comment by bdekoz** [comment]
We did a review today, seems like a good idea. No objections here, seems like a logical next step after the attribute work.
