### ISSUE TITLE
fetch streaming upload

### ISSUE THREAD

**Issue by yutakahirano** [mozilla/standards-positions#663]
## Request for Mozilla Position on fetch streaming upload

* Specification Title: Fetch streaming upload
* Specification or proposal URL: https://fetch.spec.whatwg.org/
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): @annevk (whle he is leaving Mozilla), @ddragana 

### Other information
Discussions:
 - https://github.com/whatwg/fetch/issues/1438
 - https://github.com/whatwg/fetch/issues/966
 - https://github.com/whatwg/fetch/issues/425

TAG review:
 - https://github.com/w3ctag/design-reviews/issues/754

Explainer:
 - https://github.com/yutakahirano/fetch-with-streams/blob/master/streaming-upload.md

**Comment by yutakahirano** [comment]
We talked about the feature at TPAC 2019 and at that time Mozilla was interested in the feature. [note](https://docs.google.com/document/d/1q090ovJ4gd8wSfVtvuoZLMZ51YkiFDsEZ0Jiqi41Iys/edit#heading=h.85gziabhajhg)

**Comment by nwtgck** [comment]
These may be Bugzilla URLs.
* [1387483 - [Meta-Bug] Support ReadableStream as Request.body in fetch API](https://bugzilla.mozilla.org/show_bug.cgi?id=1387483)
* [1469359 - Support ReadableStream as Request.body in fetch API in necko](https://bugzilla.mozilla.org/show_bug.cgi?id=1469359)

**Comment by bgrins** [comment]
I chatted with some folks about this. We're positive on the concept & use cases. There were two concerns raised which I wanted to share and give space for discussion if necessary:

1) Potential for observable ServiceWorker lifetime changes (as per @asutherland). We think browsers should not keep alive a ServiceWorker due to an ongoing stream and since the SW lifetime isn't specced there's a risk for interop bugs. @yutakahirano do you know if this is the case in the Chrome implementation?
2) There's likely some implementation complexity for Gecko (as per @mystor), which doesn't affect our position on the standard but I'll share it for context:
> Because our existing code depends on all of the upload stream being available and rewindable, we actually aggressively convert the stream into a buffered one so we can replay it within the http channel

**Comment by yutakahirano** [comment]
> Potential for observable ServiceWorker lifetime changes (as per @asutherland). We think browsers should not keep alive a ServiceWorker due to an ongoing stream and since the SW lifetime isn't specced there's a risk for interop bugs. @yutakahirano do you know if this is the case in the Chrome implementation?

When the script clones a Request and then kicks off the network fallback, we need to keep the service worker alive until we read the request body.

See ['Running clone() in the service worker does not prevent network fallback.'](https://github.com/web-platform-tests/wpt/blob/master/service-workers/service-worker/fetch-event.https.h2.html#L91) which uses ["handleConeAndIgnore"](
https://github.com/web-platform-tests/wpt/blob/master/service-workers/service-worker/resources/fetch-event-test-worker.js#L163) for the test case.

**Comment by valenting** [comment]
Considering the last comment and the fact that we are actually going to implement this, I think we can close this issue as Positive ➕.

**Comment by martinthomson** [comment]
➕ it is.  Thanks all.  No dashboard entry for this one.
