### ISSUE TITLE
ContentVisibilityAutoStateChanged event

### ISSUE THREAD

**Issue by vmpstr** [mozilla/standards-positions#664]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Contain: Content Visibility
* Specification or proposal URL: This will be an amendment to https://drafts.csswg.org/css-contain-2/
* Explainer: https://github.com/vmpstr/web-proposals/blob/main/explainers/cv-auto-event.md

CSSWG discussion: https://github.com/w3c/csswg-drafts/issues/7384#issuecomment-1176847043

**Comment by bgrins** [comment]
Under consideration - with some questions in https://github.com/w3c/csswg-drafts/issues/7384#issuecomment-1183497525

**Comment by jcsteh** [comment]
Added https://github.com/w3c/csswg-drafts/issues/7384#issuecomment-1189938042 regarding a11y concerns.

**Comment by vmpstr** [comment]
We've resolved the a11y concerns and I believe we answered the questions raised on the issue. Let me know if I missed something

**Comment by miketaylr** [comment]
@bgrins @jcsteh please let us know if a11y concerns have been addressed - thanks!

**Comment by bgrins** [comment]
I had synced with @jcsteh after the conversation and understood that the updated guidance (as planned at the time) would address the a11y concerns. This was before the actual text changed though so I wouldn't mind getting a thumbs up from him. But I'm pretty confident it is and certainly appreciate the team taking the time to discuss and make the changes.

**Comment by jcsteh** [comment]
As per https://github.com/w3c/csswg-drafts/pull/7515#issuecomment-1200727627:

> The updated text addresses my concerns. Thank you. 👍

**Comment by bgrins** [comment]
I was just reviewing my notes for this and I remember Emilio raising [a question](https://github.com/w3c/csswg-drafts/issues/7384#issuecomment-1183497525) about when the event should fire in the case when it's triggered due to focus or selection
> there's other things that affect c-v: auto state, like focus and selection. Does the event still fire at IntersectionObserver time even when e.g., a descendant gets focus? 

@emilio @vmpstr has this been resolved? Maybe I'm missing it but I don't see it addressed in the thread

**Comment by vmpstr** [comment]
I don't think that question was directly answered.

To answer: the timing of the event is a task that runs when the state of the c-v auto element changes. Points 3 and 4 in https://www.w3.org/TR/css-contain-2/#cv-notes mention when the state of the c-v auto (or specifically the skipping of the contents) changes, and that's after the rAF callbacks. So this event is dispatched after the lifecycle phase in which these rAF callbacks and changes are done.

**Comment by emilio** [comment]
Hmm, that spec note is broken right? Frame callbacks run in step 13, but that happens before intersection observer tasks and paint.

So then I assume it's collapsed somehow and focus changes don't have any effect in the scheduling until you get to that point?

Also doesn't that mean that c-v: auto is one frame late (which seems very unfortunate), but this event wouldn't? That seems really weird...

**Comment by vmpstr** [comment]
> Hmm, that spec note is broken right? Frame callbacks run in step 13, but that happens before intersection observer tasks and paint.

Hmm yeah, that should say step 13 not step 11. Do you know if the Update the Rendering spec changed recently? The c-v spec seems to have been written with a different rendering model in mind. Specifically, I seem to recall that the steps were run rAF callbacks, update the user interface (ie do the render) then dispatch intersection observations. For this reason we wanted to defer the observation to before the _next_ updating of the user interface (and after the next rAF callbacks), so that the visual updates will be reflected in time for script to inspect the state of the element. This no longer seems to be needed in the new rendering model. Although I briefly checked Chromium, and it's still dispatching intersection observations _after_ updating the rendering. I think we (Chromium) need to revisit the spec and the code to see if I'm misunderstanding this or whether they aren't aligning. 

All that aside, the intent of the event is to fire _after_ the state changes that affect c-v auto have taken place. I tried to write the spec change to say that it should run at the earliest posted-task opportunity after the state change occurs, which is intended to say after the visual effect of the state change has taken place. Here, the "state change" is already taking into account any of the intersection observation delay that may need to happen, so the event should not fire earlier than the c-v auto change

**Comment by vmpstr** [comment]
Ok, I misunderstood the steps here. It is true that this should be step 13 (and when referring to intersection observer, that's step 14) -- I think a few steps were added to the algorithm, pushing things down. However, the "update the rendering" here is not style & layout, etc, but rather just present pixels to screen. It is still the case that the style & layout update, which is implicit in the spec between step 13 and 14, so since IO observations happen at 14, we don't want to update style&layout in the same frame and instead defer the observation delivery to after step 13 of the next update the rendering phase. It is after this delivery that the task is posted to fire this event

**Comment by vmpstr** [comment]
@emilio do you think what I said makes sense here? Other than fixing the step numbers in c-v spec, do you think the event spec text looks reasonable?

**Comment by zcorpan** [comment]
This was implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1798485
