### ISSUE TITLE
Encoding streams API (TextDecoderStream and TextEncoderStream)

### ISSUE THREAD

**Issue by saschanaz** [mozilla/standards-positions#673]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Encoding Standard
* Specification or proposal URL: https://encoding.spec.whatwg.org/#interface-textdecoderstream, https://encoding.spec.whatwg.org/#interface-textencoderstream
* Caniuse.com URL (optional): https://caniuse.com/mdn-api_textdecoderstream, https://caniuse.com/mdn-api_textencoderstream
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1486949
* Mozillians who can provide input (optional): @smaug---- ?

### Other information

Gecko already have TextDecoder and TextEncoder which are defined by the same spec.

(Requested from the [already submitted intent-to-ship](https://groups.google.com/a/mozilla.org/g/dev-platform/c/QtcGTx8gJWQ/m/C1ZVOVN6BgAJ). We don't have the position for the existing non-stream features anyway!)

**Comment by bgrins** [comment]
The streams API is marked as [worth prototyping](https://github.com/mozilla/standards-positions/issues/70) and the ability to encode / decode text for streams makes sense. It's also been specified and shipping for a long time in other browsers so I wouldn't expect any surprises here.
