### ISSUE TITLE
The `model` element

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#674]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: The `model` element
* Specification or proposal URL: https://github.com/immersive-web/model-element/blob/main/explainer.md | [early spec]( https://immersive-web.github.io/model-element/)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
The model element allows embedding 3D graphical content into a [[HTML](https://immersive-web.github.io/model-element/#bib-html)] document. The HTMLModelElement interface then provides a means to interface with the embedded resource.

**Comment by marcoscaceres** [comment]
Hi Mozilla friends, the [explainer](https://github.com/immersive-web/model-element/blob/main/explainer.md) provides a more wholistic overview of the proposal - so it's best to start there to get a sense of the general idea and motivation of why we want to add this to the Web. 

The [super early draft spec](https://immersive-web.github.io/model-element/) outlines all the issues we've identified so far, which we would love to collaborate on at the W3C and WHATWG.

**Comment by bgrins** [comment]
Hi @marcoscaceres - thanks for filing. We've started some internal discussions about this  but don't have specific feedback yet - so I'm going to mark as under consideration

**Comment by marcoscaceres** [comment]
Thanks, @bgrins! I guess the biggest questions that have come up are around rendering (i.e., what renderer could Gecko  and other browser engines could use on various platforms?). In WebKit for iOS and macOs, we are relying on AR Quick Look, but we haven't given much thought of what Gecko or other engines might use on Windows, Linux, Android, etc? 

The other big elephant in the room is the formats: The proposal is silent on that, but WebKit currently only supports USDZ. However, much like `<video>`, developers can use `<source>` for format selection. That has its own set of problems, but it's there for consideration as part of the proposal. 

Looking forward to hearing from you and the rest of the Mozilla team.
