### ISSUE TITLE
Autoplay Policy Detection API

### ISSUE THREAD

**Issue by alastor0325** [mozilla/standards-positions#675]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Autoplay Policy Detection API
* Specification or proposal URL: https://w3c.github.io/autoplay/
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1773551
* Mozillians who can provide input (optional): alwu

### Other information
This is a new API which allows websites to detect whether they are allowed to play autoplay media. We would like to be the first browser starting implementing this. We already have a [similar experimental feature](https://searchfox.org/mozilla-central/rev/552bfc6334b797d92fb2ce8e93a6ace5f47cd56d/dom/webidl/HTMLMediaElement.webidl#287) before.

**Comment by bgrins** [comment]
Do Blink and WebKit have positions on this?

**Comment by bgrins** [comment]
A quick search on blink-dev for Autoplay Policy turned up https://groups.google.com/a/chromium.org/g/blink-dev/c/5Y1BqbGauEs/m/rRocaytKBgAJ which is and mentioned Web Audio - could you give a little bit of history/context to this and related features for the uninitiated?

And if we don't have a previous signal from webkit-dev then you could ask at https://github.com/WebKit/standards-positions/.

**Comment by alastor0325** [comment]
Not yet, but Chrome, Safari and Edge were all involved in this spec discussion during the past Media WG meetings. The [link](https://groups.google.com/a/chromium.org/g/blink-dev/c/5Y1BqbGauEs/m/rRocaytKBgAJ) you mentioned above is a different thing, which is about their implementation of blocking web audio.

In short, every browsers has their own way to block autoplay (media element & web audio), but it's a pain for web developers to know whether they can play something or not. Current situation for them is that they have to make some hacky workaround, trying to start the media first and see if the play promise gets rejected or not. This spec aims to give web developers a clear picture about whether they are allowed to play autoplay media without using any other hacky workarounds.

My plan is to ask their attitude about this API in the TPAC this year, but if other browsers have same repo like this, I would go to file issues for them as well.

**Comment by bgrins** [comment]
> My plan is to ask their attitude about this API in the TPAC this year, but if other browsers have same repo like this, I would go to file issues for them as well.

From https://wiki.mozilla.org/ExposureGuidelines#How_do_we_know_what_other_browser_engines_think.3F - there's not a defined process to preflight position requests from Blink (other than waiting for an "intent to"), so a discussion within the working group makes sense to me. For WebKit - yeah, please file an issue there.

**Comment by martinthomson** [comment]
I've been interested in the intersection between user consent and engagement gestures (clicks, keypresses) for some time.  The permissions API was the place where we did a lot of that work.  Take the notifications permission, for which browsers recently made the consent dialog conditional on a user gesture.  That state or condition is not visible through any API surface and it is still inconsistent between browsers (and sites, thanks to Google's implementation quirks), which makes it pretty hard for sites to build to reliably.

I would like to see more effort concentrated on reconciling things in this area so that they are more consistent.  This appears to be a point solution.  @alastor0325, can you speak about what the Media WG has done about that sort of thing?

> there's not a defined process to preflight position requests from Blink

If you have contacts at Google or Microsoft (or Brave or DDG or Vivaldi or Opera or...), who you can ask directly, within the working group or outside, that might work.

**Comment by Explorer09** [comment]
Hello. I'm just an ordinary user of Firefox and may I give a comment on this?

The introduction of the spec mentioned this use case:

> For instance, if a user agent only blocks audible autoplay, then web developers can replace audible media with inaudible media to keep media playing, instead of showing a blocked media which looks like a still image to users. If the user agent does not allow any autoplay media, then web developers could stop loading media resources and related tasks to save the bandwidth and CPU usage for users. 

I think the use case is weak for justifying the need to tell the web server about the autoplay policy. I think a better way for achieving the task is to let web pages present both the media and the alternate content (still image) and let the browser decide which resource to load.

**Comment by alastor0325** [comment]
Sorry for my late reply.

> I would like to see more effort concentrated on reconciling things in this area so that they are more consistent. This appears to be a point solution. @alastor0325, can you speak about what the Media WG has done about that sort of thing?

The only issue related with Permission API is [this one](https://github.com/w3c/autoplay/issues/27) and so far we don't have other discussion related with that. The purpose of the autoplay policy detection is to provide an abstract layer no matter what kind of blocking autoplay mechanism is implemented by user agent, which should be helpful to address the pain point of not knowing whether those internal status affects autoplay or not.

> I think the use case is weak for justifying the need to tell the web server about the autoplay policy. I think a better way for achieving the task is to let web pages present both the media and the alternate content (still image) and let the browser decide which resource to load.

HTML spec already has defined [poster](https://html.spec.whatwg.org/multipage/media.html#attr-video-poster) on the video element, which is used to display an image when video is not able to play.

---

In addition, in last TPAC, Safari expressed their interest in this spec as well. At the time I was presenting this spec, no chrome and edge guys were there so I couldn't know their position. But one of the spec reviewers is from Chrome, at least he didn't express negative or objection during the review process.

**Comment by Explorer09** [comment]
@alastor0325 
Sorry for my ignorance, but is there anyone concerned about the potential fingerprinting when the web page can query the autoplay policy _per element_, instead of just yes and no on the "can-autoplay" question?

Specifically, why is there a separate _[allowed-muted](https://www.w3.org/TR/autoplay-detection/#dom-autoplaypolicy-allowed-muted)_ value and not just _[allowed](https://www.w3.org/TR/autoplay-detection/#dom-autoplaypolicy-allowed)_ and _[disallowed](https://www.w3.org/TR/autoplay-detection/#dom-autoplaypolicy-disallowed)_? The media element should have been told if it is audible already, and whether the user would play the media with sound, or play it muted, is not a concern for a web page.

And if the user wants to save bandwidth by requesting an inaudible stream only, there should be a dedicated API for doing so. The autoplay policy API seems (for me) to be a wrong solution to the problem.

Detecting whether a media can autoplay ahead of time have merits, but I would wish a browser that, for privacy reasons, _not tell too specifically about whether a media can autoplay muted_. In other words, just return _allowed_ or _disallowed_. In case a web page trying to guess if the policy is _allowed-muted_, the browser may pretend it's not (but autoplay everything muted to the user anyway; in other words, lie on the policy details).

**Comment by alastor0325** [comment]
> Sorry for my ignorance, but is there anyone concerned about the potential fingerprinting when the web page can query the autoplay policy per element, instead of just yes and no on the "can-autoplay" question?

Yes, [this issue](https://github.com/w3c/autoplay/issues/24) is for discussing the fingerprinting possibility, feel free to leave your suggestion there as well.

Only providing `allowed` and `disallowed` for the media element isn't enough which can't really solve the problems which web authors encounter. Especially blocking only audible autoplay has become a common thing among different browsers, if web authors just want to know whether autoplay is allowed or not for a media element, they can simply call `media.play()` then they can know the result by checking the play promise. So only answering `yes/no` seems not too useful for this API design.

**Comment by Explorer09** [comment]
@alastor0325 Unfortunately in the issue you referenced, you only discussed about the `allowed` vs. `disallowed` difference in the context of fingerprinting. But I have a question specifically on the `allowed-muted` value. The benefit of reporting `allowed-muted` separate from `allowed` is small, and for the use case like:
> (https://w3c.github.io/autoplay/#introduction) For instance, if a user agent only blocks audible autoplay, then web developers can replace audible media with inaudible media to keep media playing

it seems to me like a wrong tool for the job (the web browser can play the audible media muted, without any additional work of web developers).

And for the use case of livestream media where this autoplay API _might_ benefit, as I mentioned in a previous comment, it would be better to just have the browser request a "no-audio" stream (as a dedicated request API), similar to how a video resolution change request can be done, and there would be no need to expose the client side setting (the autoplay policy) right away.

**Comment by uazo** [comment]
> So only answering yes/no seems not too useful for this API design.

I don't think that is strictly true.
For web developers, knowing exactly why the promise goes wrong possibly grants an advantage in terms of user experience, since it is possible to show the reason for the error, whereas now the only possibility is introspection of the exception.

**Comment by alastor0325** [comment]
> it seems to me like a wrong tool for the job (the web browser can play the audible media muted, without any additional work of web developers).

Sorry I don't agree this. Currently it did require extra work to allow muted media to autoplay depending on what kind of blocking autoplay mechanism a user agent is using. 

> And for the use case of livestream media where this autoplay API might benefit, as I mentioned in a previous comment, it would be better to just have the browser request a "no-audio" stream (as a dedicated request API), similar to how a video resolution change request can be done, and there would be no need to expose the client side setting (the autoplay policy) right away.

I don't think browser should do any request to server, this is completely different from the scenario of changing the video resolution. Those are all website's implementation, not API level design.

> I don't think that is strictly true. For web developers, knowing exactly why the promise goes wrong possibly grants an advantage in terms of user experience, since it is possible to show the reason for the error, whereas now the only possibility is introspection of the exception.

I don't understand your point. Handling rejected promise is independent with this API and why we need to put them together to discuss? In addition, another benefit of this API is also allowing website to understand if they can play autoplay media before they actually create a real instance, which was a request we received from web developers during the spawning process of this API.

**Comment by alastor0325** [comment]
In addition, for finger printing discussion, feel free to discuss that in the [spec issue](https://github.com/w3c/autoplay/issues/24) or this [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1812190). Thanks.

**Comment by alastor0325** [comment]
This spec got good feedback from [TAG](https://github.com/w3ctag/design-reviews/issues/810) and Apple also expressed support on their [position](https://github.com/WebKit/standards-positions/issues/113#issuecomment-1426130160). So I'm going to close this bug and file the Intent-to-Ship later in order to target this API on Fx112+.

**Comment by zcorpan** [comment]
We should still record our position and add a dashboard entry.

**Comment by zcorpan** [comment]
Proposed position: positive
Proposed rationale: This API provides a convenient and synchronous answer to whether a particular kind of media can autoplay, which is something web developers are currently detecting either with various hacks or through UA detection. ([example](https://www.npmjs.com/package/can-autoplay?activeTab=readme), [more examples](https://github.com/search?q=canAutoPlay+language%3AJavaScript&type=code&l=JavaScript)). This doesn't expose new information for fingerprinting (see https://github.com/w3c/autoplay/issues/24) as media elements already expose through events which media will autoplay by trying to autoplay.

**Comment by martinthomson** [comment]
Tagged.  I initially had concerns about the API being synchronous, but it seems like information like that needs to be available synchronously anyway.

I think that we can avoid a dashboard entry for this.  Though it is a spec in its own right, it's a trivial one.
