### ISSUE TITLE
CHIPS (Cookies Having Independent Partitioned State)

### ISSUE THREAD

**Issue by johannhof** [mozilla/standards-positions#678]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CHIPS (Cookies Having Independent Partitioned State)
* Specification or proposal URL: https://github.com/privacycg/CHIPS
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @bvandersloot-mozilla, @martinthomson 

### Other information

CHIPS is a proposal for a new cookie attribute, Partitioned. This attribute will indicate to user agents that these cross-site cookies should only be available in the same top-level context that the cookie was first set in.

CHIPS has been discussed in PrivacyCG and beyond for a while, and participants from other browsers including Firefox have generally signaled support so far (with a few details to figure out), see https://github.com/privacycg/proposals/issues/30.

The TAG Review reached an [overall positive conclusion](https://github.com/w3ctag/design-reviews/issues/654#issuecomment-1218145338)

**Comment by johannhof** [comment]
cc @DCtheTall @krgovind

**Comment by johannhof** [comment]
WebKit position issue: https://github.com/WebKit/standards-positions/issues/50

**Comment by bvandersloot-mozilla** [comment]
We are going to mark this as "positive" via #682.

A key piece of this decision is the behavior of a cookie when the Partitioned attribute is not provided being left up to the implementer. This allows us to continue deployment of partitioning by default while not forcing other browsers to change their default cookie behavior immediately.

**Comment by johannhof** [comment]
Great, thank you for the update, @bvandersloot-mozilla! I agree that we should preserve this condition for browsers.
