### ISSUE TITLE
HTML: enterkeyhint attribute

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#68]
In https://github.com/whatwg/html/pull/3538 a new attribute is proposed for all elements. It allows the page to control the visual label of the virtual keyboard enter key to some extent (it's an enum) when a visual keyboard is shown for that element (e.g., when it's editable and focused).

**Comment by bzbarsky** [comment]
Note that we already support such a thing as "moz-actionhint".

In general, this seems ok to me, modulo naming...

**Comment by domenic** [comment]
If folks want to chip in on the name, now's the time. Current plan is `inputactionlabel`.

**Comment by bzbarsky** [comment]
I just asked some questions about how this is supposed to work in practice in https://bugzilla.mozilla.org/show_bug.cgi?id=1490661#c4

**Comment by sideshowbarker** [comment]
This was renamed to `enterkeyhint` (so maybe change the issue title here?) and is now in the HTML standard:

* https://github.com/whatwg/html/commit/a5422d984d9b7b8a4e0ad7a0ad237b07f190cc93
* https://html.spec.whatwg.org/multipage/interaction.html#attr-enterkeyhint

> The `enterkeyhint` content attribute is an enumerated attribute that specifies what action label (or icon) to present for the enter key on virtual keyboards. This allows authors to customize the presentation of the enter key in order to make it more helpful for users.

* Intent to Ship for Chrome: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Hfe5xktjSV8/Re-SMF3wAwAJ
* Mozilla feature bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1490661
* Safari feature bug: https://bugs.webkit.org/show_bug.cgi?id=189546
