### ISSUE TITLE
AudioContext.setSinkId()

### ISSUE THREAD

**Issue by ajay-rah** [mozilla/standards-positions#683]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: AudioContext.setSinkId()
* Specification or proposal URL: https://github.com/WebAudio/web-audio-api/pull/2498
* Caniuse.com URL (optional): n/a
* Bugzilla URL (optional): n/a
* Mozillians who can provide input (optional): @padenot

**Comment by padenot** [comment]
We're `positive` and actively participating in the standard and have quite a lot of the implementation ready. I'll note that the spec is not finished yet, but almost there. Some details are to be determined still.
