### ISSUE TITLE
Style Container Queries (for custom properties)

### ISSUE THREAD

**Issue by lilles** [mozilla/standards-positions#686]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Containment Module Level 3
* Specification or proposal URL: https://drafts.csswg.org/css-contain-3/#style-container
* Mozillians who can provide input (optional): @emilio 

### Other information

Issue #118 was asking for size container queries. Filing a new request since style() queries are assumed to not be covered by that request.

Style queries can be used to style an element based on querying the computed style values of a parent element or a named ancestor element.

Chrome currently has an implementation for custom property queries behind a flag and it would be good to have separate positions on custom and standard property queries separately if applicable.

**Comment by woody-li** [comment]
Webkit maked their position as support for custom properties.
What about Mozilla?

**Comment by matuzo** [comment]
Are there any news or can we follow the status elsewhere?

**Comment by emilio** [comment]
Style queries for custom props seem uncontroversial to me. I guess we'll see how useful they are in practice, but yeah, neutral or support seems fine to me.

**Comment by nileshprajapati** [comment]
Safari has enable Style queries by default https://github.com/WebKit/WebKit/pull/24251

**Comment by zcorpan** [comment]
`positive` per @emilio's comment above.

**Comment by woody-li** [comment]
Safari has shipped it at [TP 190](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-190#CSS)

What's more, it's very useful for Web Components.
May resolve styles across shadowDom or slot. Such as :host-context(), :has-slotted(), etc.

Hope it will be implemented in Firefox.

**Comment by jogibear9988** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1795622

**Comment by Msherzai522** [comment]
emojis

**Comment by Msherzai522** [comment]
it usefully
