### ISSUE TITLE
CustomStateSet for custom elements

### ISSUE THREAD

**Issue by calebdwilliams** [mozilla/standards-positions#688]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title:  Exposing custom element states
* Specification or proposal URL: https://wicg.github.io/custom-state-pseudo-class/#customstateset
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

This provides an API to allow custom element authors a way to expose internal state to the DOM for matching operations (including CSS and things like `document.querySelector`).

This is done via the ElementInternals.prototype.states, which is a set of custom states. A naive example would be

```javascript
class FancyElement extends HTMLElement {
  constructor() {
    super();
    const internals = this.attachInternals();

    this.internals.states.add('--fancy');
  }
}

customElements.define('fancy-element', FancyElement);
```

This would mean that a newly-constructed instance of fancy-element would match against :--fancy.

**Comment by bgrins** [comment]
Is the [explainer](https://github.com/WICG/custom-state-pseudo-class/blob/main/explainer.md) out of date? the code sample there doesn't use the `--` prefixed syntax, for example

**Comment by calebdwilliams** [comment]
It very well could be. Chrome shipped this with feature requiring the double-dash prefix presumably to avoid collisions with future DOM state matches that might need to be built in.

**Comment by keithamus** [comment]
I can't comment on if Mozilla supports the proposal or not, but there is an intent to prototype (https://groups.google.com/u/1/a/mozilla.org/g/dev-platform/c/vDVxI6O3YqU) and there is an experimental implementation behind a flag in Nightly. 

I'll also add that the new selector takes the shape of `:state(fancy)` rather than `:--fancy`.

**Comment by zcorpan** [comment]
cc @emilio @EdgarChen

**Comment by emilio** [comment]
This looks sensible to me. Positive?

**Comment by zcorpan** [comment]
Do we need a dashboard entry here?

**Comment by emilio** [comment]
I could go either way. It's not a particularly big feature imo.
