### ISSUE TITLE
Request for position on WebAuthentication Conditional UI

### ISSUE THREAD

**Issue by nsatragno** [mozilla/standards-positions#692]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebAuthentication Conditional UI
* Specification or proposal URL:
  * Conditional UI is part of the wider WebAuthn spec: https://w3c.github.io/webauthn/#GetAssn-ConditionalMediation-Interact-FormControl
  * Explainer: https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI
  * PR: https://github.com/w3c/webauthn/pull/1576
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): dveditz@mozilla.com

**Comment by dveditz** [comment]
This is a thoughtful proposal that addresses real usability issues that make it difficult for sites to transition to WebAuthn, while honoring user privacy. We should support this.

Note: this is useful for Web Authn Level 2 "discoverable keys", too. It's not just for multi-device "passkeys"
