### ISSUE TITLE
CSS Nesting Module Level 1

### ISSUE THREAD

**Issue by lilles** [mozilla/standards-positions#695]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Nesting Module Level 1
* Specification or proposal URL: https://drafts.csswg.org/css-nesting/
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1648037

### Other information

There have been some discussions in the CSSWG around the syntax indicating there could be changes in the spec. The plan is to do an initial implementation behind a flag with the spec's current syntax in Blink.

**Comment by emilio** [comment]
In general this seems worth prototyping. I have some concerns about CSSOM and so on and I wonder if it'd be easier to make it a parse-time expansion (like SASS / etc do...), but that's something that pretty much needs prototyping and experience to decide so...

**Comment by bgrins** [comment]
Marking this as positive based on Emilio's comment and feedback from Tantek. This seems useful and worth prototyping.

**Comment by lilles** [comment]
> In general this seems worth prototyping. I have some concerns about CSSOM and so on and I wonder if it'd be easier to make it a parse-time expansion (like SASS / etc do...), but that's something that pretty much needs prototyping and experience to decide so...

FYI @sesse (who has started prototyping and has concerns in that area too)

**Comment by SebastianZ** [comment]
This issue was closed without actually adding an entry for it to the list. I know Mozilla is actively working on the feature and will ship it soon, though maybe it's still worth adding it to the standards positions.

Sebastian
