### ISSUE TITLE
Conditional Focus

### ISSUE THREAD

**Issue by eladalon1983** [mozilla/standards-positions#697]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Conditional Focus
* Specification or proposal URL:
  * Generally, it's in: https://www.w3.org/TR/screen-capture/#dom-capturecontroller-setfocusbehavior
  * The two PRs that introduced this are:
    * https://github.com/w3c/mediacapture-screen-share/pull/235/files
    * https://github.com/w3c/mediacapture-screen-share/pull/240/files
* Mozillians who can provide input (optional): @jan-ivar

**Comment by jan-ivar** [comment]
I'm supportive of this API, and after internal solicitation received no objections.

**Comment by martinthomson** [comment]
Marked as positive, but not much point in putting something this granular on the dashboard.
