### ISSUE TITLE
The Popover API

### ISSUE THREAD

**Issue by mfreed7** [mozilla/standards-positions#698]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: The Pop-Up API
* Specification or proposal URL: https://github.com/whatwg/html/pull/8221
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Explainer: https://open-ui.org/components/popup.research.explainer
* Incubation: OpenUI. See [issues discussed/resolved](https://github.com/openui/open-ui/issues?q=is%3Aissue+label%3Apopup+-label%3Apopup-spec+-label%3Apopup-v2).
* Mozillians who can provide input (optional): @emilio, @tantek, @smaug----

**Comment by zcorpan** [comment]
After discussing with @emilio I think this should be labeled "positive". It also warrants a dashboard entry imo. I'll leave this open for a week to allow for other comments.

**Comment by mfreed7** [comment]
> After discussing with @emilio I think this should be labeled "positive". It also warrants a dashboard entry imo. I'll leave this open for a week to allow for other comments.

Awesome news! Thanks!
