### ISSUE TITLE
CSS lh and rlh units

### ISSUE THREAD

**Issue by lilles** [mozilla/standards-positions#699]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Values and Units Module Level 4
* Specification or proposal URL: https://www.w3.org/TR/css-values-4/#lh
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1310170
* Mozillians who can provide input (optional): @emilio

### Other information

Blink plan to ship lh first (without rlh, just practical reasons), but asking for position on both.

**Comment by emilio** [comment]
I guess I'm still sad that we shrugged off https://github.com/w3c/csswg-drafts/issues/3257, but alas. It seems fine other than that really.

**Comment by dholbert** [comment]
Yeah, I think we can call this "worth prototyping".
