### ISSUE TITLE
RFP: TransformStreams (part of the Streams Standard)

### ISSUE THREAD

**Issue by domenic** [mozilla/standards-positions#70]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Streams Standard
* Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1493537
* Specification or proposal URL: https://streams.spec.whatwg.org/#ts

### Other information

Mozilla has been a great contributor to the streams API in general. We were hoping to get a sense of how they (probably specifically folks like @wanderview and @tschneidereit) were feeling about the TransformStreams section.

**Comment by annevk** [comment]
Potential usage: https://github.com/whatwg/encoding/issues/72 (exposed) and https://github.com/whatwg/fetch/issues/450 (probably not exposed).

**Comment by annevk** [comment]
@tschneidereit @wanderview I suspect we want to mark this as `worth prototyping` if not `important`, right?

**Comment by tschneidereit** [comment]
> I suspect we want to mark this as worth prototyping if not important, right?

Yes, I fully agree. I think streams only truly shine with transform streams. With those, they have the potential to become an important building block for development. So my vote is for marking them as `important`.

**Comment by wanderview** [comment]
> @tschneidereit @wanderview I suspect we want to mark this as worth prototyping if not important, right?

Agree.
