### ISSUE TITLE
Content-type in Resource Timing

### ISSUE THREAD

**Issue by abinpaul1** [mozilla/standards-positions#705]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Content-type in Resource Timing
* Specification or proposal URL: 
   - Explainer: https://github.com/abinpaul1/resource-timing/blob/explainer-content-type/Explainers/Content-Type.md
   - Spec PR : https://github.com/w3c/resource-timing/pull/341
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1800443
* Mozillians who can provide input (optional): @bdekoz @sefeng211

### Other information

Link to entry on the Chrome Platform Status: https://chromestatus.com/feature/5156068351541248

**Comment by sefeng211** [comment]
This looks reasonable to me! 

It'd be great to get another confirmation from @bdekoz

**Comment by zcorpan** [comment]
I've discussed with @bdekoz, concluded "positive"
