### ISSUE TITLE
Request for Position: Canvas Floating Point Color Types

### ISSUE THREAD

**Issue by ccameron-chromium** [mozilla/standards-positions#708]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Canvas Floating Point Color Types
* Specification or proposal URL: https://github.com/w3c/ColorWeb-CG/blob/master/canvas_float.md
* Mozillians who can provide input (optional): kdashg

**Comment by kdashg** [comment]
Mozilla is Positive on this addition.
Having a solution for greater-than-unorm8 precision (and ideally >1.0 values for working with differing color spaces) is important as we move into having better color support than 8-bit srgb.

**Comment by bgrins** [comment]
Marking positive as discussed

**Comment by mdrejhon** [comment]
Related at MDN, but I spent a few hours untangling HDR dependencies at https://bugzilla.mozilla.org/show_bug.cgi?id=1539685#c34 -- There's a lot of reverse dependencies at this 6-year-old tracking entry.  This may somewhat accidentally discourage potential volunteer Mozilla developers, so I add this link here for completeness' sake.

<details>

(In reply to Mark Rejhon from comment #34)
> ## Helping Simplify Dependency Tree
> 
> This will help volunteer open source developers trying to find out where to start in implementing HDR.  (TL;DR: Go to #1889288)
> 
> I know this is a META tracker.  However, the dependancy tree seems messed up with lots of horses-before-carts from many people submitting different HDR bugzilla reports at different times in the past, confusing a lot of us what comes first.  To help y'all (I may even throw in a cash bounty this summer, waiting for funding, but don't wait for me).  
> 
> Allow me to clean up the dependency graph and show proofs that #1889288 is the main dependancy -- the mother of all bedrocks dependency --that blocks HDR sub-items and sub-features.  Also from what I looked, a Mozilla developer to begin #1889288 (at least for Windows platforms) without waiting for any of the items in this meta tracker, because everything in this meta tracker depends on the more recently-created #1889288.  So the egg happened before the chicken in this instance; creating a confusion for potential new Mozilla developers who don't know where to begin for HDR.  HDR video is too bright on macOS (over exposure).  Therefore, this reply is designed to reduce friction by helping disambiguate this messy HDR dependency tree:
> 
> On the outstanding items in DependsOn/Blocks:
> 
> DependsOn 1743824 - https://bugzilla.mozilla.org/show_bug.cgi?id=1743824
> - "h264 video with pixel format yuv420p10le is either not played, played with visual glitches, or played perfectly, depending on the platform"
> - *That's not a HDR item.*
> - **DELETE from HDR meta tracker**
> 
> DependsOn 1793091 - https://bugzilla.mozilla.org/show_bug.cgi?id=1793091
> - "HDR images are rendered extremely dark"
> - *My assessment of why: This is because HDR images are downconverted to SDR because the base Gecko framebuffer is not yet HDR, the goal of #1889288*
> - **1793091 is dependant on solving #1889288** 
> 
> DependsOn 1948317 - https://bugzilla.mozilla.org/show_bug.cgi?id=1948317
> - "YouTube HDR Brightness Problem"
> - *My assessment of why: This is because HDR video are downconverted to SDR because the base Gecko framebuffer is not yet HDR, the goal of #1889288*
> - **1948317 is dependant on solving #1889288** 
> - **1948317 does not depend on this meta item other than #1889288**
> 
> DependsOn 1948583 - https://bugzilla.mozilla.org/show_bug.cgi?id=1948583
> - "imageData does not support color space"
> - *Chrome imageData does not support colorspace even for Canvas2D HDR. And VIDEO/WebGPU HDR doesn't require imageData, nor AVIF embeds. Not a blocker for HDR!*
> - **1948583 does not depend on this meta item other than #1889288**
> 
> DependsOn 1949088 - https://bugzilla.mozilla.org/show_bug.cgi?id=1949088
> - "HEVC 10-bit playback washed out."
> - *My assessment of why: This is because HDR video are downconverted to SDR because the base Gecko framebuffer is not yet HDR, the goal of #1889288*
> - **1949088 is dependant on solving #1889288** 
> - **1949088 does not depend on this meta item other than #1889288**
> 
> DependsOn 1952603 - https://bugzilla.mozilla.org/show_bug.cgi?id=1952603
> - "HDR video is too bright on macOS (over exposure)"
> - *This is usually a colorspace mismatch issue. Addressing the multiple HDR colorspaces in #1889288 is likely to fix this*
> - **1952603 does not depend on this meta item other than #1889288**
> 
> DependsOn wr-video-color - https://bugzilla.mozilla.org/show_bug.cgi?id=1494381
> - "[meta] [project] Proper colorspace support and color rendering for video playback"
> - *On many platforms, HDR video playback will depend on the entire Gecko browser framebuffer (for everything/text/images/video) supporting HDR.  That's the purview of #1889288, I believe*
> 
> DependsOn hdr-video-linux - https://bugzilla.mozilla.org/show_bug.cgi?id=1642854
> - "https://bugzilla.mozilla.org/show_bug.cgi?id=1642854"
> - *Oh boy, yes. Linux will need lots of HDR catching up; and I'm glad to see very active work there. But it's not a blocker for continued Windows/Mac/Android/iOS/etc HDR implementations. The way it's bugzilla'd currently suggests Linux HDR support is blocking Windows/Mac; but that's not true.  #1889288 can easily proceed on the Windows platform unfettered from the dependency hell at #1642854, from a quick check that I did*
>  
> DependsOn hdr-video-windows - https://bugzilla.mozilla.org/show_bug.cgi?id=1902427
> - "[meta] Add HDR video playback support on Windows"
> - *It has a few dependencies (1711812, 1750660, 1832971, 1898591) like distorted video, typically HDR misdownconverted to SDR and similar, which all seem mostly actually dependant on #1889288 except for the overlay technique at "Add HDR tone mapping for playing HDR through video overlay on Windows".  However, most modern ways of playing videos on Windows do not necessarily use the video-overlay technique (except in certain situations, e.g. HDCP-protected video which is usually played fullscreen anyway).  Most browsers including FireFox now use the GPU-accelerated compositor approach, where the final browser framebuffer contains a copy of the video frame composited within (that's why it's all screenshottable normally).  Preserving HDR in video composited into the Gecko browser framebuffer requires solving item #1889288...*  
> 
> DependsOn hdr-images-windows - https://bugzilla.mozilla.org/show_bug.cgi?id=1918773
> - "[meta] HDR image display on Windows"
> - **Obviously requires the HDR gecko compositor at #1889288**
> 
> Blocks 1722790 - https://bugzilla.mozilla.org/show_bug.cgi?id=1722790
> - "Support "Optimize video streaming while on battery" (Play HDR as SDR on battery)"
> - *This is a 4-year-old item that probably should be simplified as a HDR/SDR Gecko-wide efficiency mode switch, not video-specific.  A Gecko-wide HDR/SDR switch would be handled by dependencies closer to #1889288*
> 
> Blocks wr-hdr - https://bugzilla.mozilla.org/show_bug.cgi?id=1889288
> - "[meta] [project] Implement WR functionality needed for HDR"
> - Basically, the entire Gecko engine (framebuffer of Gecko) needing to support HDR, before you can composite HDR stuff into it (VIDEO buffers, WebGPU HDR buffers, HDR AVIF images, HDR JXL images, and other HDR pixels).  Basically whenever the screen is in HDR mode, Gecko using a 48-bit final-compositor HDR framebuffer instead of 24-bit RGB framebuffer.  Children elements may be in various colorspaces (including RGB) but the final window rectangle (framebuffer of the viewport) is all HDR 48-bit pixels in Chrome(129+)/Edge(129+)/Brave(129+)/Safari(TechPreview215+) -- because that essentially handles things this way to do high-performance HDR compositing, even doing SDR graphics within the HDR framebuffer (e.g. the text parts of a HDR page).
> - I declare #1889288 the bedrock item for adding HDR support to Windows.
> 
> If any open source developers are deciding where to begin; then here we go!

</details>
