### ISSUE TITLE
Request for Position: TLS ClientHello extension permutation

### ISSUE THREAD

**Issue by dadrian** [mozilla/standards-positions#709]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: TLS ClientHello extension permutation
* Specification or proposal URL: https://github.com/dadrian/clienthello-randomization/blob/main/EXPLAINER.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1789436
* Mozillians who can provide input (optional): Dennis Jackson

### Other information

TLS RFC, Section 4.2: https://www.rfc-editor.org/rfc/rfc8446#section-4.2
https://groups.google.com/a/chromium.org/g/blink-dev/c/zdmNs2rTyVI/m/MAiQwQkwCAAJ
https://groups.google.com/a/chromium.org/g/blink-dev/c/bYZK81WxYBo

**Comment by martinthomson** [comment]
As Dennis already indicated on the blink-dev thread, we're positive on this one.

As I can also claim some authority here - and I agree with Dennis - I'm just going to close this out directly.  Thanks for filing the issue @dadrian.

**Comment by fippo** [comment]
@martinthomson would you extend that to *D*TLS (mostly WebRTC) too?

(trying to avoid filing a new issue)

**Comment by martinthomson** [comment]
For us, the TLS and DTLS implementations are generally treated the same.  Our version of this feature will be applied to DTLS handshakes in the same way as TLS handshakes.  There can be important differences -- which we will sometimes miss -- but I don't believe that applies in this case.

Consider this position to apply to DTLS and TLS equally.
