### ISSUE TITLE
chore: extract labeled issue positions

### ISSUE THREAD

**Issue by bgrins** [mozilla/standards-positions#710]
Since we now support labeling and closing as an alternative to filing a PR to show up on the dashboard (https://mozilla.github.io/standards-positions/) via https://github.com/mozilla/standards-positions/blob/main/activities.json, it would be helpful for consumers to have a single source of truth that includes all positions without having to dig into individual issue UI or work with github APIs.

I'm imagining we'd have an action on commit that either:
1) Insert labeled-and-closed issues directly into activities.json, keeping the a subset of the fields, like `mozPosition`. `mozPositionIssue`, `title`. Then either have a new field to indicate it shouldn't show up on the dashboard, or use the absence of one of the others.
2) Makes a new file that's shaped kinda like (1) where we reflect the more elaborate positions from activities.json into the simpler format. This wouldn't be used for dashboard generation at all and may be object keyed on the issue number for easy lookup.

I lean towards (2) - since (1) continues to be human edited activities.json can stay shorter and have less chance of a merge conflict when someone wrote a PR. It would also have less interference with other build tasks.

The other question is should we include "all" issues (including those that haven't been labeled) so there's an explicit record of non-position - as opposed to relying on something not being present. That may seem a little weird for issues like this one where it's not a request at all - perhaps we'd start labeling those to exempt them from the build.

**Comment by bgrins** [comment]
Implementation-wise we could probably use something like https://github.com/dogsheep/github-to-sqlite to handle the interaction with the API (handling pagination, etc)

**Comment by zcorpan** [comment]
I don't mind too much about the implementation details, but I think these properties would be good:

* All issues should have the appropriate labels, and match with the dashboard.
* All info in the dashboard should be available in the github issue, such that the github issue can be considered to be the source of truth.
* There should be no need to edit JSON to create a new dashboard entry or edit a dashboard entry. Editing labels and a comment in the github issue (by a user with repo write access) seems like lower friction.

**Comment by zcorpan** [comment]
Fixed by https://github.com/mozilla/standards-positions/pull/1063.
