### ISSUE TITLE
Request for Position: Fullscreen Popup Windows

### ISSUE THREAD

**Issue by bradtriebwasser** [mozilla/standards-positions#714]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Fullscreen Popups
* Specification or proposal URL: https://github.com/bradtriebwasser/fullscreen-popup/blob/main/EXPLAINER.md

### Introduction
This proposal introduces the ability for web applications to open a fullscreen popup window, without the need for a separate calls to [`Window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) and [`Element.requestFullscreen()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen).

The proposed enhancement would allow web applications to create a fullscreen popup window on a target display from a single user activation. The [window placement permission](https://webscreens.github.io/window-placement/#api-permissions) will be required for these capabilities.

### Problem and Use Cases
Web applications are limited in the ways that they can [Initiate Multi-Screen Experiences](https://github.com/w3c/window-placement/blob/main/EXPLAINER_initiating_multi_screen_experiences.md) across multi-display configurations. Specifically, opening a popup and transitioning the window to fullscreen typically requires two separate user gestures (depending on brower popup blocking settings). This results in a cumbersome user experience for web applications which utilize multiple displays.

Multiple partners and early adopters of the [Multi-Screen Window Placement API](https://w3c.github.io/window-placement/) have specifically requested the ability to show one or more fullscreen popups from a single user gesture, to avoid the user friction entailed with making separate gestures to create each window and make each window fullscreen. For example:

https://github.com/w3c/window-placement/issues/7
https://github.com/w3c/window-placement/issues/98#top
https://github.com/w3c/window-placement/issues/92.

Some basic illustrative examples which may be achieved with this proposal are listed below:

* Video streaming app launches a video directly to fullscreen on a separate display.
* 3D modeling app launches a preview in fullscreen on a separate display.

### Proposal
Allow sites with the `window-management` permission to open a fullscreen window on a specified display from a single user gesture. Scripts calling [window.open()](https://html.spec.whatwg.org/multipage/window-object.html#dom-open-dev) to request a popup window could also include a new fullscreen boolean window feature.

Fullscreen popup requests could also include window bounds features (e.g. left, top, width, height), with positions specified [relative to the multi-screen origin](https://w3c.github.io/window-placement/#api-window-attribute-and-method-definition-changes), to request that the window be made fullscreen on the screen containing those bounds, and also to be used as the popup window bounds after exiting fullscreen.

#### Example Code
Basic Example:
```js
window.open(url, '_blank', 'popup,fullscreen');
```

**Comment by michaelwasserman** [comment]
Chromium is no longer pursuing this feature directly; see the superseding Request for Position in Issue #1020.

**Comment by martinthomson** [comment]
Thanks @michaelwasserman, we'll just close this then.
