### ISSUE TITLE
Request for re-opening the Request for position on JPEG XL

### ISSUE THREAD

**Issue by jonsneyers** [mozilla/standards-positions#721]
The Request for position on JPEG XL (https://github.com/mozilla/standards-positions/issues/522) was closed one year ago because it had "passed the new information stage".

However, I think new information is available at this point, and it would be useful to add it to that thread. For example, the "works across the workflow" argument that was originally raised in a rather hypothetical/theoretical fashion, has now materialized in the form of, amongst others, Adobe, Serif, Krita, Gimp and darktable adding support for JPEG XL in their products.
Also, the proposal to add JPEG XL support has meanwhile been raised and is being discussed in the Mozilla Connect Community too: https://connect.mozilla.org/t5/ideas/support-jpeg-xl/idi-p/18433

I think it would therefore make sense to re-open this thread so new information can be added, perhaps with a warning that it is not intended for general advocacy but only to report factually on new evidence of adoption and other new elements that are of interest for Mozilla to take a position.

**Comment by martinthomson** [comment]
Hi @jonsneyers, thanks for engaging here.  We've reached a conclusion on #522.  Unfortunately, the level of advocacy relative to the level of new information got unmanageable for us, so we had to lock it.

We do follow market adoption of different technologies and that does influence product decisions, but we try to limit the extent to which the positions we take here are affected by such dynamics.

**Comment by jthoward64** [comment]
> Hi @jonsneyers, thanks for engaging here. We've reached a conclusion on #522. Unfortunately, the level of advocacy relative to the level of new information got unmanageable for us, so we had to lock it.
> 
> We do follow market adoption of different technologies and that does influence product decisions, but we try to limit the extent to which the positions we take here are affected by such dynamics.

> So we don't see support for JPEG-XL as either good or bad for the Web. We might find it necessary to support the format *if usage becomes more widespread*, but that will be a product decision[1](https://github.com/mozilla/standards-positions/issues/522#user-content-fn-1-172a0635b7cb82d2833feed0c7670948).

There has been some more progress on JpegXL with WebKit [bringing in support](https://webkit.org/blog/14205/news-from-wwdc23-webkit-features-in-safari-17-beta/#images) with v16, I know this is a bit of a chicken and the egg situation with use of JXL and browser implementations, but there has been some good discussion over on [the web platform tests' interop repo](https://github.com/web-platform-tests/interop/issues/430#issue-1899100775)) that may be relevant.
