### ISSUE TITLE
Request for position: Interim response timings in resource timing

### ISSUE THREAD

**Issue by noamr** [mozilla/standards-positions#722]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Adding interim response info to resource timing
* Specification or proposal URL:  https://github.com/w3c/resource-timing/pull/366 and https://github.com/whatwg/fetch/pull/1483
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by yoavweiss** [comment]
^^ @bdekoz @bas-moz

**Comment by bdekoz** [comment]
this seems worth prototyping, I've added a Moz tracker bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1811291
