### ISSUE TITLE
Request for position: CSS root font units

### ISSUE THREAD

**Issue by danielsakhapov** [mozilla/standards-positions#725]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Values and Units Module
* Specification or proposal URL: https://drafts.csswg.org/css-values/#font-relative-lengths
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1740584

### Other information
Request specifically for rex, rch, ric, rlh, rcap.

**Comment by bgrins** [comment]
cc @jfkthame @emilio

**Comment by bgrins** [comment]
This seems reasonable to me, and confirmed the same with Emilio. Will leave this open for a bit to see if jfkthame wants to weigh in.

**Comment by jfkthame** [comment]
Nothing in particular to add; this seems fine.
