### ISSUE TITLE
Request for Mozilla Position: baseline-source CSS property.

### ISSUE THREAD

**Issue by bfgeek** [mozilla/standards-positions#727]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Inline 3 - baseline-source property.
* Specification or proposal URL: https://drafts.csswg.org/css-inline-3/#baseline-source
* Mozillians who can provide input (optional): @dholbert ?

### Other information

This covers just the baseline-source property, which has three values `auto` (the default), `first`, and `last`.
See here for an example of this being used: https://twitter.com/bfgeek/status/1612518098611089408

**Comment by dholbert** [comment]
This seems worth implementing and shipping, yeah.

A few links for reference:
* The spec text was added back in 2019, in https://github.com/w3c/csswg-drafts/issues/861#issuecomment-494961117
* Blink's intent-to-ship is in https://groups.google.com/a/chromium.org/g/blink-dev/c/gLNyu0lTRS0/m/yHcJhlDMBgAJ
* We have https://bugzilla.mozilla.org/show_bug.cgi?id=1805273 filed on the WPT test failures, but I'll file a cleaner bug on the feature itself.

**Comment by martinthomson** [comment]
Sounds like a resolution to me.  Thanks both.  (If you think we need this on a dashboard, tell me, but this seems small.)
