### ISSUE TITLE
Request for Position: FileSystemFileHandle.move() for local files

### ISSUE THREAD

**Issue by a-sully** [mozilla/standards-positions#732]
## Request for Mozilla Position on an Emerging Web Specification

* Specification or proposal URL: https://github.com/whatwg/fs/pull/10 (though that currently specifies directory moves, too)
  * Explainer: https://github.com/a-sully/fs/pull/2
* Mozillians who can provide input: @jesup

### Other information

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/805
* WebKit standards-positions issue: https://github.com/WebKit/standards-positions/issues/121

This is specifically asking for input for moving/renaming ___local___ (i.e. not in the Origin Private File System - which is already shipped) ___files___ (not directories - which is different enough that it will have a separate explainer)

**Comment by jesup** [comment]
While we're supportive of move() for files (and directories) in OPFS, we're negative on manipulations/access of local user files in general, so that would apply here as well.

**Comment by martinthomson** [comment]
Thanks @a-sully for asking and @jesup for the response.
