### ISSUE TITLE
Request for position: new dialog initial focus algorithm

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#734]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: New dialog initial focus algorithm
* Specification or proposal URL: https://github.com/whatwg/html/pull/8199
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1811129
* Mozillians who can provide input (optional):

**Comment by zcorpan** [comment]
I think the change is good and should make dialog behave closer to what users expect, based on comments from the a11y community.

@jcsteh said
> I took a look at the proposal; I hadn't seen the most recent work yet. I think this is good. It's not perfect for every case, but I don't think anything can be and I think a lot of great work has been done to try to balance the various concerns. Aside from the new initial focus steps, the "should" for authors explicitly setting autofocus is great in that it communicates that authors are expected to think about where focus lands.

In conclusion, we're positive. No dashboard entry needed.
