### ISSUE TITLE
Request for position: The Language Pseudo-class: :lang() (Selectors Level 4)

### ISSUE THREAD

**Issue by rogerzanoni** [mozilla/standards-positions#735]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: The Language Pseudo-class: :lang() (Selectors Level 4)
* Specification or proposal URL: https://www.w3.org/TR/selectors-4/#the-lang-pseudo
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1121792
* Mozillians who can provide input (optional): 

### Other information

Chromium status entry: https://chromestatus.com/feature/5071058079055872
In-progress implementation for chromium: https://chromium-review.googlesource.com/c/chromium/src/+/3515958
Explainer: https://github.com/rogerzanoni/docs/tree/main/lang-level-4

**Comment by foolip** [comment]
There's an Intent to Ship for Blink now:
https://groups.google.com/a/chromium.org/g/blink-dev/c/tO598HXuS94/m/x8rIA38aBgAJ

**Comment by jfkthame** [comment]
While in principle I think this is reasonable, I'm concerned that the current webkit implementation, and its associated (webkit-internal, not currently WPT) tests deviates pretty severely from the spec text. As such, there's work to be done on the spec/test side to ensure we have a solid basis for interoperability.

(I posted a comment -- currently pending moderation -- to the Blink I2S thread, though the situation looks a lot worse than I initially realized and mentioned there. Basically, the spec references BCP47 for what it means to "match", but webkit and its tests seem to accept all kinds of "garbled" tags that are not well-formed per BCP47 and therefore, IMHO, cannot possibly match. I think we should push back against that behavior.)

**Comment by zcorpan** [comment]
@jfkthame can you file an issue about it for the CSS WG?

**Comment by jfkthame** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/8720

**Comment by zcorpan** [comment]
Thanks. I suggest `positive` for this feature.

**Comment by jfkthame** [comment]
Agreed. (Note also our recent Intent to Prototype/Ship: https://groups.google.com/a/mozilla.org/g/dev-platform/c/ynb0ZQFk0l4, and patches landed in bug [1121792](https://bugzilla.mozilla.org/show_bug.cgi?id=1121792).)
