### ISSUE TITLE
Never Unpartition Storage APIs via the Storage Access API

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [mozilla/standards-positions#737]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Always Partition Storage
* Specification or proposal URL: [Storage Access API, Section 3.4](https://privacycg.github.io/storage-access/#storage)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @bvandersloot-mozilla 

### Other information

The Storage Access API has been formalized to not affect Storage APIs, instead restricting its effects to cookies. This newly written section reflects that. Historically the Gecko implementation has unpartitioned all Storage along with cookies.

**Comment by bvandersloot-mozilla** [comment]
That would be for the entirety of the Storage Access API, of which this is an update to the draft spec. The entire spec is currently undergoing TAG review and has one more substantive PR to land, but is looking to graduate once those are done. I'd estimate in the next 3 months, based on conversations with co-editors, but admitting that I've never gone through the process before :)

**Comment by bgrins** [comment]
The argument for this particular change makes sense, and it's good to hear that the feature as a whole is in flight to WHATWG. Marking as positive and closing.
