### ISSUE TITLE
Meta: add issue template fields/templates to explain the maturity of the spec

### ISSUE THREAD

**Issue by jyasskin** [mozilla/standards-positions#739]
In discussing with @tantek, it seems like you want Chrome to file standards positions around the time we have IDL and an API shape (which we usually do inside the explainer, roughly during [step 2 of the Blink process](https://www.chromium.org/blink/launching-features/#step-2-prototyping)), which is often before we write a specification (roughly the [end of step 4 or early in step 5](https://www.chromium.org/blink/launching-features/#step-4-widen-review)). If that's accurate, this repo's [issue template (or templates)](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) should have a field where we can say whether the URL refers to an explainer or full specification, and probably the rough timeline we expect before we'd want to ship something.

**Comment by zcorpan** [comment]
Thanks for filing.

I think we could have separate fields for explainer and spec URL, where the latter is either link to spec PR or the relevant spec section (there might be several links, too).

Timeline for shipping also seems useful. Maybe yeah+month and optionally additional info (like Chromium milestone)?
