### ISSUE TITLE
Request for Position: Use `v` flag instead of `u` for HTML `pattern` attribute RegExps

### ISSUE THREAD

**Issue by mathiasbynens** [mozilla/standards-positions#745]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Use `v` flag instead of `u` for HTML `pattern` attribute RegExps
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/7908
* Explainer URL (if available): https://github.com/whatwg/html/pull/7908
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=pattern-v
* Mozillians who can provide input (optional): @codehag @iainireland 

### Other information

The proposed change to the HTML `pattern` attribute swaps the `u` RegExp flag for [the new `v` flag](https://github.com/tc39/proposal-regexp-v-flag), enabling the use of three new features:

- set notation
- string literal syntax
- Unicode properties of strings

The spec patch at [https://github.com/whatwg/html/pull/7908](https://github.com/whatwg/html/pull/7908) lists the potentially breaking changes. Some patterns that previously would compile, now throw an early error with the `v` flag — specifically those with a character class including either an unescaped special character or a double punctuator.

**We expect such patterns to be rare.** To validate those assumptions we’ve added two use counters to Chromium: `V8RegExpUnicodeSetIncompatibilitiesWithUnicodeMode` tracks patterns in any JavaScript `u` RegExps (not just those implicitly generated via the `pattern` attribute) that would throw if they were used with the `v` flag, and `HTMLPatternRegExpUnicodeSetIncompatibilitiesWithUnicodeMode` does the same thing for the smaller & more relevant set of RegExps that are compiled via the HTML `pattern` attribute.

Importantly, note that throwing patterns result in `inputElement.validity.valid === true` for any input value (as if the `pattern` attribute wasn’t present), so the only compatibility risk is that some value/pattern combinations that would previously result in `inputElement.validity.valid === false` now result in `inputElement.validity.valid === true`. So even if the UseCounters are non-zero, it could be that there is no actual breakage.

**Comment by zcorpan** [comment]
The web compat risk seems acceptable since the attribute fails open for form validation.

Proposed position: positive. No dashboard entry.

**Comment by codehag** [comment]
From my perspective, this will be in line with the change for regexp that we did in javascript. I support the proposed position from @zcorpan.
