### ISSUE TITLE
Request for Mozilla Position: `text-wrap: balance` CSS property.

### ISSUE THREAD

**Issue by kojiishi** [mozilla/standards-positions#755]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Text Level 4
* Specification or proposal URL (if available): https://w3c.github.io/csswg-drafts/css-text-4/#valdef-text-wrap-balance
* Explainer URL (if available): https://docs.google.com/document/d/16-T9gqCagJxcST6hcnneSb7qGunxXa37_UHYqMqhPL0/edit?usp=sharing
* Mozillians who can provide input (optional): @jfkthame ?

### Other information

This covers just the `text-wrap` property, with values `wrap` (initial) and `balance`. Other values need to wait for the spec to complete making the `white-space` to a shorthand. Please see the ["CSS" section of the explainer](https://docs.google.com/document/d/16-T9gqCagJxcST6hcnneSb7qGunxXa37_UHYqMqhPL0/edit#bookmark=id.c0zmfgo8wp8o).

**Comment by zcorpan** [comment]
Chromium Intent to Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/f5eLz6PIXaI/m/R__N3BdjAAAJ

**Comment by dholbert** [comment]
I'd call this worth-prototyping.

It's a relatively targeted feature, which fills a demonstrated gap in web layout technology, which is currently being filled by various text-balancing JS libraries.  Also nice that there's an upper-bound on the performance cost of the balancing analysis, via the explicitly-allowed fallback to `wrap` behavior for >10-line paragraphs (and the exact algorithm being UA-defined).

**Comment by zcorpan** [comment]
"worth prototyping" is now called "positive" :)

I agree. I think we should have a dashboard entry.

**Comment by dholbert** [comment]
(We have https://bugzilla.mozilla.org/show_bug.cgi?id=1731541filed on this, for reference.)
