### ISSUE TITLE
Request for Mozilla Position on RTCRtpReceiver.jitterBufferTarget

### ISSUE THREAD

**Issue by jan-ivar** [mozilla/standards-positions#756]
## Request for Mozilla Position

* Specification Title: RTCRtpReceiver extensions — `playoutDelay`
* Specification or proposal URL (if available): https://w3c.github.io/webrtc-extensions/#dom-rtcrtpreceiver-playoutdelay
* Explainer URL (if available): none found
* Caniuse.com URL (optional): none found
* Bugzilla URL (optional): https://bugzil.la/1592988
* Mozillians who can provide input (optional): @jan-ivar @padenot

### Other information

Chrome shipped `playoutDelayHint` (old name) in 2019 — Their intent to implement: https://groups.google.com/a/chromium.org/g/blink-dev/c/4W4orKqA3Rs

WPT: https://wpt.fyi/results/webrtc-extensions/RTCRtpReceiver-playoutDelayHint.html

**Comment by jan-ivar** [comment]
Given that we're shipping this API should we close this as positive?

**Comment by zcorpan** [comment]
Sounds reasonable to me!
