### ISSUE TITLE
Request for Mozilla Position: import conditions - supports()

### ISSUE THREAD

**Issue by CanadaHonk** [mozilla/standards-positions#761]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Cascading and Inheritance Level 4 - import conditions - supports()
* Specification or proposal URL (if available): https://www.w3.org/TR/css-cascade-4/#conditional-import
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1427715

### Other information
Blink bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1380321 - marked as started
Web platform tests: https://wpt.fyi/results/css/css-cascade/import-conditions.html

**Comment by zcorpan** [comment]
I think this seems good. We may want to check if there are complications for speculative parsing. @emilio @hsivonen

**Comment by CanadaHonk** [comment]
I already wrote a patch accepted by the way (waiting for a spec issue to get cleared up before push): https://phabricator.services.mozilla.com/D172995

**Comment by CanadaHonk** [comment]
This was shipped in Fx 115 so I think this can be closed as positive?
