### ISSUE TITLE
Transitions on specified discrete properties

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#763]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Transitions on specified discrete properties
* Specification or proposal URL (if available): https://github.com/w3c/csswg-drafts/issues/4441
* Explainer URL (if available): https://github.com/w3c/csswg-drafts/issues/4441#issuecomment-1329749962
* Caniuse.com URL (optional): none
* Bugzilla URL (optional): none
* Mozillians who can provide input (optional): none

### Other information

* Tag review: https://github.com/w3ctag/design-reviews/issues/825
* WebKit standards position: https://github.com/WebKit/standards-positions/issues/148

Allows transitions of discrete properties to be started on properties explicitly listed in the transition-property list. These transitions run using the same logic as an animation on those properties performing a flip at 50% by default but can be customized through the use of the transitionstart event and web-animations-1 APIs for modifying transition animations.

**Comment by zcorpan** [comment]
@dholbert @emilio thoughts?

**Comment by dholbert** [comment]
Yeah, this is just a spec-change, already discussed & resolved-on in the CSSWG, no objections from us.  We have https://bugzilla.mozilla.org/show_bug.cgi?id=1805727

I don't think it needs a standards-position issue.  If we run into concerns when implementing this or thinking about it, we'll bring them up as csswg issues.
