### ISSUE TITLE
Scripting media feature

### ISSUE THREAD

**Issue by CanadaHonk** [mozilla/standards-positions#765]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Media Queries Level 5
* Specification or proposal URL: https://www.w3.org/TR/mediaqueries-5/#scripting
* Caniuse.com URL: https://caniuse.com/mdn-css_at-rules_media_scripting
* Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1166581
* Mozillians who can provide input: @emilio @zcorpan (sorry if wrong!)

### Other information
Mostly done and accepted patch: https://phabricator.services.mozilla.com/D172995
More as a formality for intents :)

**Comment by zcorpan** [comment]
I had the same reaction as @emilio in https://github.com/w3c/csswg-drafts/issues/8621 about `initial-only` thinking it shouldn't apply for "printed pages" (in a browser); the `print` media exists already.

Developers work around the lack of this by running a script that adds a class name to the root element. A media feature seems nicer.

About`initial-only`... In principle the page can find out if script only works during page load by setting an interval that calls home, and if it stops then the page can assume that scripting no longer works (but the page can't adapt anymore). So `initial-only` allows pages to adapt.

I think this seems useful and doesn't expose introduce new information from a privacy perspective. I suggest `positive`.
