### ISSUE TITLE
overflow:overlay aliases overflow:auto

### ISSUE THREAD

**Issue by chrishtr** [mozilla/standards-positions#768]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: [css-overflow-3] Make `overflow: overlay` a legacy alias of `auto`
* Specification or proposal URL (if available): https://drafts.csswg.org/css-overflow-3/#valdef-overflow-auto
* Explainer URL (if available): N/A
* Caniuse.com URL (optional):  N/A
* Bugzilla URL (optional): N/A
* Mozillians who can provide input (optional): 

CSSWG resolution here: https://github.com/w3c/csswg-drafts/issues/8063#issuecomment-1431620007

The needed work in Gecko is to support `overlay` as a legacy alias of `auto`.

**Comment by emilio** [comment]
Yeah, agreed. In fact we already do this (https://bugzilla.mozilla.org/show_bug.cgi?id=1817189)
