### ISSUE TITLE
Unsanitized HTML read/write in Async Clipboard API

### ISSUE THREAD

**Issue by anaskim** [mozilla/standards-positions#769]
## Request for Mozilla Position on Unsanitized HTML read/write in Async Clipboard API

* Specification Title: Unsanitized HTML read/write in Async Clipboard API
* Specification or proposal URL (if available): https://github.com/w3c/clipboard-apis/issues/150 
* Explainer URL (if available): https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-unsanitized/explainer.md
* Mozillians who can provide input (optional): @smaug---- @EdgarChen

### Other information
There was some discussion around the topic in the issue linked above, but we would like to formally request Mozilla's position on reading and writing unsanitized HTML to and from the clipboard.

**Comment by snianu** [comment]
Note that FF was supportive of aligning the sanitization requirement of HTML format of Async API with DataTransfer API: https://github.com/w3c/clipboard-apis/issues/150#issuecomment-1031684598
Since Chromium has already shipped async api with sanitization behavior, we're making this change to interop with the legacy DataTransfer API. You can read about it in the linked Github issue.

**Comment by snianu** [comment]
@EdgarChen Just checking if you got a chance to review this proposal?

**Comment by EdgarChen** [comment]
> Note that FF was supportive of aligning the sanitization requirement of HTML format of Async API with DataTransfer API:[ w3c/clipboard-apis#150 (comment)](https://github.com/w3c/clipboard-apis/issues/150#issuecomment-1031684598)

For built-in types, I think the proposal is to have consistent behavior between the legacy and the async API by default: Either sanitize consistently in all APIs without a way to disable it (agent might do differently based on origin), or do not sanitize. Adding an 'unsanitized' option to force the return of unsanitized data doesn't seem to make sense to me.

**Comment by snianu** [comment]
@EdgarChen In Firefox, DataTransfer APIs provide access to unsanitized HTML content by-default (just like Chromium) regardless of the origin of the site. Is your position that async clipboard API should provide access to unsanitized HTML by-default as well?

Chromium has shipped async clipboard API with a strictly sanitized version, so we want to give web authors option to choose what type of content they would like to process -- a sanitized fragment (where `<head>`, `<style>` etc is stripped out), or unprocessed HTML content (that helps with round-tripping of HTML content from native apps to web apps and vice versa).
Adobe, Office products, Google Sheets etc are interested in this API, so it would be great if Firefox can provide support for the `unsanitized` option.

**Comment by EdgarChen** [comment]
Gecko maintains consistent behavior between the legacy and async APIs on `read()` for built-in types by default (returning unsanitized data for built-in types), so we don’t need to implement the `unsanitized` options to make the built-in types interoperable. I propose a `neutral` position.
