### ISSUE TITLE
Protected Audience API

### ISSUE THREAD

**Issue by JensenPaul** [mozilla/standards-positions#770]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: FLEDGE API
* Specification or proposal URL (if available): Partial spec is [here](https://wicg.github.io/turtledove/), but recommend deferring to the explainer.
* Explainer URL (if available): https://github.com/WICG/turtledove/blob/main/FLEDGE.md
* Mozillians who can provide input (optional): @martinthomson 

### Other information

Chrome status page: https://chromestatus.com/features/5733583115255808
We’ve been working on FLEDGE, a privacy advancing API to facilitate advertising based on showing an ad to a potentially-interested person who has previously interacted with the advertiser or ad network.  Historically this has worked by the advertiser recognizing a specific person as they browse across web sites, a core privacy concern with today's web.  Our effort is about offering a new API to address this advertising use case while offering some key privacy advances:
 * The user’s browser, not the advertiser, holds the information about what the advertiser thinks a person is interested in.
 * Advertisers can serve ads based on an interest, but cannot combine that interest with other information about the person — in particular, with who they are or what page they are visiting.
 * Web sites the person visits, and the ad networks those sites use, cannot learn about their visitors' ad interests.

FLEDGE is Chrome's first experiment in this direction.  We are currently conducting an Origin Trial with FLEDGE but are open to evolving the API over time and are appreciative of your feedback.

The FLEDGE explainer calls out certain behaviors as temporary. These are design trade-offs that we have chosen in the interest of having an API available in Chrome and adopted by ad techs as soon as possible, since the API is a key piece of our effort to remove third-party cookies. The most useful feedback and position would probably be focused on the long-term goal, rather than the interim compromises that we've made. We remain happy to hear your thoughts about any part of the design, though.

**Comment by JensenPaul** [comment]
We wanted to bring to your attention that we’re proposing shipping a change to Protected Audience (formerly known as FLEDGE) that gives API callers the option of moving execution of much of the Protected Audience auction logic off the user’s device and onto servers: [Bidding and Auction Services](https://groups.google.com/a/chromium.org/g/blink-dev/c/CyXJz3xOEcc/m/1snkv2KhAwAJ)

**Comment by martinthomson** [comment]
Thanks for the update.  I am reminded that we should have posted a "negative" position on this, consistent with [our blog posting](https://blog.mozilla.org/en/privacy-security/googles-protected-audience-protects-advertisers/).  Correcting that oversight.
