### ISSUE TITLE
Request for Mozilla Position: Zstandard compression format for Content-Encoding

### ISSUE THREAD

**Issue by nidhijaju** [mozilla/standards-positions#775]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Zstd Content-Encoding
* Specification or proposal URL (if available): https://datatracker.ietf.org/doc/html/rfc8878
* Explainer URL (if available): https://docs.google.com/document/d/1aDyUw4mAzRdLyZyXpVgWvO-eLpc4ERz7I_7VDIPo9Hc/edit?usp=sharing
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=zstd
* Mozillians who can provide input (optional): @martinthomson 

### Other information
[Zstandard](https://facebook.github.io/zstd/), or "zstd", is a data compression mechanism, described in [RFC8878](https://datatracker.ietf.org/doc/html/rfc8878), providing high compression ratios. The proposal is to add "zstd" to the tokens in the `Accept-Encoding` header, and decompress with Zstandard when the token is seen in the `Content-Encoding` header. It is anticipated to make pages load faster and reduce serving costs, by reducing CPU and/or bandwidth consumption, especially for dynamic content. 

Chrome is currently evaluating implementing this, and is interested in other browsers' position on the specification.

**Comment by ricea** [comment]
I just found out that this was previously closed as `defer`: https://github.com/mozilla/standards-positions/issues/105

I do not have a lot of new information to contribute, except that zstd adoption has continued to grow.

**Comment by rektide** [comment]
I noticed a couple items down is #160, which is for adding Compression Dictionary support to websites. This is WIP, but it seemingly could/would overcome a primary cause for the `defer` in #105 / here.

I'll comment in #105 as well.

**Comment by martinthomson** [comment]
We can skip the dashboard for this one.

**Comment by jesup** [comment]
FYI, we just landed zstd support in Nightly

**Comment by martinthomson** [comment]
A timely reminder that we probably want to update the dashboard.  Note that this and that are subtly different things, so we might need to tweak a few things.
