### ISSUE TITLE
WhatWG owning type streams 

### ISSUE THREAD

**Issue by youennf** [mozilla/standards-positions#778]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WhatWG owning type streams 
* Specification or proposal URL (if available): https://github.com/whatwg/streams/pull/1271
* Explainer URL (if available): https://github.com/whatwg/streams/blob/main/streams-for-raw-video-explainer.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jan-ivar

**Comment by jan-ivar** [comment]
This seems like the right solution to the tricky problem of streaming chunks backed by [system resources](https://w3c.github.io/webcodecs/#system-resources). Hopefully this pattern can be expanded on to work with transferable streams as well.

**Comment by martinthomson** [comment]
Inferring from this a positive view (and from other internal discussion of similar disposition), I'm marking this positively.
