### ISSUE TITLE
Submitting element directionality via the dirname attribute

### ISSUE THREAD

**Issue by vinhill** [mozilla/standards-positions#782]
## Request for Mozilla Position on a Web Specification

* Specification Title: Submitting element directionality: the dirname attribute
* Specification or proposal URL: [Submitting element directionality: the dirname attribute](https://html.spec.whatwg.org/#submitting-element-directionality:-the-dirname-attribute)
* Explainer URL: [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#dirname)
* Bugzilla URL: [Bug 675943](https://bugzilla.mozilla.org/show_bug.cgi?id=675943)
* Mozillians who can provide input: @zcorpan

### Other information
We intend to prototype and ship this feature soon.

**Comment by zcorpan** [comment]
Suggested position: positive

This is implemented in WebKit and Chromium and is part of interop 2023.
