### ISSUE TITLE
Request for position: customElements.getName 

### ISSUE THREAD

**Issue by keithamus** [mozilla/standards-positions#785]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: customElements.getName
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9195#discussion_r1174422812
* Explainer URL (if available): https://github.com/WICG/webcomponents/issues/566
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1829335
* Mozillians who can provide input (optional): @smaug----, @zcorpan 

### Other information

This was a proposed addition to the customElements spec by the WCCG, during their spring F2F, @smaug---- & @zcorpan were in attendance. See https://github.com/WICG/webcomponents/issues/566 for more on the problem/solution. 

WebKit has landed a patch for this: https://github.com/WebKit/WebKit/pull/13053
Chrome has landed a patch for this: https://chromium-review.googlesource.com/c/chromium/src/+/4466232
I've written a patch for Gecko: https://phabricator.services.mozilla.com/D181646

**Comment by zcorpan** [comment]
I think this is reasonable, suggest positive. @smaug---- WDYT?

**Comment by smaug----** [comment]
Oh sorry, I thought I had responded here already. Yes, looks reasonable minor addition.
