### ISSUE TITLE
WebRTC Codec selection API

### ISSUE THREAD

**Issue by Orphis** [mozilla/standards-positions#789]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: WebRTC Codec selection API
* Specification or proposal URL (if available): https://w3c.github.io/webrtc-extensions/#dom-rtcrtpencodingparameters-codec
* Explainer URL (if available): Slides for the WG interim at https://docs.google.com/presentation/d/1OfAN3sfVXhvOBCqgLMegrNcHz7-V4qTnuHjBP3gLdgg/edit#slide=id.g216ea3acd8c_1_3
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jan-ivar 

### Other information

The `RTCRtpEncodingParameters.codec` field is a new API allowing the developers to change the current codec used to encode a layer without having to do a renegotiation with a different codec order. Currently, the codec used by a sender is the first one negotiated, which is not convenient for developers as they can't update all the encoding parameters (especially in simulcast use case) at the same time as they change codec.

**Comment by jan-ivar** [comment]
API is something like:
```js
    const {codecs} = RTCRtpSender.getCapabilities("video"); 
    const vp8 = codecs.find(({mimeType}) => mimeType == "video/VP8");
    const h264 = codecs.find(({mimeType}) => mimeType == "video/H264");

    const pc = new RTCPeerConnection();
    // before negotiation
    const {sender} = pc.addTransceiver("video", {sendEncodings: [{codec: h264}]});
    
    // after negotiation
    const params = sender.getParameters();
    params.encodings[0].codec = vp8;
    await sender.setParameters(params);
```

**Comment by jesup** [comment]
LGTM.  From an rtp/sdp spec perspective the sender is allowed to switch codecs among the agreed on list at any time.  Currently there's no way to actually do so in WebRTC, however, and it's useful to switch at times.  +1

**Comment by martinthomson** [comment]
This seems small enough that a dashboard entry isn't needed.
