### ISSUE TITLE
CSS Anchor Positioning

### ISSUE THREAD

**Issue by lukewarlow** [mozilla/standards-positions#794]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Anchor Positioning
* Specification or proposal URL (if available): https://drafts.csswg.org/css-anchor-position-1/
* Explainer URL (if available): ~~https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md (probably slightly outdated but should give a general overview)~~

https://xiaochengh.github.io/Explainers/css-anchor-position/explainer.html

* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

## Other Information

This new CSS functionality will allow web developers to position elements anchored to another element with built in fallback positioning. This will go hand in hand with the Popover API [which Mozilla is positive on](https://github.com/mozilla/standards-positions/issues/698)

**Comment by xiaochengh** [comment]
The original Microsoft explainer is very old and has a lot of out-of-date details.

Here's a new explainer: https://xiaochengh.github.io/Explainers/css-anchor-position/explainer.html

**Comment by zcorpan** [comment]
@emilio @dholbert

**Comment by dholbert** [comment]
We're `positive` on anchor positioning; it seems to be an elegant evolution of absolute positioning, with an assortment of nice use-cases.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1838746 as a placeholder metabug to track implementation.

**Comment by jwatt** [comment]
Intent to Prototype e-mail:
https://groups.google.com/a/mozilla.org/g/dev-platform/c/4cbytMKbHtg

**Comment by steffchep** [comment]
What's the ETA on this feature? Asking for a friend.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1838746 is the right place to track implementation status.
