### ISSUE TITLE
Request for position: Intervention Reporting (Reporting API)

### ISSUE THREAD

**Issue by sefeng211** [mozilla/standards-positions#797]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Intervention Reporting
* Specification or proposal URL (if available):  https://wicg.github.io/intervention-reporting/#intervention-report
* Mozillians who can provide input (optional): @zcorpan

**Comment by dveditz** [comment]
@sefeng211: is this position request obsolete? The intervention report spec looks pretty unbaked and placeholdery, and references the [Interventions](https://github.com/WICG/interventions) proposal which has been archived.

**Comment by zcorpan** [comment]
I think the idea was to have position requests for all reporting types. https://developer.chrome.com/articles/reporting-api/

Although the "interventions" terminology is no longer used for new spec changes (see https://twitter.com/zcorpan/status/1542857293527662592), the interventions are still supported (including Gecko for some) and I assume are still reported in Chromium.

**Comment by sefeng211** [comment]
Yeah right, exactly as to what Simon mentioned. 

Shall we resolve this as Neutral given its not harmful the web and we have no intention in implementing it?

**Comment by zcorpan** [comment]
SGTM
