### ISSUE TITLE
Add value argument to URLSearchParams's has() and delete()

### ISSUE THREAD

**Issue by debadree25** [mozilla/standards-positions#801]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Add value argument to URLSearchParams's has() and delete()
* Specification or proposal URL (if available): https://github.com/whatwg/url/pull/735
* Explainer URL (if available): 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1831587
* Mozillians who can provide input (optional):

**Comment by valenting** [comment]
I think we're positive on this change, and we can close it without a dashboard entry.
