### ISSUE TITLE
Ignore target names which contain both `\n` and `<` characters

### ISSUE THREAD

**Issue by shhnjk** [mozilla/standards-positions#804]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Ignore target names which contain both `\n` and `<` characters
* Specification or proposal URL: https://github.com/whatwg/html/pull/9309
* Mozillians who can provide input: @mozfreddyb

**Comment by mozfreddyb** [comment]
I would think we are generally in favor of this change. The [impact seems low](https://chromestatus.com/metrics/feature/timeline/popularity/4493), which is good.

All in all, it seems a bit early to say more, given that this is still under review in WHATWG. Either way, I think we can close this as "positive" without making an explicit entry in our dashboard.

**Comment by valenting** [comment]
Gecko is tracking this in [Bug 1369029 - Consider blocking requests to HTTP(S) URLs that contain both `\n` and `<` characters.](https://bugzilla.mozilla.org/show_bug.cgi?id=1369029)

**Comment by shhnjk** [comment]
Sounds great! Thank you!

**Comment by mozfreddyb** [comment]
@valenting This is about `target` attributes (e.g., target names) and https://github.com/whatwg/html/pull/9309.
The URL parsing bit you were looking at is likely https://github.com/whatwg/fetch/issues/546.

**Comment by valenting** [comment]
Ah, that's right. Sorry for the noise.
