### ISSUE TITLE
CSS Values 5: random()

### ISSUE THREAD

**Issue by CanadaHonk** [mozilla/standards-positions#809]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Values and Units Module Level 5
* Specification or proposal URL (if available): https://drafts.csswg.org/css-values-5/#random
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1836588
* Mozillians who can provide input (optional): @emilio

### Other information
No engines implement or ship this yet.

**Comment by CanadaHonk** [comment]
CC also @dholbert

**Comment by Mardeg** [comment]
There still remain environments where webpages are restricted from running any javascript while still allowing CSS, like embedded .html documents in Sharepoint internally at many workplaces, or code within Wikimedia hosted .svg files, eg. https://commons.wikimedia.org/wiki/Category:Interactive_SVG_games

The latter would definitely benefit from CSS random()

**Comment by zcorpan** [comment]
There were several comments after https://github.com/w3c/csswg-drafts/issues/2826#issuecomment-1587795893 showing use cases, and per https://github.com/w3c/csswg-drafts/issues/2826#issuecomment-2350544265 it's now in the spec following a WG resolution. @emilio WDYT?

**Comment by emilio** [comment]
Yeah the thing the WG settled on was a lot saner than the initial proposal :)
