### ISSUE TITLE
Tabbed web apps

### ISSUE THREAD

**Issue by loubrett** [mozilla/standards-positions#811]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Tabbed web apps
* Specification or proposal URL (if available): 
* Explainer URL (if available): https://github.com/WICG/manifest-incubations/blob/gh-pages/tabbed-mode-explainer.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by martinthomson** [comment]
Hi @loubrett, Thanks for asking, but Mozilla isn't currently looking at these sorts of features, so we're not really able to take a position.
