### ISSUE TITLE
Broken image for asset/Other.svg (JPEG-XL spec)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/standards-positions#825]
https://mozilla.github.io/standards-positions/#jpegxl

```html
<img src="asset/Other.svg" height="18px" alt="Other">
```

I don't see an asset/Other.svg in https://github.com/mozilla/standards-positions/tree/main/asset

Looks like the only broken image and didn't see any other mentions of `"Other"` in https://github.com/mozilla/standards-positions/blob/main/activities.json

**Comment by zcorpan** [comment]
Fixed by https://github.com/mozilla/standards-positions/pull/1063.
