### ISSUE TITLE
contain-intrinsic-size: auto none syntax support

### ISSUE THREAD

**Issue by vmpstr** [mozilla/standards-positions#827]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: [css-sizing-4](https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-size)
* Specification or proposal URL (if available):
     Resolution to add this syntax is part of the following resolution:
     https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1440466558
* Mozillians who can provide input (optional): @emilio

**Comment by emilio** [comment]
I think we're positive on the idea of having `auto none`, but the feature needs a proper spec.

**Comment by vmpstr** [comment]
> I think we're positive on the idea of having `auto none`, but the feature needs a proper spec.

I've put together a PR for the spec edits, I appreciate if you could take a look:
https://github.com/w3c/csswg-drafts/pull/8989
