### ISSUE TITLE
ServiceWorker static routing API

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [mozilla/standards-positions#828]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: ServiceWorker static routing API
* Specification or proposal URL (if available): 
* Explainer URL (if available): https://github.com/yoshisatoyanagisawa/service-worker-static-routing-api

* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

This API allows developers to configure the routing, and allows them to offload simple things ServiceWorkers do. If the condition matches, the navigation happens without starting ServiceWorkers or executing JavaScript, which allows web pages to avoid performance penalties due to ServiceWorker interceptions.

Starting ServiceWorkers is known to be a slow process, and web users need to wait for its startup if the ServiceWorker intercepts loading the page resources. At the same time, the ServiceWorker brings flexibility to the transport layer, and it behaves as a client-side proxy. Developers can implement offline support or provide client-side content modification with it. Currently, ServiceWorkers intercept all requests for pages within their scope, which brings a performance penalty within the scope.

**Comment by mkruisselbrink** [comment]
FYI, I just [merged the spec PR for this](https://github.com/w3c/ServiceWorker/pull/1701). Happy to take any additional feedback you might have into account though.

**Comment by sefeng211** [comment]
(Implementation bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1855580)
