### ISSUE TITLE
Web Charts

### ISSUE THREAD

**Issue by AdamSobieski** [mozilla/standards-positions#829]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Web Charts
* Specification or proposal URL (if available): https://github.com/WICG/proposals/issues/97
* Explainer URL (if available): 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information

The _**Web Charts**_ proposal intends to add a new HTML [media element](https://html.spec.whatwg.org/multipage/media.html#media-element), `<chart>`, alongside the `<audio>` and `<video>` elements.

Charts can provide interactive visualizations for static data as well as for time-based, dynamic, streaming data. Scenarios for this latter case, consuming "data video", include displaying streaming data from: sensors, business intelligence and analytics, and stock markets.

Accordingly, the proposed `<chart>` element would be conceptually derived from the `<video>` element, utilizing most or all of its attributes, and extending its content model. In this approach, any eventual `HTMLChartElement` interface would extend `HTMLMediaElement`.

For scenarios involving the visualization of static data, here are some markup examples:

```xml
<chart src="data.csv" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
</chart>
```

```xml
<chart width="600" height="400">
  <source type="text/csv" src="data.csv" />
  <source type="text/tsv" src="data.tsv" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
</chart>
```

In these above examples, the provided scripting logic processes the selected input data into interactive content, e.g., HTML, SVG, Canvas, WebGL, or WebGPU content, in the shadow DOM.

Next, we can add configuration settings for the provided scripting logic to consume utilizing the [data block](https://html.spec.whatwg.org/multipage/scripting.html#data-block) capabilities of `<script>` elements when they are provided content of a type other than `text/javascript`.

```xml
<chart src="data.csv" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

```xml
<chart width="600" height="400">
  <source type="text/csv" src="data.csv" />
  <source type="text/tsv" src="data.tsv" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

Next, for time-based, dynamic, streaming data scenarios, here are some markup examples. In the following examples, the MIME types of `video/mp4` and `video/webm` are utilized as placeholders.

```xml
<chart src="data-video.m3u8" poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

```xml
<chart poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <source type="video/mp4" src="data-video.mp4" />
  <source type="video/webm" src="data-video.webm" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

Finally, we can add a `<style>` element so that charts could provide custom styling instead of only being able to utilize the style of their containing documents.

```xml
<chart src="data-video.m3u8" poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
  <style  src="custom.css" />
</chart>
```

```xml
<chart poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <source type="video/mp4" src="data-video.mp4" />
  <source type="video/webm" src="data-video.webm" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
  <style  src="custom.css" />
</chart>
```

**Comment by martinthomson** [comment]
Also [WebKit oppose](https://github.com/WebKit/standards-positions/issues/207) this.  I agree that this would need to be substantially different to reach any other conclusion.
