### ISSUE TITLE
Request for Mozilla Position: exclusive accordions with <details name="">

### ISSUE THREAD

**Issue by dbaron** [mozilla/standards-positions#831]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Exclusive accordion (the `name` attribute on the HTML `details` element)
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9400
* Explainer URL (if available): https://open-ui.org/components/accordion.explainer
* Caniuse.com URL (optional):
* Bugzilla URL (optional):
* Mozillians who can provide input (optional): @emilio

**Comment by zcorpan** [comment]
I like the direction here and it aligns with our vision for the web with [more declarative solutions](https://www.mozilla.org/en-US/about/webvision/full/#thedeclarativeweb) that are accessible by default (as opposed to implementing a widget like this with JS + ARIA).

Suggest `positive`.

**Comment by smaug----** [comment]
But the current setup requires JS. Before implementing this having reasonable behavior during page load is rather important.
In other words, I'm not sold on the proposed solution here https://open-ui.org/components/accordion.explainer/#interaction-with-open-attribute

**Comment by dbaron** [comment]
What is it that requires JS?

Would it help to clarify things if we made it an explicit document conformance requirement not to have more than one `<details>` element in a single `name`-group that has an `open` attribute?

**Comment by smaug----** [comment]
The proposed solution explicitly talks about setAttribute or open attributes, in addition to user interaction.
So to set initial state, one needs to use JS.

**Comment by dbaron** [comment]
Setting initial state does not require JS.  It can be done by using an 'open' attribute in the markup.  I would describe is as an authoring error to use an `open` attribute in the markup on more than one element in a group.

**Comment by MBeggiato** [comment]
Is there any progress on this issue? Firefox is the last browser to not support the `name `attribute.

**Comment by zcorpan** [comment]
This is not the right place to follow implementation progress in Gecko. https://bugzilla.mozilla.org/show_bug.cgi?id=1856460 is.
