### ISSUE TITLE
@starting-style CSS Rule

### ISSUE THREAD

**Issue by lilles** [mozilla/standards-positions#833]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Transitions Level 2
* Specification or proposal URL (if available):  https://drafts.csswg.org/css-transitions-2/#defining-before-change-style-the-starting-style-rule
* Explainer URL (if available): https://github.com/chrishtr/rendering/blob/master/entry-exit-animations.md

### Other information

TAG review: https://github.com/w3ctag/design-reviews/issues/829

The explainer is outdated since it uses the :initial pseudo class that was later made into an `@initial` rule, and later renamed `@starting-style` by the CSSWG.

**Comment by dholbert** [comment]
We can record a position of `positive` here; I've been following the CSSWG discussions around this feature, and it seems to me like it fixes a real problem in an intuitive & straightforward way.

**Comment by zcorpan** [comment]
No dashboard entry since it's an addition to CSS Transitions.

**Comment by yairEO** [comment]
Is there a link I can follow in order to follow *Mozilla*'s progress on the `@starting-style` rule's support?

**Comment by dholbert** [comment]
@BorisChiou is working on it in https://bugzilla.mozilla.org/show_bug.cgi?id=1834876
