### ISSUE TITLE
`dialogmodaltarget` attribute

### ISSUE THREAD

**Issue by keithamus** [mozilla/standards-positions#834]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: `dialogmodaltarget` attribute
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9456
* Explainer URL (if available): https://github.com/whatwg/html/pull/9456
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1840602
* Mozillians who can provide input (optional): @smaug---- @zcorpan 

### Other information

This spec adds a `dialogmodaltarget` attribute to button elements. Similar to `popovertarget`, `dialogmodaltarget` takes an IDREF and calls `showModal()` or `close()` on the idref element, when the button is clicked. It also specifies the reflected `dialogModalTargetElement` attribute (which allows for cross-root assignment).

**Comment by smaug----** [comment]
Commented in https://github.com/whatwg/html/pull/9456#issuecomment-1611165349

**Comment by smaug----** [comment]
As explained in the spec issue, we think some more generic approach would be better for this use case.
