### ISSUE TITLE
Bounce Tracking Mitigations

### ISSUE THREAD

**Issue by wanderview** [mozilla/standards-positions#835]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Bounce Tracking Mitigations
* Specification or proposal URL (if available): https://privacycg.github.io/nav-tracking-mitigations/#bounce-tracking-mitigations (Note, the doc has descriptions of other nav tracking topics, but the spec is just one section in the doc.)
* Explainer URL (if available): https://github.com/privacycg/nav-tracking-mitigations/blob/main/bounce-tracking-explainer.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): We've had previous discussions with Ben VanderSloot and Paul Zühlcke in the privacycg.

### Other information

Note, we have not been able to write web-platform tests because the algorithm runs deletion on a long running timer.  WPT does [not have support for moving the clock forward yet](https://github.com/web-platform-tests/wpt/issues/17489).

Also note, we have tried to align our proposal along the lines of what Firefox has shipped in the past, although we ended up with some differences.  In particular, our triggering condition is based on "stateful bounce" instead of "all sites with storage".  There are benefits to the Firefox behavior, but our experiments showed it hitting some sites we could not explain and wanted to be cautious.  I hope to expand our triggering condition in the future.

**Comment by zcorpan** [comment]
cc @bvandersloot-mozilla @Trikolon

**Comment by bvandersloot-mozilla** [comment]
Sorry for the long delay here- we are generally positive on this work. This is mechanically similar to a Firefox product features we already have, but expands it beyond a list and into heuristics that don't risk existing authentication workflows. Clearing site data is a risk and makes website state unreliable for some actors, however the privacy gains this enables to mitigate tracking techniques not affected by third party cookie deprecation are worth pushing on. Potential harm is minimized with the balance struck away from false positives by the heuristic.

RE WPT: I think we may be able to test a lot of it if we add new web-driver functions to trigger some of the algorithms that typically occur on a timer.
