### ISSUE TITLE
UserActivation API

### ISSUE THREAD

**Issue by zcorpan** [mozilla/standards-positions#838]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: The `UserActivation` interface
* Specification or proposal URL (if available): https://html.spec.whatwg.org/multipage/interaction.html#the-useractivation-interface
* Explainer URL (if available): https://github.com/dtapuska/useractivation
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1791079
* Mozillians who can provide input (optional): @smaug---- @EdgarChen 

### Other information

- MDN: https://developer.mozilla.org/en-US/docs/Web/API/UserActivation
- Spec issue: https://github.com/whatwg/html/issues/4008

**Comment by smaug----** [comment]
I think the API is quite reasonable, and we implement at least most of it internally already. It just isn't exposed to the web.
