### ISSUE TITLE
contenteditable="plaintext-only"

### ISSUE THREAD

**Issue by zcorpan** [mozilla/standards-positions#839]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: `contenteditable="plaintext-only"`
* Specification or proposal URL (if available): https://html.spec.whatwg.org/multipage/interaction.html#editing-2 , https://w3c.github.io/editing/docs/execCommand/
* Explainer URL (if available): 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1291467
* Mozillians who can provide input (optional): @masayuki-nakano 

### Other information
- MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
- Spec issues: https://github.com/whatwg/html/issues/7864 , https://github.com/w3c/editing/issues/162

**Comment by zcorpan** [comment]
This is needed for web compat. It's basically a subset of `contenteditable="true"` since some formatting commands are disabled. A declarative way to turn off formatting but still have editing seems reasonable.

There are known interop issues with `contenteditable` in general. Adding `plaintext-only` in Gecko improves interop.

Suggested position: positive

**Comment by masayuki-nakano** [comment]
+1 for solving web-compat issues, but standardizing the behavior (at least roughly for the important editing commands) first.

**Comment by zcorpan** [comment]
No dashboard entry as this is an extension of `contenteditable` (which also has no dashboard entry).
