### ISSUE TITLE
Lazy loading for iframes

### ISSUE THREAD

**Issue by zcorpan** [mozilla/standards-positions#840]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Lazy loading for iframes
* Specification or proposal URL (if available): https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-loading
* Explainer URL (if available): https://github.com/scott-little/lazyload
* Caniuse.com URL (optional): https://caniuse.com/loading-lazy-attr (images and iframes)
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1622090
* Mozillians who can provide input (optional): @hiikezoe @emilio

### Other information

Also see https://github.com/mozilla/standards-positions/issues/151

**Comment by zcorpan** [comment]
We support lazy-loaded images, and the feature makes sense for `iframe` for similar reasons. Initial page load is faster and more lightweight if out-of-view iframes are lazy-loaded. It's possible for sites to implement lazy-loading with JS but a declarative solution is easier to use and allows browsers to control when to load things.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1622090#c10 for an example of real-world impact.

Suggested position: positive.

**Comment by emilio** [comment]
I agree fwiw.

**Comment by martinthomson** [comment]
@zcorpan did you intend to add this to the dashboard?
