### ISSUE TITLE
CSS Color 5: Relative Color Syntax

### ISSUE THREAD

**Issue by svgeesus** [mozilla/standards-positions#841]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Color Module Level 5, section 4. Relative Color Syntax 
* Specification or proposal URL (if available): https://drafts.csswg.org/css-color-5/#relative-colors
* Explainer URL (if available): [RCS Explainer](https://github.com/w3c/csswg-drafts/blob/main/css-color-5/RCS-Explainer.md)
* Caniuse.com URL (optional): https://caniuse.com/css-relative-colors
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1701488
* Mozillians who can provide input (optional): @emilio 

### Other information

- Shipped in Safari 16.4.
- Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1447327&q=relative%20color&can=2
- WPT tests (2076 subtests) (most passed by Safari): https://wpt.fyi/results/css/css-color/parsing?label=master&label=experimental&aligned&q=relative
- CSSWG issue: Is relative color syntax ready to ship? https://github.com/w3c/csswg-drafts/issues/7978
- CSS WG issue: compat issues https://github.com/w3c/csswg-drafts/issues/8943

**Comment by svgeesus** [comment]
Oh, relative color syntax is also supported in Lightning CSS, a server-side preprocessor written in Rust:

https://lightningcss.dev/transpilation.html#relative-colors

**Comment by emilio** [comment]
I think we generally like the shape of RCS. cc @tlouw who has looked more into it.

I'd love more tests for the feature because just from a quick look a couple weeks ago Safari doesn't support `currentColor` in RCS, which seems like a big oversight and apparently nobody noticed?

I'd suggest a positive position, assuming the test-suite improves, and also assuming Tiaan agrees :)

**Comment by svgeesus** [comment]
Yeah looking at [parsing/color-computed-relative-color.html](https://wpt.fyi/results/css/css-color/parsing/color-computed-relative-color.html?label=master&label=experimental&aligned&q=relative) there is no test for currentColor.

`currentColor` in RCS was discussed:

 - https://github.com/w3c/csswg-drafts/issues/6168
 - https://github.com/w3c/csswg-drafts/issues/9238

**Comment by tiaanl** [comment]
The spec as it is now looks good.  Only thing coming up for me during prototyping was the `currectcolor` issue, but that has been addressed now.

Implementation for this will start soonish.

**Comment by svgeesus** [comment]
@emilio could you review https://github.com/web-platform-tests/wpt/pull/41933 which adds some RCS `currentColor` tests?

**Comment by tiaanl** [comment]
Having `currentcolor` in `color-valid-relative-color.html` would also help to make it clear that parsing and serializing it as specified value is valid.

**Comment by svgeesus** [comment]
Good point, I will add it.

**Comment by svgeesus** [comment]
> Having `currentcolor` in `color-valid-relative-color.html` would also help to make it clear that parsing and serializing it as specified value is valid.

Added in https://github.com/web-platform-tests/wpt/pull/41933/commits/9a43e48b4a6cd8ecc28e0284aa8d963082c978ef

**Comment by svgeesus** [comment]
@tiaanl could you review https://github.com/web-platform-tests/wpt/pull/41933

**Comment by tiaanl** [comment]
@svgeesus Yup looks great. Thanks!

**Comment by svgeesus** [comment]
Okay well please say so as an approving review comment :)

**Comment by svgeesus** [comment]
@tiaanl thanks! @emilio when you get a chance?

**Comment by svgeesus** [comment]
Tests are all merged now, thanks to the reviewers.

Will this positive position be reflected on https://mozilla.github.io/standards-positions/ at some point?

**Comment by martinthomson** [comment]
Lots of noise here, I missed the two positive statements up-thread (and I suspect others did too).  I'll defer to them as to whether this appears on a dashboard.

@emilio, @tiaanl, if you think that this needs a dashboard entry, can I request that you create a pull request?
