### ISSUE TITLE
ManagedMediaSource API 

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/standards-positions#845]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: ManagedMediaSource API
* Specification or proposal URL (if available): https://github.com/w3c/media-source/issues/320
* Explainer URL (if available): As above
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jan-ivar, @padenot, Randall Jessup

### Other information
A “managed” MediaSource is one where more control over the MediaSource and its associated objects has been given over to the User Agent.

It's in WebKit and we'd love to hear Mozilla's position on it, and we would love any detailed feedback in the corresponding [issue](https://github.com/w3c/media-source/issues/320).

**Comment by padenot** [comment]
This is `positive`, for the reasons outlined in my post to the [main issues](https://github.com/w3c/media-source/issues/320#issuecomment-1632846690). There are, of course, still discussions to have (e.g. around privacy, naming, level of leeway left to the UA), but the majority of the concepts presented can be implemented in a way that they would bring clear improvements to the platform.

As an aside, for media related things that are not related to WebRTC, @alastor0325  and myself are good first point of contact (but it's eventually routed to us at some point anyway).
