### ISSUE TITLE
css-ui `field-sizing` property

### ISSUE THREAD

**Issue by tkent-google** [mozilla/standards-positions#849]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: css-ui `field-sizing` property
* Specification or proposal URL (if available): https://drafts.csswg.org/css-ui/#field-sizing
* Explainer URL (if available): N/A
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1832409
* Mozillians who can provide input (optional):

**Comment by zcorpan** [comment]
cc @emilio 

I think this is reasonable, suggest `positive`

**Comment by emilio** [comment]
I agree

**Comment by stefanjm** [comment]
This will be shipping soon on Chrome. Would love it for Firefox too.

**Comment by yisibl** [comment]
It's shipping in Chrome 123, and WebKit is in the [process of implementing](https://github.com/WebKit/WebKit/pull/24195) it.

**Comment by WyvernDryke** [comment]
CSS "field-sizing" does not function at all in Firefox. Is there an ETA for this feature to be introduced, please?

**Comment by jonathan-s** [comment]
@zcorpan As this was closed as completed I wonder what happened with this in the end.

**Comment by zcorpan** [comment]
This repo is about Mozilla's position on proposals, not about the implementations status in Firefox. Bugzilla is where the latter is tracked. For this feature it's https://bugzilla.mozilla.org/show_bug.cgi?id=1832409 (linked in OP).

**Comment by Jacksonmills** [comment]
any updates?

**Comment by DidierLoiseau** [comment]
@Jacksonmills, according to the linked bugzilla ticket, as well as the [field-sizing page on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/field-sizing#browser_compatibility), it should be enabled by default in release 152. It seems mdn/content#44325 with the release note update was just merged.

Based on the [Experimental web features of 151](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/151#experimental_web_features), this can also be enabled by setting `layout.css.field-sizing.enabled` to `true` in `about:config` – I confirm it works.
