### ISSUE TITLE
Opaque Response Blocking

### ISSUE THREAD

**Issue by hsinyi** [mozilla/standards-positions#860]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Opaque Response Blocking
* Specification or proposal URL (if available):  https://github.com/annevk/orb
* Explainer URL (if available): 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1532642
* Mozillians who can provide input (optional): @zcorpan @sefeng211 @farre 

### Other information
* There's a PR open which has the actual changes to the Fetch spec: https://github.com/whatwg/fetch/pull/1442
* ORB has been enabled on [Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1800658) and [early beta](https://bugzilla.mozilla.org/show_bug.cgi?id=1821682) on Firefox.
* Chrome's intent-to-ship for ORB [v0.1](https://groups.google.com/a/chromium.org/g/blink-dev/c/ScjhKz3Z6U4/m/5i_0V7ogAwAJ) and [v0.2](https://groups.google.com/a/chromium.org/g/blink-dev/c/RcuAzHEI2CU/m/E37KLjZjCwAJ) 
* Also see https://github.com/mozilla/standards-positions/issues/81#issuecomment-613937108

**Comment by sefeng211** [comment]
I think it is worth noting that we've found a few issues in the spec that may not be web-compatible, such as `Fetch API raising errors`. However, given we've implemented this and starting to roll this out, it should be an easy `positive` from us.

**Comment by martinthomson** [comment]
Agreed and marking this positive.  @sefeng211, let me know if you would prefer to put this on a dashboard (it doesn't seem big enough to warrant that).

**Comment by farre** [comment]
Since ORB to some extent (but not wholly) replaces CORB, and CORB is on the dashboard it might make sense to include ORB there as well. And even though ORB spec-wise is small it is fairly impactful.

@hsinyi, @sefeng211 do you agree?

**Comment by hsinyi** [comment]
Second @farre's points.

**Comment by farre** [comment]
Not sure if I managed to ask for dashboard before @martinthomson closed it, sorry for the ping :D

**Comment by martinthomson** [comment]
If one of you want to open a pull request to put the update in place, we can reopen this one to track that.  But we don't need an issue to make that change.
