### ISSUE TITLE
X25519Kyber768 key encapsulation for TLS

### ISSUE THREAD

**Issue by dadrian** [mozilla/standards-positions#874]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: X25519Kyber768 key encapsulation for TLS 
* Specification or proposal URL (if available): https://www.ietf.org/archive/id/draft-tls-westerbaan-xyber768d00-02.html
* Explainer URL (if available): https://blog.chromium.org/2023/08/protecting-chrome-traffic-with-hybrid.html
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): Dennis Jackson

### Other information

This is a draft post-quantum secure key encapsulation method for TLS. Standardization is via IETF, not W3C. I believe Firefox is already rolling this out.

**Comment by dennisjackson** [comment]
We're positive on this. The implementation work (by @xvzcf and @jschanck) in Firefox is wrapping up and we're looking to begin experiments soon.

I don't think this needs a dashboard entry.
