### ISSUE TITLE
HTML: Document Render-Blocking

### ISSUE THREAD

**Issue by khushalsagar** [mozilla/standards-positions#875]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: HTML
* Specification or proposal URL (if available): https://github.com/whatwg/html/issues/9332
* Explainer URL (if available): https://github.com/WICG/view-transitions/blob/main/document-render-blocking.md
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @emilio 

### Other information
This feature is required to support cross-document View Transitions reviewed at https://github.com/mozilla/standards-positions/issues/677.

**Comment by vmpstr** [comment]
Hi, please note that we're proposing the following solution: https://github.com/WICG/view-transitions/blob/main/document-render-blocking.md#blocking-element-id

This is in a spec PR here: https://github.com/whatwg/html/pull/9970

**Comment by zcorpan** [comment]
I think this is useful and necessary for cross-document View Transitions, as OP mentions. My main concern was about using the HTML parser end tag hook for arbitrary elements, but if https://github.com/whatwg/html/issues/9332#issuecomment-1857566537 is right then it shouldn't regress performance.

Suggest `positive`.

cc @hsivonen
