### ISSUE TITLE
Remove same-origin blanket enforcement from CSP Embedded Enforcement

### ISSUE THREAD

**Issue by shhnjk** [mozilla/standards-positions#878]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Remove same-origin blanket enforcement from CSP Embedded Enforcement
* Specification or proposal URL: https://github.com/w3c/webappsec-cspee/pull/28
* Mozillians who can provide input: @mozfreddyb

**Comment by mozfreddyb** [comment]
We don't support CSPEE and we don't plan to support it in the near future. That being said, I'm vaguely supportive of this amendment on CSPEE for those that implement it (cough cough, Chrome only) as it seems to plug an annoying leak. 🙂
