### ISSUE TITLE
Fetch Metadata Request Headers

### ISSUE THREAD

**Issue by annevk** [mozilla/standards-positions#88]
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1508292.

See https://github.com/whatwg/fetch/issues/700. Also mentioned in #80. Concerns mentioned in that issue:

> My concern with that header is that it makes referrer leaking worse, unless we restrict it to revealing one of same-origin, same-site, or cross-site.

Another concern is that it's yet another request header. It could perhaps be made opt-in, but that requires new infrastructure that hasn't materialized yet. As such I don't think this is something we can or want to do soon.

**Comment by jonathanKingston** [comment]
@annevk should this be renamed to sec-metadata?

**Comment by annevk** [comment]
Someone will have to decide whether the additional fingerprinting bits and increase in request headers is worth it.

I'm quite convinced some of this is very useful for sites to protect their resources though.

I wonder if we could perhaps not expose "destination" and expose the main relevant bit that has through mode instead: https://github.com/mikewest/sec-metadata/issues/16.

**Comment by annevk** [comment]
As an update, various security folks at Mozilla have discussed this more and Mozilla is positive on this, with the caveat that there's a couple outstanding issues still that need to be sorted.
