### ISSUE TITLE
CSS Values 5: attr() fallback

### ISSUE THREAD

**Issue by CanadaHonk** [mozilla/standards-positions#885]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: CSS Values 5
* Specification or proposal URL (if available): https://drafts.csswg.org/css-values-5/#attr-notation
* Caniuse.com URL (optional): No browser support as of filing
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1448248
* Mozillians who can provide input (optional): @emilio @zcorpan

### Other information
This will likely be shipped today in 119 if no one rejects here shortly (patch is accepted), more of a formality for intent to prototype + ship.

**Comment by bgrins** [comment]
Yeah, this seems like a good addition - I don't see any concerns with it
