### ISSUE TITLE
HTMLSelectElement `showPicker()`

### ISSUE THREAD

**Issue by lukewarlow** [mozilla/standards-positions#886]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: HTML 
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9754
* Explainer URL (if available): inline in https://github.com/whatwg/html/pull/9754
* Proposal author(s) (`@`-mention GitHub accounts): @lukewarlow
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1854112
* Mozillians who can provide input (optional): 

* Tag Design Review URL: https://github.com/w3ctag/design-reviews/issues/900

### Other information

The `showPicker()` method is a new addition to HTMLSelectElement which addresses a [common request from web developers](https://www.google.com/search?q=programmatically+open+select+site%3Astackoverflow.com): programmatically showing the option picker UI for a select element

**Comment by zcorpan** [comment]
cc @emilio @evilpie

This seems OK to me. Suggest `positive`.

**Comment by evilpie** [comment]
Agreed. It's a good idea and logically extension of the feature.

**Comment by zcorpan** [comment]
No dashboard entry since it's an incremental improvement for an existing feature.
