### ISSUE TITLE
Allow `<hr>` tags inside `<select>` tags

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#887]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Allow `<hr>` to be used inside `<select>` as a separator
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9124
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): @annevk
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1830909
* Mozillians who can provide input (optional): 

### Other information

This has been shipped in webkit and is going to ship soon in chrome.

**Comment by hsivonen** [comment]
Seems OK from the parser perspective.

**Comment by zcorpan** [comment]
The UI aspect is optional but I think also is OK. Suggest `positive`, no dashboard entry.
