### ISSUE TITLE
CaptureStartFocusBehavior enum value "focus-capturing-application"

### ISSUE THREAD

**Issue by beaufortfrancois** [mozilla/standards-positions#888]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: CaptureStartFocusBehavior enum value "focus-capturing-application"
* Specification or proposal URL (if available): https://www.w3.org/TR/screen-capture/#idl-def-CaptureStartFocusBehavior.focus-capturing-application
* Explainer URL (if available): https://github.com/WICG/conditional-focus/blob/main/README.md
* Proposal author(s) (`@`-mention GitHub accounts):  @eladalon1983 @beaufortfrancois
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jan-ivar 

### Other information

* Blink-dev Intent to ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/B2jT8PG8Lww

**Comment by jan-ivar** [comment]
I welcome this change.

**Comment by jan-ivar** [comment]
I've already found myself having to use the old value `"no-focus-change"` in place of this value in https://github.com/w3c/mediacapture-screen-share/issues/280#issuecomment-1718283047, because it threw in Chrome, so I welcome this change. Thanks!

**Comment by martinthomson** [comment]
Marking positive.  That said, I found the explanation of "focus-capturing-application" and "focus-captured-surface" confusing and in need of work.  Is the capturing application the browser in which the site that is calling the screen capture API lives, or the specific tab?  Or is this up to the implementation to decide?
