### ISSUE TITLE
Clear Site Data

### ISSUE THREAD

**Issue by bakulf** [mozilla/standards-positions#90]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Clear Site Data
* Specification or proposal URL: https://w3c.github.io/webappsec-clear-site-data/
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1268889

### Other information

This spec is about the introduction of a new http header: 'Clear-Site-Data' that allows the server to cleanup data for the current origin.  Possible values: cookies, cache, storage, ...

**Comment by bakulf** [comment]
This feature is currently in release. Should we close this issue? I guess so.

**Comment by marcoscaceres** [comment]
We probably want to take an actual position. @dbaron, could maybe draft one up?

**Comment by dbaron** [comment]
I assume the basic idea is that it's helpful for sites to be able to recover from mistakes in deployment of certain web technologies like Service Workers, and thus makes them more confident about deploying such technology.

Is it `worth prototyping` or `important`?  I'm inclined to use the former unless I hear an argument for the latter.

**Comment by bakulf** [comment]
I would say: worth prototyping

**Comment by dbaron** [comment]
Fixed by #116.
