### ISSUE TITLE
Fire toggle events using microtasks

### ISSUE THREAD

**Issue by josepharhar** [mozilla/standards-positions#901]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Fire toggle events using microtasks
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9775
* Explainer URL (if available): https://github.com/whatwg/html/issues/9046
* Proposal author(s) (`@`-mention GitHub accounts):
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @smaug---- 

### Other information

The toggle events for the popover attribute and the details element, as well as the close event for dialog elements, currently post a task to the DOM manipulation task source to fire these events asynchronously. This means that the event could fire before or after the next render, which could lead to flaky rendering for one frame. By using microtasks instead, the event will always fire before the next render. This was suggested in this HTML spec issue: https://github.com/whatwg/html/issues/9046

**Comment by smaug----** [comment]
I did comment already in the spec issue and this should be a good change https://github.com/whatwg/html/issues/9046#issuecomment-1724509340
