### ISSUE TITLE
Invokers (`invoketarget` & `invokeaction`)

### ISSUE THREAD

**Issue by keithamus** [mozilla/standards-positions#902]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Invokers
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9841
* Explainer URL (if available): https://open-ui.org/components/invokers.explainer/
* Proposal author(s) (`@`-mention GitHub accounts): @keithamus
* Caniuse.com URL (optional): N/A
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1856430
* Mozillians who can provide input (optional): @smaug----, @zcorpan, @emilio 

### Other information

This is a request for position just on the `invoketarget` and `invokeaction` parts of the Invokers explainer (excluding `interesttarget` and `interestaction`).

**Comment by keithamus** [comment]
I2P Chrome and is in Chrome Canary behind the Experimental Web Platform Features flag.

**Comment by smaug----** [comment]
I think we're positive on prototyping this. There might be still some things to sort out before the feature is ready
(see the feedback to the intent-to-prototype email, which is very similar to what was discussed at TPAC too), but overall this is looking reasonable approach.
And hopefully after this we could get rid of the weird popover specific attributes.

**Comment by lukewarlow** [comment]
Just as an fyi OpenUl have agreed (openui/open-ui#952 (comment)) to an initial scope for invokers of just popover and dialog actions, along with custom actions.

Hopefully this helps with some concerns regarding security of some of the additional proposed actions.

**Comment by tomayac** [comment]
@keithamus If `invokeaction`s that toggle state like `toggleMuted` would automatically sync with `aria-pressed`, this would allow to solve setting dynamic content with CSS, a concern that was uttered in 2) in https://github.com/WebKit/standards-positions/issues/264#issuecomment-2099956932.

Here's a [demo](https://selective-tricky-price.glitch.me/) in which I need JS to control the ARIA attribute.

**Comment by mfreed7** [comment]
Quick ping here, just to make sure Mozilla would still be supportive if the attribute names get renamed:

https://github.com/whatwg/html/issues/9625#issuecomment-2123566461
