### ISSUE TITLE
View Transitions: list of types

### ISSUE THREAD

**Issue by vmpstr** [mozilla/standards-positions#905]
* Specification title: View Transitions Module Level 2 (list of types)
* Specification or proposal URL (if available): 
  * https://drafts.csswg.org/css-view-transitions-2/#the-active-view-transition-pseudo
  * https://drafts.csswg.org/css-view-transitions-2/#additions-to-document-api
* Explainer URL (if available): https://github.com/vmpstr/web-proposals/blob/main/explainers/view-transition-types.md
* Proposal author(s) (`@`-mention GitHub accounts): @vmpstr @noamr
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @emilio 

### Other information
Note that View Transitions Module Level 2 has a number of new features being worked on in parallel. This particular issue is about the "list of types" component which allows developers to specify types when calling `startViewTransition`. The initial issue that spawned this spec change is https://github.com/w3c/csswg-drafts/issues/8960

**Comment by zcorpan** [comment]
Chromium Intent to Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/bq8u5SREiYE/m/BMOnhIzPBQAJ

**Comment by miketaylr** [comment]
FYI, it's proposed that we (Chromium) ship this in M121 (hitting Stable in early January), so if you have any feedback on the design now would be a good time to give it.

**Comment by emilio** [comment]
Yeah, no objections from my side. I'm still sad that we ended up with these mouthful of a name for pseudo classes rather than something more like ::part()/:state(), but that ship sailed and was discussed so... Positive?
