### ISSUE TITLE
`navigation.activation`

### ISSUE THREAD

**Issue by noamr** [mozilla/standards-positions#928]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Navigation Activation
* Specification or proposal URL (if available):  https://github.com/whatwg/html/pull/9856
* Proposal author(s) (`@`-mention GitHub accounts): @noamr
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1777171
* Mozillians who can provide input (optional): 

### Other information

Navigation Activation exposes information about the most recent cross-document navigation (aka "activation").
It exposes the old URL, new URL, and navigation type.
This is mainly useful for cross-document view transitions.

Navigation Activation is namespaced to the navigation API and uses the `NavigationHistoryEntry` interface, but other than that it's a somewhat self-contained.

**Comment by zcorpan** [comment]
@smaug---- @petervanderbeken

**Comment by smaug----** [comment]
I and @petervanderbeken went through the proposal again and think it is a reasonable addition to Navigation API.

**Comment by zcorpan** [comment]
No need for a dashboard entry IMO since https://mozilla.github.io/standards-positions/#navigation-api exists.
