### ISSUE TITLE
Long Animation Frame

### ISSUE THREAD

**Issue by noamr** [mozilla/standards-positions#929]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Long Animation Frames (LoAF)
* Specification or proposal URL (if available): https://github.com/w3c/longtasks/pull/122
* Explainer URL (if available): https://github.com/w3c/longtasks/blob/main/loaf-explainer.md
* Proposal author(s) (`@`-mention GitHub accounts): @noamr
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 
* TAG Review: https://github.com/w3ctag/design-reviews/issues/911

**Comment by noamr** [comment]
@emilio @sefeng211 @zcorpan any thoughts on this? We've heard some informal support for this from you guys during 2023 but would love to hear something more formal.

**Comment by sefeng211** [comment]
implementation tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1348405
