### ISSUE TITLE
CSS Houdini

### ISSUE THREAD

**Issue by flaki** [mozilla/standards-positions#93]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: CSS Houdini family features (Paint API, Typed OM, Layout API etc.)
* Specification or proposal URL: [CSS Painting API Level 1](https://drafts.css-houdini.org/css-paint-api/)
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1302328
* Mozillians who can provide input (optional): @tantek, Andrew Overholt

### Other information
* [Intent to Experiment: CSS Houdini Paint API Level 1](https://groups.google.com/forum/#!topic/mozilla.dev.platform/uI5bHZil2KU)
* [CSS/Houdini - Mozilla Wiki](https://wiki.mozilla.org/CSS/Houdini)
* [**META** Implement Houdini CSS Painting API Level 1 spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1302328)
* [**META** Implement Houdini CSS Layout API Level 1 spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1302337)
* [**META** implement Houdini CSS Properties and Values API](https://bugzilla.mozilla.org/show_bug.cgi?id=1273706)
* [**META** Implement CSS Houdini "Worklets Level 1" spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1315239)
* [Houdini "Worklets Level 1" prototype implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1290021)
* [Is Houdini ready yet?](https://ishoudinireadyyet.com/)

Under consideration: _Worklets Level 1, CSS Paint API Level 1, CSS Layout API Level 1_  
Currently being implemented: _CSS Typed OM Level 1, CSS Properties and Values API Level 1_  
— according to [the Mozilla Wiki on DOM/Houdini](https://wiki.mozilla.org/CSS/Houdini)

> _“Worklets is one of the Houdini specs we are "considering" but have no firm implementation plans for. Unlikely for 2018, we can reconsider when doing 2019 CSS priorities.”_
> —  [Tantek Çelik, bugzilla bug #1315239](https://bugzilla.mozilla.org/show_bug.cgi?id=1315239#a47768742_164722)

With Chrome's shipped Paint API and partial implementations of other APIs, coupled various, spec-compliant [polyfills](https://github.com/GoogleChromeLabs/css-paint-polyfill) appearing developer interest seems to be on the rise, with almost all JavaScript/Web-related conferences sporting a talk on the lineup about the magical developer-facing features, and encouraging the audience to start experimenting. Browser support, of course, always comes up (and never fails to chill the excitement of the talk presented), and although @surma's implementation tracker does a good job in summarizing the (current and expected) support of various browsers, a clear cut decision/expectation on various parts of the Houdini family features would be still very useful.

**Comment by tantek** [comment]
Mozilla has been participating in the design and development discussions of Houdini at the CSS Working Group since the beginning and continues to do so.

For Houdini as a whole ("CSS Houdini family features" that have published drafts per this issue), I think the most accurate current summary position is "worth prototyping".

As individual Houdini specifications technically mature (with web developer feedback &amp; iteration) and assuming we see broader use-cases across the web, we can consider stating upgraded positions for each individual specification as appropriate, taking into account the importance of other web platform features.

If anyone has concerns about particular Houdini drafts that should block an explicit "worth prototyping" position, please speak up and we can use "under consideration" while we file issues on those drafts and iterate accordingly.

In addition, since &lt;https://github.com/surma&gt; ’s tracker was mentioned, this overall Houdini position should not be taken to apply to anything that is not yet at least a published working draft.

If an explicit position is desired for proposals in &lt;https://ishoudinireadyyet.com&gt; without a working draft, please file separate issues for those.

(Originally published at: http://tantek.com/2018/172/t2/houdini-worth-prototyping)

**Comment by dbaron** [comment]
I think it's probably best to list all 5 drafts mentioned above (worklets, typed om, properties and values, paint api, and layout api) separately, and I'm happy to list all 5 of them as `worth prototyping` (see the legend at the bottom of [Mozilla Specification Positions](https://mozilla.github.io/standards-positions/)).

/cc @bakulf @dholbert @heycam @mattwoodrow to see if they agree.

**Comment by annevk** [comment]
Worklets is also needed for audio.

My main worry with these APIs is that they haven't been designed with concurrency in mind. At least the last time @bzbarsky went through them there were lots of issues around this.

**Comment by kaizhu256** [comment]
> Typed OM fixes what has been recognized as a longstanding set of poorly designed APIs (and largely deprecated and removed from browsers) in the original CSS OM.

from what i recall on blink-dev mailing list, there was strong rejection against typed-om.  however poorly designed existing api's are, there was little explanation how the extra pedanticity from typed-om would make web-developer lives easier rather than worse off.

**Comment by dbaron** [comment]
Yeah, I guess it's true that Typed OM is substantially less well justified than the other specs.  Maybe it makes sense to change it from `worth prototyping` to `non-harmful`.

**Comment by arxpoetica** [comment]
Can someone update on the Mozilla status on this? I would love to have Typed OM—I'm surprised at the idea that it's not useful.

**Comment by dholbert** [comment]
As far as I know, none of these Houdini APIs are on our roadmap/horizon for implementation at the moment.

**Comment by arxpoetica** [comment]
Why? They are extremely useful APIs. I admit I've been waiting years. You're the bottle neck. Why no show?

**Comment by ekr** [comment]
This repo is intended for the discussion of Mozilla's position on this topic, not about our implementation plans or non-plans. Typed OM is marked "worth prototyping" in our dashboard, so unless you're arguing for a different status, Bugzilla is the correct venue to debate implementation priority.

**Comment by zcorpan** [comment]
I have split this into separate issues (see https://github.com/mozilla/standards-positions/issues/1087):

- #1088 
- #1089 
- #1090 
- #1091 
- #1097

**Comment by emilio** [comment]
FWIW Igalia is implementing TypedOM in Gecko as well (see https://bugzilla.mozilla.org/show_bug.cgi?id=1278697). But yeah I agree performance wise it's not necessarily better. If anything author convenience?

**Comment by emilio** [comment]
FWIW #1091 is the issue for TypedOM in particular.
