### ISSUE TITLE
WebGPU default entry points to shader modules

### ISSUE THREAD

**Issue by beaufortfrancois** [mozilla/standards-positions#931]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: WebGPU
* Specification or proposal URL (if available): https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuprogrammablestage
* Explainer URL (if available): https://github.com/gpuweb/gpuweb/issues/4342
* Proposal author(s) (`@`-mention GitHub accounts): @beaufortfrancois @Kangz
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @jimblandy

**Comment by kdashg** [comment]
As part of community group consensus, we decided to pursue this.
https://github.com/gpuweb/gpuweb/issues/4342#issuecomment-1810496844
As such we don't need this in standards-positions anymore, I think.
