### ISSUE TITLE
MediaTrackSupportedConstraints.eyeGazeCorrection

### ISSUE THREAD

**Issue by riju** [mozilla/standards-positions#934]
* Specification title: MediaTrackSupportedConstraints.eyeGazeCorrection 
* Specification or proposal URL (if available): https://w3c.github.io/mediacapture-extensions/#exposing-mediastreamtrack-source-eye-gaze-correction-support
* Explainer URL (if available): https://github.com/riju/eyeGazeCorrection/blob/main/explainer.md
* Proposal author(s) (`@`-mention GitHub accounts): @riju
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): Jan-Ivar Bruaroey

### Other information

ChromeStatus Entry : https://chromestatus.com/feature/5140905475964928
WebRTC meeting notes: https://lists.w3.org/Archives/Public/www-archive/2023Feb/att-0002/WEBRTCWG-2023-02-21.pdf#page=46

**Comment by jan-ivar** [comment]
This exposes one more camera feature to web developers that might be popular with streamers.

The feature is introduced as a _constraint_, letting applications request it without committing user agents to implementing it.

It would be helpful if there was a [Privacy and Security Considerations](https://www.w3.org/TR/mediacapture-streams/#privacy-and-security-considerations) section like that in the main spec, but in short, like all new constraints, it's not [required](https://www.w3.org/TR/mediacapture-streams/#dfn-allowed-required-constraints-for-device-selection), meaning  it leaves no fingerprint ahead of active camera or microphone access.
