### ISSUE TITLE
CSS Images Level 4: cross-fade()

### ISSUE THREAD

**Issue by sesse** [mozilla/standards-positions#937]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: CSS Images Level 4, specifically the part about unprefixed cross-fade()
* Specification or proposal URL (if available): https://drafts.csswg.org/css-images-4/#cross-fade-function
* Explainer URL (if available): None
* Proposal author(s) (`@`-mention GitHub accounts): @tabatkins
* Mozillians who can provide input (optional): @emilio 

### Other information

We already support -webkit-cross-fade(); this is for implementing the standards-compliant unprefixed cross-fade(). We've gone through HTTP Archive, and it seems there is de-facto a net zero effect. See https://chromestatus.com/feature/5155783434305536 for some more discussion.

**Comment by zcorpan** [comment]
Thanks for filing! Closing as a dup of #417
