### ISSUE TITLE
FileSystemObserver

### ISSUE THREAD

**Issue by a-sully** [mozilla/standards-positions#942]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: FileSystemObserver
* Specification or proposal URL (if available): 
* Explainer URL (if available): https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md
* Proposal author(s): @a-sully
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @janvarga @jesup

### Other information

This feature is being prototyped in Chromium and currently going through a [TAG review](https://github.com/w3ctag/design-reviews/issues/868).

**Comment by asutherland** [comment]
From discussions with the storage team I think we're:
- Positive on the use-case.
- Very appreciative of the the explainer's effort to delineate between Bucket FS and interaction with the local filesystem and the inherent platform limitations that can arise and to avoid setting unrealistic expectations for what a standard could guarantee.
- Wondering if [ReadableStream](https://streams.spec.whatwg.org/#rs-class) might be a way of avoiding introducing the additional `FileSystemObserver` interface and its `FileSystemObserverCallback` callback, but still maintaining `FileSystemChangeRecord` as the data payload. @saschanaz indicates WebCodecs is interested in using ReadableStream for VideoFrame, although as VideoFrames are much more resource intensive, there is some additional discussion around GC/cleanup when the stream closes, captured at https://github.com/whatwg/streams/blob/main/streams-for-raw-video-explainer.md.
  - Given that for the local filesystem case additional support code is presumed to be necessary to provide more precise/actionable data, the ability to use [pipeThrough](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeThrough) to layer in normalization in that case, but not for Bucket FS, could be interesting.

**Comment by zcorpan** [comment]
Thanks @asutherland . Should this have a new dashboard entry?

**Comment by asutherland** [comment]
> Thanks @asutherland . Should this have a new dashboard entry?

I think our existing entry for https://mozilla.github.io/standards-positions/#fs potentially suffices?  It seems rather foundational to the spec, although it was large enough that it was appropriate to create this issue and request TAG review of the explainer.  (https://github.com/mozilla/standards-positions/blob/main/CONTRIBUTING.md could provide more clarity on where the dividing line is.)
