### ISSUE TITLE
WebAssembly JS Promise Integration

### ISSUE THREAD

**Issue by fgmccabe** [mozilla/standards-positions#944]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: JS Promise Integration
* Specification or proposal URL (if available): https://github.com/WebAssembly/js-promise-integration
* Explainer URL (if available):https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md
* Proposal author(s) (`@`-mention GitHub accounts): @fgmccabe, Ross Tate
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): Ryan Hunt, Yuri Delendik

**Comment by eqrion** [comment]
We're supportive of this proposal and have begun prototyping it out (https://bugzilla.mozilla.org/show_bug.cgi?id=1850627).

It should address a major paint point for developers porting existing applications that assume synchronous I/O to the web (which uses promises). It's also a first step to supporting more powerful stack-switching features that could be useful to languages like Go/Dart/Kotlin.

**Comment by mnoorenberghe** [comment]
This issue title is missing the WASM context so is confusing. The specification title is also incorrect. It should be: 

> JavaScript-Promise Integration Proposal for WebAssembly
