### ISSUE TITLE
TLS certificate compression

### ISSUE THREAD

**Issue by davidben** [mozilla/standards-positions#96]
## Request for Mozilla Position on an Emerging Web Specification

* Specification Title: Transport Layer Security (TLS) Certificate Compression
* Specification or proposal URL: https://tools.ietf.org/html/draft-ietf-tls-certificate-compression-03
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

### Other information

Filing this since we're discussing it in https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/DkMcAxxUQGI. Mozilla folks have weighed in individually at the IETF, but I figure I may ask for a more official position since it seems easy. (Very cool repo!)

**Comment by martinthomson** [comment]
As we've indicated, I think that we've agreed that this is good.  For me, this is `worth prototyping` (not `important`, even if we might eventually conclude that the performance benefits are that significant).

**Comment by dbaron** [comment]
cc:ing @ekr as well, to double-check that he agrees with @martinthomson  `worth prototyping` suggestion here.

**Comment by ekr** [comment]
I concur.

**Comment by dbaron** [comment]
Oh, @martinthomson already added this in #97, but didn't resolve or link to this issue...
