### ISSUE TITLE
WebSockets: Allow http(s) scheme and relative URLs

### ISSUE THREAD

**Issue by CanadaHonk** [mozilla/standards-positions#966]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: WHATWG WebSockets PR - Allow HTTP(S) schemes in the WebSocket constructor 
* Specification or proposal URL (if available): https://github.com/whatwg/websockets/pull/45
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1797449

**Comment by bgrins** [comment]
This is a nice ergonomic improvement. Quoting @zcorpan in https://github.com/whatwg/websockets/pull/45#issuecomment-1543876080:

> Mozilla is supportive of this change.
