### ISSUE TITLE
Fetch keepalive

### ISSUE THREAD

**Issue by valenting** [mozilla/standards-positions#967]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Fetch keepalive
* Specification or proposal URL (if available): https://fetch.spec.whatwg.org/#ref-for-dom-request-keepalive
* Explainer URL (if available): https://github.com/whatwg/fetch/issues/124
* Proposal author(s) (`@`-mention GitHub accounts): @igrigorik and @annevk
* Caniuse.com URL (optional): https://caniuse.com/mdn-api_fetch_init_keepalive_parameter
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1342484
* Mozillians who can provide input (optional): @MayyaSunil

### Other information

[MDN link for fetch keepalive parameter](https://developer.mozilla.org/en-US/docs/Web/API/fetch#keepalive)
[Chrome feature status](https://chromestatus.com/feature/5760375567941632)
[Safari 168865 – Fetch API Support keepalive flag and enforce limit on inflight keepalive bytes](https://bugs.webkit.org/show_bug.cgi?id=168865)

**Comment by zcorpan** [comment]
Spec issues mentioning keepalive:
- https://github.com/whatwg/fetch/issues?q=is%3Aissue+is%3Aopen+keepalive
- related for HTML `img`: https://github.com/whatwg/html/issues/1655

In particular https://github.com/whatwg/fetch/issues/679 warrants consideration.

Keepalive is already part of the web platform with [`sendBeacon`](https://w3c.github.io/beacon/#sendbeacon-method) and the `img` element (in unload), so supporting it in `fetch()` makes sense I think.
