### ISSUE TITLE
The `pageconceal` event (part of cross-document view-transitions)

### ISSUE THREAD

**Issue by noamr** [mozilla/standards-positions#969]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: The `pageconceal` event
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/10002
* Explainer URL (if available): https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md#pageconceal
* Proposal author(s) (`@`-mention GitHub accounts): @noamr @khushalsagar @vmpstr
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): @zcorpan @smaug---- 

### Other information
This is developed as part of cross-document view-transitions, but we're sending separate RFPs for  the sub-features that can work outside the context of view-transitions, to make sure we're all on the same page.

**Comment by zcorpan** [comment]
I think this proposal is reasonable. @smaug---- @petervanderbeken any concerns?

**Comment by smaug----** [comment]
I've been waiting for response to my question in the spec issue https://github.com/whatwg/html/issues/9702#issuecomment-1917193911
(I'd rather not start painting background tabs)

**Comment by noamr** [comment]
> I've been waiting for response to my question in the spec issue [whatwg/html#9702 (comment)](https://github.com/whatwg/html/issues/9702#issuecomment-1917193911) (I'd rather not start painting background tabs, if possible. Those are heavily throttled)

Sorry I totally missed that comment, responded now.

**Comment by khushalsagar** [comment]
FYI, the event was finally renamed to `pageswap`. See the final spec here: https://html.spec.whatwg.org/#the-pageswapevent-interface.

**Comment by khushalsagar** [comment]
Heads up on a minor change to this event: https://github.com/whatwg/html/issues/10196. Please let me know if this position needs to be revisited for this change.
