### ISSUE TITLE
Make computation of directionality account for Shadow DOM

### ISSUE THREAD

**Issue by hsinyi** [mozilla/standards-positions#974]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: Make computation of directionality account for Shadow DOM
* Specification or proposal URL (if available): https://github.com/whatwg/html/pull/9796
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): @dbaron 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=1876163
* Mozillians who can provide input (optional): @zcorpan

**Comment by smaug----** [comment]
Yes. I wasn't expecting this to get a standards position.
The spec may of course get tweaked a bit while folks implement it.
