### ISSUE TITLE
The textInput event

### ISSUE THREAD

**Issue by zcorpan** [mozilla/standards-positions#975]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: UI Events - the `textInput` event
* Specification or proposal URL (if available): https://github.com/w3c/uievents/pull/362
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): @zcorpan
* Caniuse.com URL (optional):
* Bugzilla URL (optional): https://bugzilla.mozilla.org/show_bug.cgi?id=903746
* Mozillians who can provide input (optional): @masayuki-nakano

### Other information

Spec issue: https://github.com/w3c/uievents/issues/353

**Comment by zcorpan** [comment]
This event is technically redundant with the `beforeinput` event (which is fired in more cases and has richer information).

It's also used by web content sufficiently that it needs to be supported to be compatible.

I think there isn't anything particularly negative for the web with this event existing. Suggest a neutral position.

**Comment by masayuki-nakano** [comment]
I agree with standardizing this event, but there is only once concern, that is, if some web apps which uses `textInput`, they **might** also use `beforeinput` or something others when running in Firefox due to some logical bugs. Anyway, we should prototype it and test in a couple of cycles.
