### ISSUE TITLE
CSS margin-trim property

### ISSUE THREAD

**Issue by nileshprajapati** [mozilla/standards-positions#994]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: 
* Specification or proposal URL (if available): https://www.w3.org/TR/css-box-4/
* Explainer URL (if available):
* Proposal author(s) (`@`-mention GitHub accounts): 
* Caniuse.com URL (optional):  https://caniuse.com/?search=margin-trim
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional):

**Comment by zcorpan** [comment]
cc @dholbert

**Comment by dholbert** [comment]
Ah sorry, it looks like I overlooked the CC here.

Note that we do have a bugzilla link for this, which is https://bugzilla.mozilla.org/show_bug.cgi?id=1506241 , and Chromium's issue is https://issues.chromium.org/issues/40886857

I'd say we're 'positive' here; this is a relatively targeted feature that addresses a demonstrated need.  The spec still has some open issues (at end of sections 3.3 and 3.4 in the spec, RE what effect this has in fragmented contexts, and in the inline axis, and on inline-level elements), so those probably need to be shaken out before we start implementing. But assuming reasonable resolutions to those issues, I'm in favor of supporting this.

**Comment by zcorpan** [comment]
Sounds good. Closing without a dashboard entry, as it seems like a minor feature.
