### ISSUE TITLE
MediaRecorder: Support mp4 container with avc1 and mp4a.40.2 codecs for MediaRecorder

### ISSUE THREAD

**Issue by sunggook** [mozilla/standards-positions#996]
## Request for Mozilla Position on an Emerging Web Specification

* Specification title: MP4 container for MediaRecorder.
* Specification or proposal URL (if available): https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder
* Explainer URL (if available): https://docs.google.com/document/d/1WV795DHY3Jf2p_htuAKZ9DXUefiGdQs29mCb8vRiHt8/edit?usp=sharing
* Proposal author(s) (`@`-[mention GitHub accounts] @sunggook [https://github.com/sunggook]: 
* Caniuse.com URL (optional): 
* Bugzilla URL (optional): 
* Mozillians who can provide input (optional): 

### Other information
Chromestatus: https://chromestatus.com/feature/5163469011943424?gate=5159325630988288

**Comment by padenot** [comment]
Makes sense to have this on the higher level API since it's available in Web Codecs.

`positive`.
